SounDroid: BlueToothLib.c File Reference
BlueToothLib.c File Reference
The library for client-server connection by blue tooth Sending text messages and getting addresses of the local blue tooth adapter and a connected one.
#include "service.h"
#include "BlueToothLib.h"
#include "synchronise.h"
#include "Log.h"
#include "addr.h"
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <netdb.h>
Macros
#define STR_END "end"
#define TAG "BT_LIB"
The tag for writing to the log file.
#define MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT 1
The maximal number of sockets waiting for accept.
#define MAX_BT_DEV_NAME_LEN 50
The maximal length of bluetooth device.
Functions
const char * getLocalAddr ()
Get local address string.
const char * getConnectedAddr ()
Get connected address string.
const int closeBtSocketConn (const int sockDescr)
Close the socket connection.
const int createBtSocket ()
Create blue tooth socket.
const int bindBtSocket (const int sockDescr)
Bind the socket with the given descriptor.
void initLocalAdapterName ()
Initialize the name of the local bluetooth adapter.
const int initBtConnectionBeforeListen ()
Initialize the connection before listening.
const int listenBtConns (const int sockDescr)
Listen to new connections.
const int acceptBtConn (const int sockDescr)
Accept a connection.
const char * receiveBtData (const int newSockDescr, char *incoming_data_buffer, const size_t buff_len)
Receive a data from a client.
const int sendBtData (const int socketDescr)
Send data by sockets.
const int conversationBt (char *incoming_data_buffer, const size_t buff_len, const int socket)
Client-server conversation.
void runBtConnection (const int sockDescr)
Run client-server connection.
Variables
char connectedAdapterName [MAX_BT_DEV_NAME_LEN] = { 0 }
The string of the name of a connected device.
char localAdapterName [MAX_BT_DEV_NAME_LEN] = { 0 }
The string of the name of the local adapter.
Detailed Description
The library for client-server connection by blue tooth Sending text messages and getting addresses of the local blue tooth adapter and a connected one.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file BlueToothLib.c.
Macro Definition Documentation
#define MAX_BT_DEV_NAME_LEN 50
The maximal length of bluetooth device.
Definition at line 57 of file BlueToothLib.c.
Referenced by acceptBtConn(), and initLocalAdapterName().
#define MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT 1
The maximal number of sockets waiting for accept.
Definition at line 55 of file BlueToothLib.c.
Referenced by listenBtConns().
#define STR_END "end"
Definition at line 52 of file BlueToothLib.c.
Referenced by conversationBt(), and receiveBtData().
#define TAG "BT_LIB"
The tag for writing to the log file.
Definition at line 53 of file BlueToothLib.c.
Referenced by acceptBtConn(), bindBtSocket(), closeBtSocketConn(), conversationBt(), createBtSocket(), getLocalAddr(), initLocalAdapterName(), listenBtConns(), receiveBtData(), and sendBtData().
Function Documentation
const int acceptBtConn (const int sockDescr)
Accept a connection.
Parameters
sockDescr A socket's descriptor
Returns
ERR if there is an error. Any other number if there is no error
Definition at line 201 of file BlueToothLib.c.
References connectedAdapterName, ERR, getRunStatus(), MAX_BT_DEV_NAME_LEN, MILLISECONDS_SLEEP_TIME, STOP, TAG, writeToLog(), writeToLog2(), and writeToLogIfError().
Referenced by runBtConnection().
const int bindBtSocket (const int sockDescr)
Bind the socket with the given descriptor.
Parameters
sockDescr The socket descriptor
Returns
The status of binding
Definition at line 127 of file BlueToothLib.c.
References TAG, writeToLog(), and writeToLogIfError().
Referenced by initBtConnectionBeforeListen().
const int closeBtSocketConn (const int sockDescr)
Close the socket connection.
Parameters
sockDescr The socket descriptor of the connection
Returns
The result integer of closing
Definition at line 86 of file BlueToothLib.c.
References ERR, TAG, writeToLog(), and writeToLogIfError().
Referenced by createBtSocket(), initBtConnectionBeforeListen(), and runBtConnection().
const int conversationBt (char * incoming_data_buffer, const size_t buff_len, const int socket)
Client-server conversation.
Parameters
incoming_data_buffer The string buffer for the incoming from the client data
buff_len The length of the data(send/receive) buffer
socket The socket descriptor of the conversation
Returns
The integer status of the conversation: ERR, NO_ERR or STOP if received the connection end message
Definition at line 333 of file BlueToothLib.c.
References ERR, getSentData(), HAS_NEW_DATA, receiveBtData(), sendBtData(), setReceivedData(), setReceivedDataStatus(), STOP, STR_END, TAG, writeToLog(), and writeToLog2().
Referenced by runBtConnection().
const int createBtSocket ()
Create blue tooth socket.
Returns
The socket descriptor
Definition at line 103 of file BlueToothLib.c.
References closeBtSocketConn(), ERR, TAG, writeToLog(), writeToLog2(), and writeToLogIfError().
Referenced by initBtConnectionBeforeListen().
const char* getConnectedAddr ()
Get connected address string.
Returns
The string of the connected address or ""
Definition at line 75 of file BlueToothLib.c.
References connectedAdapterName.
const char* getLocalAddr ()
Get local address string.
Returns
The string of the local address or ""
Definition at line 65 of file BlueToothLib.c.
References localAdapterName, TAG, and writeToLog2().
const int initBtConnectionBeforeListen ()
Initialize the connection before listening.
Initialize connection before listening.
Returns
socket descriptor or ERR
Definition at line 166 of file BlueToothLib.c.
References bindBtSocket(), closeBtSocketConn(), createBtSocket(), ERR, and initLocalAdapterName().
Referenced by ConnectorBT::ConnectorBT().
void initLocalAdapterName ()
Initialize the name of the local bluetooth adapter.
Definition at line 146 of file BlueToothLib.c.
References localAdapterName, MAX_BT_DEV_NAME_LEN, TAG, and writeToLog2().
Referenced by initBtConnectionBeforeListen().
const int listenBtConns (const int sockDescr)
Listen to new connections.
Parameters
sockDescr A socket's descriptor
Returns
ERR if there is an error. Any other number if there is no error
Definition at line 186 of file BlueToothLib.c.
References MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT, TAG, writeToLog(), and writeToLogIfError().
Referenced by runBtConnection().
const char* receiveBtData (const int newSockDescr, char * incoming_data_buffer, const size_t buff_len)
Receive a data from a client.
Parameters
newSockDescr A socket's descriptor
incoming_data_buffer The buffer for incoming data
buff_len The length of the data's buffer
Returns
The buffer of the incoming data or NULL if there is an error
Definition at line 247 of file BlueToothLib.c.
References ERR, getRunStatus(), MILLISECONDS_SLEEP_TIME, STOP, STR_END, TAG, writeToLog(), and writeToLog2().
Referenced by conversationBt().
void runBtConnection (const int sockDescr)
Run client-server connection.
Parameters
sockDescr Socket deskriptor of the server
Definition at line 372 of file BlueToothLib.c.
References acceptBtConn(), closeBtSocketConn(), connectedAdapterName, conversationBt(), DATA_LEN, destroyMutexes(), ERR, getRunStatus(), initMutexes(), listenBtConns(), NO_ERR, and STOP.
Referenced by ConnectorBT::run().
const int sendBtData (const int socketDescr)
Send data by sockets.
Parameters
socketDescr The socket descriptor
Returns
ERR or NO_ERR
Definition at line 300 of file BlueToothLib.c.
References ERR, getSentData(), NO_ERR, sentData, TAG, writeToLog(), and writeToLog2().
Referenced by conversationBt().
Variable Documentation
char connectedAdapterName[MAX_BT_DEV_NAME_LEN] = { 0 }
The string of the name of a connected device.
Definition at line 58 of file BlueToothLib.c.
Referenced by acceptBtConn(), getConnectedAddr(), and runBtConnection().
char localAdapterName[MAX_BT_DEV_NAME_LEN] = { 0 }
The string of the name of the local adapter.
Definition at line 59 of file BlueToothLib.c.
Referenced by getLocalAddr(), and initLocalAdapterName().