SounDroid: ConnectorWiFi Class Reference
ConnectorWiFi Class Reference
The class should send, receive string data between the daemon and a connected clint, make port operations.
#include <ConnectorWiFi.h>
Inherits NetConnector.
Public Member Functions
ConnectorWiFi (const string &portNum) throw (PortException)
Constructor.
~ConnectorWiFi ()
Destructor.
void run ()
Run the connector.
bool isRunning () const
Is the connector running?
void send (const string &dataStr)
Send data string to connector.
const string receive ()
Get a data string arrived to the connector.
void stop ()
Stop the connector.
const string getLocalAddrStr () const
Get the string of the local IP.
const string getConnectedAddrStr () const
Get the string of the connected IP.
const string getUsedPort () const
Get the string of the currently used port number.
void setPortNum (const string &portNum) throw (PortException)
Set the port number.
const string getLastErrStr () const
Get the last error string.
const bool isPortAvailable ()
Is the currently used port available.
Public Member Functions inherited from Connector
virtual ~Connector ()
Destructor.
virtual void send (const std::string &dataStr)=0
Send data string to connector.
Private Member Functions
ConnectorWiFi ()=delete
string convertLong2Str (const long num)
Convert the given long number to a string.
void processPortNumErr (const string &errStr) const throw (PortException)
Process the error of a port number.
Private Attributes
string portNumStr_
The string of the currently used port number.
mutex mutex_
int socketDescr
The currently used socket descriptor.
Static Private Attributes
static const char * TAG = "NET_CONNECTOR"
The tag for writing to the log file.
Detailed Description
The class should send, receive string data between the daemon and a connected clint, make port operations.
Definition at line 44 of file ConnectorWiFi.h.
Constructor & Destructor Documentation
ConnectorWiFi::ConnectorWiFi () private delete
ConnectorWiFi::ConnectorWiFi (const string & portNum) throw (PortException) inline
Constructor.
Parameters
portNum The string of a port number
Definition at line 75 of file ConnectorWiFi.h.
References portNum.
ConnectorWiFi::~ConnectorWiFi () inline
Destructor.
Definition at line 80 of file ConnectorWiFi.h.
Member Function Documentation
string ConnectorWiFi::convertLong2Str (const long num) private
Convert the given long number to a string.
Parameters
num The long number
Returns
The string of the converted number
const string ConnectorWiFi::getConnectedAddrStr () const virtual
Get the string of the connected IP.
Get the IP string of a connected client.
Returns
The string of the IP
The IP string of the connected client or "" if there is no one connected
Implements NetConnector.
Definition at line 177 of file ConnectorWiFi.cpp.
References getConnectedAddr(), TAG, and writeToLog().
const string ConnectorWiFi::getLastErrStr () const virtual
Get the last error string.
Returns
The string of the last error
The last error string
Implements NetConnector.
Definition at line 130 of file ConnectorWiFi.cpp.
References getErrStr().
const string ConnectorWiFi::getLocalAddrStr () const virtual
Get the string of the local IP.
Returns
The string of the local IP
The local IP string or "" if the IP hasn't found
Implements NetConnector.
Definition at line 162 of file ConnectorWiFi.cpp.
References getLocalAddr(), TAG, and writeToLog().
const string ConnectorWiFi::getUsedPort () const inline virtual
Get the string of the currently used port number.
Returns
The string of the port number
Implements NetConnector.
Definition at line 126 of file ConnectorWiFi.h.
const bool ConnectorWiFi::isPortAvailable () virtual
Is the currently used port available.
Is the currently used port number available?
Returns
true The port available
true The port is available
Implements NetConnector.
Definition at line 101 of file ConnectorWiFi.cpp.
References ERR, initConnectionBeforeListen(), and socketDescr.
bool ConnectorWiFi::isRunning () const
Is the connector running?
Returns
true The connector is running
Definition at line 121 of file ConnectorWiFi.cpp.
References getRunStatus(), and RUN.
void ConnectorWiFi::processPortNumErr (const string & errStr) const throw (PortException) private
Process the error of a port number.
Process the string of the port number error The error will be written to log file and thrown by exception.
Parameters
errStr The string with the error
errStr The string of error
Definition at line 82 of file ConnectorWiFi.cpp.
References TAG, and writeToLog().
const string ConnectorWiFi::receive () virtual
Get a data string arrived to the connector.
Receive the data from client.
Returns
The arrived data string
The string of the received data
Implements Connector.
Definition at line 139 of file ConnectorWiFi.cpp.
References getReceivedData().
void ConnectorWiFi::run () virtual
Run the connector.
Implements Connector.
Definition at line 110 of file ConnectorWiFi.cpp.
References RUN, runConnection(), setRunStatus(), socketDescr, and STOP.
void ConnectorWiFi::send (const string & dataStr)
Send data string to connector.
Send the given data string to client.
Parameters
dataStr The string of the sent data
dataStr The data string
Definition at line 148 of file ConnectorWiFi.cpp.
References setSentData(), TAG, and writeToLog().
void ConnectorWiFi::setPortNum (const string & portNum) throw (PortException) virtual
Set the port number.
Set the given port number.
Parameters
portNum The string of the new port number string
portNum The string with the port number
Implements NetConnector.
Definition at line 55 of file ConnectorWiFi.cpp.
References ERR, portNum, and setPort().
void ConnectorWiFi::stop () virtual
Stop the connector.
Implements Connector.
Definition at line 91 of file ConnectorWiFi.cpp.
References portNumStr_, runClosingClient(), setRunStatus(), and STOP.
Field Documentation
mutex ConnectorWiFi::mutex_ private
Definition at line 50 of file ConnectorWiFi.h.
string ConnectorWiFi::portNumStr_ private
The string of the currently used port number.
Definition at line 48 of file ConnectorWiFi.h.
Referenced by stop().
int ConnectorWiFi::socketDescr private
The currently used socket descriptor.
Definition at line 52 of file ConnectorWiFi.h.
Referenced by isPortAvailable(), and run().
const char * ConnectorWiFi::TAG = "NET_CONNECTOR" static private
The tag for writing to the log file.
The tag for writting to log file.
Definition at line 46 of file ConnectorWiFi.h.
Referenced by getConnectedAddrStr(), getLocalAddrStr(), and send().
The documentation for this class was generated from the following files:
ConnectorWiFi.h
ConnectorWiFi.cpp