SounDroid: GuiConnector Class Reference
GuiConnector Class Reference
The class for connecting the daemon to its GUI.
#include <GuiConnector.h>
Inherits Connector.
Public Member Functions
GuiConnector () throw (GuiException)
Constructor.
~GuiConnector ()
Destructor.
void run ()
Run the connector.
void stop ()
Stop the connector.
void send (const std::string &newDataStr)
Send data string to connector.
const std::string receive ()
Get a data string arrived to the connector.
Public Member Functions inherited from Connector
virtual ~Connector ()
Destructor.
Private Member Functions
bool isStopped ()
Is the connector stopped?
Private Attributes
bool toStop_
Should the connector be stopped?
std::mutex mutex_
Static Private Attributes
static constexpr const char * TAG = "GUI_CONNECTOR"
The tag for writing to the log file.
Detailed Description
The class for connecting the daemon to its GUI.
Definition at line 41 of file GuiConnector.h.
Constructor & Destructor Documentation
GuiConnector::GuiConnector () throw (GuiException)
Constructor.
Definition at line 46 of file GuiConnector.cpp.
References initQueueServer().
GuiConnector::~GuiConnector () inline
Destructor.
Definition at line 63 of file GuiConnector.h.
Member Function Documentation
bool GuiConnector::isStopped () private
Is the connector stopped?
Returns
true The connector has been stopped
true The connector is stopped
Definition at line 68 of file GuiConnector.cpp.
const string GuiConnector::receive () virtual
Get a data string arrived to the connector.
Receive a data string from GUI.
Returns
The arrived data string
The data string from GUI
Implements Connector.
Definition at line 103 of file GuiConnector.cpp.
References receiveMsgServer().
void GuiConnector::run () virtual
Run the connector.
Run the connector It runs the messages queue for sending and receiving commands or data to GUI.
Implements Connector.
Definition at line 59 of file GuiConnector.cpp.
References runQueue().
Referenced by CommandsDispatcherBT::initThreads(), and CommandsDispatcherWiFi::initThreads().
void GuiConnector::send (const std::string & newDataStr) virtual
Send data string to connector.
Send the given data string to GUI.
Parameters
newDataStr The string of the sent data
newDataStr The data string for sending
Implements Connector.
Definition at line 93 of file GuiConnector.cpp.
References sendMsgServer().
void GuiConnector::stop () virtual
Stop the connector.
Implements Connector.
Definition at line 80 of file GuiConnector.cpp.
References deleteQueue().
Field Documentation
std::mutex GuiConnector::mutex_ private
Definition at line 46 of file GuiConnector.h.
constexpr const char* GuiConnector::TAG = "GUI_CONNECTOR" static private
The tag for writing to the log file.
Definition at line 43 of file GuiConnector.h.
bool GuiConnector::toStop_ private
Should the connector be stopped?
Definition at line 45 of file GuiConnector.h.
The documentation for this class was generated from the following files:
GuiConnector.h
GuiConnector.cpp