SounDroid: NetConnector Class Reference
NetConnector Class Reference abstract
The abstract class of the network connector.
#include <NetConnector.h>
Inherits Connector.
Inherited by ConnectorBT, and ConnectorWiFi.
Public Member Functions
virtual const string getLocalAddrStr () const =0
Get the string of the local address.
virtual const string getConnectedAddrStr () const =0
Get the string of the connected address.
virtual const string getUsedPort () const =0
Get the string of the currently used port number.
virtual void setPortNum (const string &portNum)=0 throw (PortException)
Set the port number.
virtual const bool isPortAvailable ()=0
Is the currently used port available.
virtual const string getLastErrStr () const =0
Get the last error string.
Public Member Functions inherited from Connector
virtual ~Connector ()
Destructor.
virtual void send (const std::string &dataStr)=0
Send data string to connector.
virtual const std::string receive ()=0
Get a data string arrived to the connector.
virtual void stop ()=0
Stop the connector.
virtual void run ()=0
Run the connector.
Detailed Description
The abstract class of the network connector.
Definition at line 41 of file NetConnector.h.
Member Function Documentation
virtual const string NetConnector::getConnectedAddrStr () const pure virtual
Get the string of the connected address.
Returns
The string of the address
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandGetConnectedIP::execute().
virtual const string NetConnector::getLastErrStr () const pure virtual
Get the last error string.
Returns
The string of the last error
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandsDispatcherWiFi::initThreads().
virtual const string NetConnector::getLocalAddrStr () const pure virtual
Get the string of the local address.
Returns
The string of the local address
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandGetLocalIP::execute().
virtual const string NetConnector::getUsedPort () const pure virtual
Get the string of the currently used port number.
Returns
The string of the port number
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandGetPort::execute(), and CommandsDispatcherWiFi::restartNetConnector().
virtual const bool NetConnector::isPortAvailable () pure virtual
Is the currently used port available.
Returns
true The port available
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandsDispatcherWiFi::chgNetConnectorPort(), and CommandsDispatcherWiFi::initThreads().
virtual void NetConnector::setPortNum (const string & portNum) throw (PortException) pure virtual
Set the port number.
Parameters
portNum The string of the new port number string
Implemented in ConnectorWiFi, and ConnectorBT.
Referenced by CommandsDispatcherWiFi::chgNetConnectorPort().
The documentation for this class was generated from the following file:
NetConnector.h