SounDroid: SndConnector Class Reference
SndConnector Class Reference
Class for changing sound volume and its state(mute/unmute)
#include <SndConnector.h>
Inherits Connector.
Public Member Functions
SndConnector ()
Constructor.
~SndConnector ()
Destructor.
void run ()
Run the connector.
void stop ()
Stop the connector.
void send (const std::string &newDataStr)
Send data string to connector.
const std::string receive ()
Get a data string arrived to the connector.
void doMute ()
Make the system sound state muted.
void doUnmute ()
Make the system sound state unmuted.
void doChgVol (const int value)
Change system's sound volume.
const std::string doGetVol ()
Get the sting of the current system's sound volume value.
const std::string doIsMuted ()
Is the system's sound muted?
Public Member Functions inherited from Connector
virtual ~Connector ()
Destructor.
Private Member Functions
void setArrivedDataStr (const std::string &str)
Set the string of an arrived data.
Private Attributes
std::mutex mutex_
std::string dataStr_
The string of a data.
Static Private Attributes
static const char * TAG = "SND_CONNECTOR"
The tag for writing to the log file.
Detailed Description
Class for changing sound volume and its state(mute/unmute)
Definition at line 40 of file SndConnector.h.
Constructor & Destructor Documentation
SndConnector::SndConnector () inline
Constructor.
Definition at line 58 of file SndConnector.h.
SndConnector::~SndConnector () inline
Destructor.
Definition at line 63 of file SndConnector.h.
Member Function Documentation
void SndConnector::doChgVol (const int value)
Change system's sound volume.
Change the sound system volume to the given value.
Parameters
value The value which the volume should be changed to
value The value in percent
Definition at line 88 of file SndConnector.cpp.
References chgVol(), OK, TAG, and writeToLog().
const string SndConnector::doGetVol ()
Get the sting of the current system's sound volume value.
Get the current value (in percent) of the sound system volume.
Returns
The string of the value
The string of the current volume value
Definition at line 99 of file SndConnector.cpp.
References getVol(), TAG, and writeToLog().
const string SndConnector::doIsMuted ()
Is the system's sound muted?
Is the current sound system state MUTE?
Returns
true The system's sound muted
"true" of "false" strings
Definition at line 110 of file SndConnector.cpp.
References FALSE_, isMuted(), TAG, TRUE_, and writeToLog().
Referenced by CommandIsMuted::execute().
void SndConnector::doMute ()
Make the system sound state muted.
Mute the sound system volume.
Definition at line 67 of file SndConnector.cpp.
References mute(), OK, TAG, and writeToLog().
Referenced by CommandMute::execute().
void SndConnector::doUnmute ()
Make the system sound state unmuted.
Unmute the sound system volume.
Definition at line 77 of file SndConnector.cpp.
References OK, TAG, unmute(), and writeToLog().
Referenced by CommandUnMute::execute().
const string SndConnector::receive () virtual
Get a data string arrived to the connector.
Receive data from the connector.
Returns
The arrived data string
The data string
Implements Connector.
Definition at line 57 of file SndConnector.cpp.
Referenced by CommandMute::execute(), and CommandUnMute::execute().
void SndConnector::run () inline virtual
Run the connector.
Implements Connector.
Definition at line 68 of file SndConnector.h.
void SndConnector::send (const std::string & newDataStr) inline virtual
Send data string to connector.
Parameters
newDataStr The string of the sent data
Implements Connector.
Definition at line 79 of file SndConnector.h.
void SndConnector::setArrivedDataStr (const std::string & str) private
Set the string of an arrived data.
Set the given string as arrived data.
Parameters
str The string of the arrived data
str The string for setting of the arrived data
Definition at line 46 of file SndConnector.cpp.
void SndConnector::stop () inline virtual
Stop the connector.
Implements Connector.
Definition at line 73 of file SndConnector.h.
Field Documentation
std::string SndConnector::dataStr_ private
The string of a data.
Definition at line 44 of file SndConnector.h.
std::mutex SndConnector::mutex_ private
Definition at line 42 of file SndConnector.h.
const char * SndConnector::TAG = "SND_CONNECTOR" static private
The tag for writing to the log file.
The tag for writting to log file.
Definition at line 46 of file SndConnector.h.
The documentation for this class was generated from the following files:
SndConnector.h
SndConnector.cpp