SounDroid: ConnectorBT Class Reference
ConnectorBT Class Reference
The class should send, receive string data between the daemon and a connected clint, make port operations.
#include <ConnectorBT.h>
Inherits NetConnector.
Public Member Functions
ConnectorBT ()
Constructor.
~ConnectorBT ()
Destructor.
void run ()
Run the connector.
bool isRunning () const
Is the connector running?
void send (const string &dataStr)
Send data string to connector.
const string receive ()
Get a data string arrived to the connector.
void stop ()
Stop the connector.
const string getLocalAddrStr () const
Get the string of the local address.
const string getConnectedAddrStr () const
Get the string of the connected address.
const string getLastErrStr () const
Get the last error string.
const string getUsedPort () const
Get the string of the currently used port number.
void setPortNum (const string &portNum) throw (PortException)
Set the port number.
const bool isPortAvailable ()
Is the currently used port available.
Public Member Functions inherited from Connector
virtual ~Connector ()
Destructor.
virtual void send (const std::string &dataStr)=0
Send data string to connector.
Private Member Functions
const char * callToFuncFromDynLib (const char *funcName, const char *libName) const
Call to the function from a dynamic library.
Private Attributes
mutex mutex_
int socketDescr
The currently used socket descriptor.
Static Private Attributes
static const char * TAG = "BT_CONNECTOR"
The tag for writing to the log file.
Detailed Description
The class should send, receive string data between the daemon and a connected clint, make port operations.
Definition at line 44 of file ConnectorBT.h.
Constructor & Destructor Documentation
ConnectorBT::ConnectorBT ()
Constructor.
Definition at line 49 of file ConnectorBT.cpp.
References initBtConnectionBeforeListen().
ConnectorBT::~ConnectorBT () inline
Destructor.
Definition at line 70 of file ConnectorBT.h.
Member Function Documentation
const char * ConnectorBT::callToFuncFromDynLib (const char * funcName, const char * libName) const private
Call to the function from a dynamic library.
Parameters
funcName The name of the function
libName The name of the library
Returns
The string result of the function
Definition at line 119 of file ConnectorBT.cpp.
References handle, TAG, writeToLog(), and writeToLog2().
Referenced by getConnectedAddrStr(), and getLocalAddrStr().
const string ConnectorBT::getConnectedAddrStr () const virtual
Get the string of the connected address.
Get the IP string of a connected client.
Returns
The string of the address
The IP string of the connected client or "" if there is no one connected
Implements NetConnector.
Definition at line 167 of file ConnectorBT.cpp.
References BT_DYN_LIB, callToFuncFromDynLib(), TAG, and writeToLog().
const string ConnectorBT::getLastErrStr () const virtual
Get the last error string.
Returns
The string of the last error
The last error string
Implements NetConnector.
Definition at line 85 of file ConnectorBT.cpp.
const string ConnectorBT::getLocalAddrStr () const virtual
Get the string of the local address.
Returns
The string of the local address
The local address string or "" if the address hasn't found
Implements NetConnector.
Definition at line 152 of file ConnectorBT.cpp.
References BT_DYN_LIB, callToFuncFromDynLib(), TAG, and writeToLog().
const string ConnectorBT::getUsedPort () const virtual
Get the string of the currently used port number.
Returns
The string of the port number
Implements NetConnector.
Definition at line 183 of file ConnectorBT.cpp.
References TAG, and writeToLog().
const bool ConnectorBT::isPortAvailable () virtual
Is the currently used port available.
Returns
true The port available
Implements NetConnector.
Definition at line 202 of file ConnectorBT.cpp.
References TAG, and writeToLog().
bool ConnectorBT::isRunning () const
Is the connector running?
Returns
true The connector is running
Definition at line 76 of file ConnectorBT.cpp.
References getRunStatus(), and RUN.
const string ConnectorBT::receive () virtual
Get a data string arrived to the connector.
Receive the data from client.
Returns
The arrived data string
The string of the received data
Implements Connector.
Definition at line 94 of file ConnectorBT.cpp.
References getReceivedData().
void ConnectorBT::run () virtual
Run the connector.
Implements Connector.
Definition at line 65 of file ConnectorBT.cpp.
References RUN, runBtConnection(), setRunStatus(), socketDescr, and STOP.
void ConnectorBT::send (const string & dataStr)
Send data string to connector.
Send the given data string to client.
Parameters
dataStr The string of the sent data
dataStr The data string
Definition at line 103 of file ConnectorBT.cpp.
References setSentData(), TAG, and writeToLog().
void ConnectorBT::setPortNum (const string & portNum) throw (PortException) virtual
Set the port number.
Parameters
portNum The string of the new port number string
Implements NetConnector.
Definition at line 193 of file ConnectorBT.cpp.
void ConnectorBT::stop () virtual
Stop the connector.
Implements Connector.
Definition at line 57 of file ConnectorBT.cpp.
References setRunStatus(), and STOP.
Field Documentation
mutex ConnectorBT::mutex_ private
Definition at line 48 of file ConnectorBT.h.
int ConnectorBT::socketDescr private
The currently used socket descriptor.
Definition at line 50 of file ConnectorBT.h.
Referenced by run().
const char * ConnectorBT::TAG = "BT_CONNECTOR" static private
The tag for writing to the log file.
The tag for writting to log file.
Definition at line 46 of file ConnectorBT.h.
Referenced by callToFuncFromDynLib(), getConnectedAddrStr(), getLocalAddrStr(), getUsedPort(), isPortAvailable(), and send().
The documentation for this class was generated from the following files:
ConnectorBT.h
ConnectorBT.cpp