SounDroid: CommandsDispatcher Class Reference
CommandsDispatcher Class Reference abstract
Contains the commands set.
#include <CommandsDispatcher.h>
Inherited by CommandsDispatcherBT, and CommandsDispatcherWiFi.
Public Member Functions
virtual ~CommandsDispatcher ()
Destructor.
void start ()
Start the dispatcher.
void stop ()
Stop the dispatcher.
bool isStopped ()
Has the dispatcher stopped?
virtual const bool restartNetConnector (const string &portNum)=0
Restart the net connector with the given new port number.
Protected Member Functions
void initCommands ()
Initialize commands instances.
void delCommands ()
Delete commands collection.
const string execCommand (const string &command) const
Execute the command by given string of the command.
virtual void initConnectors (const string &portNum)=0
Initialize connectors instances.
void delConnectors ()
Delete connectors.
virtual void initThreads ()=0
Initialize threads instances.
void delThreads ()
Delete threads.
const list< string > parseCommandStr (const string &str) const
Parse the given command string into command name and parameters if there are ones.
void stopConnectors () const
Stop connectors.
Protected Attributes
map< string, Command * > commands_
The map of commands.
NetConnector * netConnector_
The connector for network.
GuiConnector * guiConnector_
The connector for GUI.
SndConnector * sndConnector_
The connector for system sound control.
bool shouldStop_
Should the dispatcher be stopped.
mutex * mutex_
thread * thNetConnector_
The thread of the network connector.
thread * thGuiConnector_
The thread of the GUI connector.
list< Connector * > connectors_
The list of connectors.
Static Private Attributes
static const char * TAG = "COMMANDS_DISPATCHER"
The for writing to log file.
Detailed Description
Contains the commands set.
Dispatches the commands between connectors
Definition at line 51 of file CommandsDispatcher.h.
Constructor & Destructor Documentation
CommandsDispatcher::~CommandsDispatcher () virtual
Destructor.
Definition at line 91 of file CommandsDispatcher.cpp.
References closeLogFile(), delCommands(), delConnectors(), delThreads(), and mutex_.
Member Function Documentation
void CommandsDispatcher::delCommands () protected
Delete commands collection.
Definition at line 80 of file CommandsDispatcher.cpp.
References commands_.
Referenced by ~CommandsDispatcher().
void CommandsDispatcher::delConnectors () protected
Delete connectors.
Definition at line 122 of file CommandsDispatcher.cpp.
References connectors_.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), and ~CommandsDispatcher().
void CommandsDispatcher::delThreads () protected
Delete threads.
Definition at line 104 of file CommandsDispatcher.cpp.
References thGuiConnector_, and thNetConnector_.
Referenced by ~CommandsDispatcher().
const string CommandsDispatcher::execCommand (const string & command) const protected
Execute the command by given string of the command.
Parameters
command The command's string containing the command's name and parameters
Returns
The execution result string, "ERR" or "OK"
Definition at line 158 of file CommandsDispatcher.cpp.
References commands_, ERR, parseCommandStr(), TAG, and writeToLog().
Referenced by start().
void CommandsDispatcher::initCommands () protected
Initialize commands instances.
Definition at line 62 of file CommandsDispatcher.cpp.
References CHG_VOL, commands_, CONNECTED_IP, GET_VOL, HELLO, IS_MUTED, LOCAL_IP, MUTE, netConnector_, QUIT, sndConnector_, and UNMUTE.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), and CommandsDispatcherWiFi::initCommands().
virtual void CommandsDispatcher::initConnectors (const string & portNum) protected pure virtual
Initialize connectors instances.
Parameters
portNum The port number string
Implemented in CommandsDispatcherWiFi, and CommandsDispatcherBT.
virtual void CommandsDispatcher::initThreads () protected pure virtual
Initialize threads instances.
Implemented in CommandsDispatcherWiFi, and CommandsDispatcherBT.
bool CommandsDispatcher::isStopped ()
Has the dispatcher stopped?
Returns
true - The dispatcher has stopped
Definition at line 204 of file CommandsDispatcher.cpp.
References mutex_, and shouldStop_.
Referenced by start().
const list< string > CommandsDispatcher::parseCommandStr (const string & str) const protected
Parse the given command string into command name and parameters if there are ones.
Parameters
str The string of the command
Returns
The list of the name of the command and its parameters
Definition at line 143 of file CommandsDispatcher.cpp.
Referenced by execCommand().
virtual const bool CommandsDispatcher::restartNetConnector (const string & portNum) pure virtual
Restart the net connector with the given new port number.
Parameters
portNum The port number string (the new port)
Returns
true The connector has restarted successfully
Implemented in CommandsDispatcherWiFi, and CommandsDispatcherBT.
void CommandsDispatcher::start ()
Start the dispatcher.
Definition at line 217 of file CommandsDispatcher.cpp.
References connectors_, execCommand(), isStopped(), stopConnectors(), TAG, and writeToLog().
Referenced by runDispatcher().
void CommandsDispatcher::stop ()
Stop the dispatcher.
Definition at line 193 of file CommandsDispatcher.cpp.
References mutex_, and shouldStop_.
Referenced by CommandQuit::execute(), and runDispatcher().
void CommandsDispatcher::stopConnectors () const protected
Stop connectors.
Definition at line 132 of file CommandsDispatcher.cpp.
References connectors_.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), and start().
Field Documentation
map<string, Command*> CommandsDispatcher::commands_ protected
The map of commands.
Definition at line 57 of file CommandsDispatcher.h.
Referenced by delCommands(), execCommand(), CommandsDispatcherWiFi::initCommands(), and initCommands().
list<Connector*> CommandsDispatcher::connectors_ protected
The list of connectors.
Definition at line 69 of file CommandsDispatcher.h.
Referenced by delConnectors(), start(), and stopConnectors().
GuiConnector* CommandsDispatcher::guiConnector_ protected
The connector for GUI.
Definition at line 60 of file CommandsDispatcher.h.
Referenced by CommandsDispatcherBT::initThreads(), and CommandsDispatcherWiFi::initThreads().
mutex* CommandsDispatcher::mutex_ protected
Definition at line 64 of file CommandsDispatcher.h.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), isStopped(), stop(), and ~CommandsDispatcher().
NetConnector* CommandsDispatcher::netConnector_ protected
The connector for network.
Definition at line 59 of file CommandsDispatcher.h.
Referenced by CommandsDispatcherWiFi::chgNetConnectorPort(), CommandsDispatcherWiFi::initCommands(), initCommands(), CommandsDispatcherBT::initThreads(), CommandsDispatcherWiFi::initThreads(), and CommandsDispatcherWiFi::restartNetConnector().
bool CommandsDispatcher::shouldStop_ protected
Should the dispatcher be stopped.
Definition at line 63 of file CommandsDispatcher.h.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), isStopped(), and stop().
SndConnector* CommandsDispatcher::sndConnector_ protected
The connector for system sound control.
Definition at line 61 of file CommandsDispatcher.h.
Referenced by initCommands().
const char * CommandsDispatcher::TAG = "COMMANDS_DISPATCHER" static private
The for writing to log file.
Definition at line 53 of file CommandsDispatcher.h.
Referenced by execCommand(), and start().
thread* CommandsDispatcher::thGuiConnector_ protected
The thread of the GUI connector.
Definition at line 67 of file CommandsDispatcher.h.
Referenced by delThreads(), CommandsDispatcherBT::initThreads(), and CommandsDispatcherWiFi::initThreads().
thread* CommandsDispatcher::thNetConnector_ protected
The thread of the network connector.
Definition at line 66 of file CommandsDispatcher.h.
Referenced by delThreads(), CommandsDispatcherBT::initThreads(), CommandsDispatcherWiFi::initThreads(), and CommandsDispatcherWiFi::restartNetConnector().
The documentation for this class was generated from the following files:
CommandsDispatcher.h
CommandsDispatcher.cpp