SounDroid: Connector Class Reference
Connector Class Reference abstract
The target of the connector to connect some item(GUI, sound system or network) with the daemon.
#include <Connector.h>
Inherited by GuiConnector, NetConnector, and SndConnector.
Public Member Functions
virtual ~Connector ()
Destructor.
virtual void send (const std::string &dataStr)=0
Send data string to connector.
virtual const std::string receive ()=0
Get a data string arrived to the connector.
virtual void stop ()=0
Stop the connector.
virtual void run ()=0
Run the connector.
Detailed Description
The target of the connector to connect some item(GUI, sound system or network) with the daemon.
The connector can send and receive a string data.
Definition at line 48 of file Connector.h.
Constructor & Destructor Documentation
virtual Connector::~Connector () inline virtual
Destructor.
Definition at line 55 of file Connector.h.
Member Function Documentation
virtual const std::string Connector::receive () pure virtual
Get a data string arrived to the connector.
Returns
The arrived data string
Implemented in ConnectorWiFi, ConnectorBT, GuiConnector, and SndConnector.
virtual void Connector::run () pure virtual
Run the connector.
Implemented in ConnectorWiFi, ConnectorBT, GuiConnector, and SndConnector.
Referenced by CommandsDispatcherBT::initThreads(), CommandsDispatcherWiFi::initThreads(), and CommandsDispatcherWiFi::restartNetConnector().
virtual void Connector::send (const std::string & dataStr) pure virtual
Send data string to connector.
Parameters
dataStr The string of the sent data
Implemented in GuiConnector, and SndConnector.
virtual void Connector::stop () pure virtual
Stop the connector.
Implemented in ConnectorWiFi, ConnectorBT, GuiConnector, and SndConnector.
Referenced by CommandsDispatcherWiFi::restartNetConnector().
The documentation for this class was generated from the following file:
Connector.h