SounDroid: CommandsDispatcherWiFi Class Reference
CommandsDispatcherWiFi Class Reference
The dispatcher of commands sent by wifi.
#include <CommandsDispatcherWiFi.h>
Inherits CommandsDispatcher.
Public Member Functions
CommandsDispatcherWiFi (string &portNum) throw (PortException, GuiException)
Constructor.
const bool restartNetConnector (const string &portNum)
Restart the net connector with the given new port number.
Public Member Functions inherited from CommandsDispatcher
virtual ~CommandsDispatcher ()
Destructor.
void start ()
Start the dispatcher.
void stop ()
Stop the dispatcher.
bool isStopped ()
Has the dispatcher stopped?
Private Member Functions
const bool chgNetConnectorPort (const string &portNum, const string &prevPortNum)
Change the port number of the net connector.
void initThreads () throw (PortException)
Initialize threads instances.
void initConnectors (const string &portNum) throw (PortException, GuiException)
Initialize connectors instances.
void initCommands ()
Initialize commands instances.
CommandsDispatcherWiFi ()
Constructor.
Static Private Attributes
static const char * TAG = "WIFI_COMMANDS_DISPATCHER"
The for writing to log file.
Additional Inherited Members
Protected Member Functions inherited from CommandsDispatcher
void initCommands ()
Initialize commands instances.
void delCommands ()
Delete commands collection.
const string execCommand (const string &command) const
Execute the command by given string of the command.
void delConnectors ()
Delete connectors.
void delThreads ()
Delete threads.
const list< string > parseCommandStr (const string &str) const
Parse the given command string into command name and parameters if there are ones.
void stopConnectors () const
Stop connectors.
Protected Attributes inherited from CommandsDispatcher
map< string, Command * > commands_
The map of commands.
NetConnector * netConnector_
The connector for network.
GuiConnector * guiConnector_
The connector for GUI.
SndConnector * sndConnector_
The connector for system sound control.
bool shouldStop_
Should the dispatcher be stopped.
mutex * mutex_
thread * thNetConnector_
The thread of the network connector.
thread * thGuiConnector_
The thread of the GUI connector.
list< Connector * > connectors_
The list of connectors.
Detailed Description
The dispatcher of commands sent by wifi.
Definition at line 43 of file CommandsDispatcherWiFi.h.
Constructor & Destructor Documentation
CommandsDispatcherWiFi::CommandsDispatcherWiFi () inline private
Constructor.
Definition at line 74 of file CommandsDispatcherWiFi.h.
CommandsDispatcherWiFi::CommandsDispatcherWiFi (string & portNum) throw (PortException, GuiException)
Constructor.
Parameters
portNum The number of port string
Definition at line 46 of file CommandsDispatcherWiFi.cpp.
References LOG_FILE_NAME, mutex, openLogFile(), and portNum.
Member Function Documentation
const bool CommandsDispatcherWiFi::chgNetConnectorPort (const string & portNum, const string & prevPortNum) private
Change the port number of the net connector.
Parameters
portNum The port number string (the new port)
prevPortNum The previous port number (the current port)
Returns
true The port has changed successfully
Definition at line 81 of file CommandsDispatcherWiFi.cpp.
References NetConnector::isPortAvailable(), CommandsDispatcher::netConnector_, and NetConnector::setPortNum().
Referenced by restartNetConnector().
void CommandsDispatcherWiFi::initCommands () private
Initialize commands instances.
Definition at line 156 of file CommandsDispatcherWiFi.cpp.
References CHG_PORT, CommandsDispatcher::commands_, GET_PORT, CommandsDispatcher::initCommands(), and CommandsDispatcher::netConnector_.
void CommandsDispatcherWiFi::initConnectors (const string & portNum) throw (PortException, GuiException) private virtual
Initialize connectors instances.
Parameters
portNum The port number string
Implements CommandsDispatcher.
Definition at line 141 of file CommandsDispatcherWiFi.cpp.
References portNum.
void CommandsDispatcherWiFi::initThreads () throw (PortException) private virtual
Initialize threads instances.
Implements CommandsDispatcher.
Definition at line 127 of file CommandsDispatcherWiFi.cpp.
References NetConnector::getLastErrStr(), CommandsDispatcher::guiConnector_, NetConnector::isPortAvailable(), CommandsDispatcher::netConnector_, GuiConnector::run(), Connector::run(), CommandsDispatcher::thGuiConnector_, and CommandsDispatcher::thNetConnector_.
const bool CommandsDispatcherWiFi::restartNetConnector (const string & portNum) virtual
Restart the net connector with the given new port number.
Parameters
portNum The port number string (the new port)
Returns
true The connector has restarted successfully
Implements CommandsDispatcher.
Definition at line 98 of file CommandsDispatcherWiFi.cpp.
References chgNetConnectorPort(), NetConnector::getUsedPort(), CommandsDispatcher::netConnector_, Connector::run(), Connector::stop(), TAG, CommandsDispatcher::thNetConnector_, and writeToLog().
Field Documentation
const char * CommandsDispatcherWiFi::TAG = "WIFI_COMMANDS_DISPATCHER" static private
The for writing to log file.
The tag for writting to log file.
Definition at line 45 of file CommandsDispatcherWiFi.h.
Referenced by restartNetConnector().
The documentation for this class was generated from the following files:
CommandsDispatcherWiFi.h
CommandsDispatcherWiFi.cpp