SounDroid: CommandsDispatcherBT Class Reference
CommandsDispatcherBT Class Reference
The dispatcher of commands sent by blue tooth.
#include <CommandsDispatcherBT.h>
Inherits CommandsDispatcher.
Public Member Functions
CommandsDispatcherBT () throw (GuiException)
Constructor.
const bool restartNetConnector (const string &portNum)
Restart the net connector with the given new port number.
Public Member Functions inherited from CommandsDispatcher
virtual ~CommandsDispatcher ()
Destructor.
void start ()
Start the dispatcher.
void stop ()
Stop the dispatcher.
bool isStopped ()
Has the dispatcher stopped?
Private Member Functions
void initThreads ()
Initialize threads instances.
void initConnectors (const string &portNum) throw (GuiException)
Initialize connectors instances.
Static Private Attributes
static const char * TAG = "BT_COMMANDS_DISPATCHER"
The tag for writing to the log file.
Additional Inherited Members
Protected Member Functions inherited from CommandsDispatcher
void initCommands ()
Initialize commands instances.
void delCommands ()
Delete commands collection.
const string execCommand (const string &command) const
Execute the command by given string of the command.
void delConnectors ()
Delete connectors.
void delThreads ()
Delete threads.
const list< string > parseCommandStr (const string &str) const
Parse the given command string into command name and parameters if there are ones.
void stopConnectors () const
Stop connectors.
Protected Attributes inherited from CommandsDispatcher
map< string, Command * > commands_
The map of commands.
NetConnector * netConnector_
The connector for network.
GuiConnector * guiConnector_
The connector for GUI.
SndConnector * sndConnector_
The connector for system sound control.
bool shouldStop_
Should the dispatcher be stopped.
mutex * mutex_
thread * thNetConnector_
The thread of the network connector.
thread * thGuiConnector_
The thread of the GUI connector.
list< Connector * > connectors_
The list of connectors.
Detailed Description
The dispatcher of commands sent by blue tooth.
Definition at line 42 of file CommandsDispatcherBT.h.
Constructor & Destructor Documentation
CommandsDispatcherBT::CommandsDispatcherBT () throw (GuiException)
Constructor.
Definition at line 47 of file CommandsDispatcherBT.cpp.
References closeLogFile(), CommandsDispatcher::delConnectors(), CommandsDispatcher::initCommands(), initConnectors(), initThreads(), LOG_FILE_NAME, mutex, CommandsDispatcher::mutex_, openLogFile(), CommandsDispatcher::shouldStop_, and CommandsDispatcher::stopConnectors().
Member Function Documentation
void CommandsDispatcherBT::initConnectors (const string & portNum) throw (GuiException) private virtual
Initialize connectors instances.
Parameters
portNum The port number string
Implements CommandsDispatcher.
Definition at line 83 of file CommandsDispatcherBT.cpp.
Referenced by CommandsDispatcherBT().
void CommandsDispatcherBT::initThreads () private virtual
Initialize threads instances.
Implements CommandsDispatcher.
Definition at line 73 of file CommandsDispatcherBT.cpp.
References CommandsDispatcher::guiConnector_, CommandsDispatcher::netConnector_, GuiConnector::run(), Connector::run(), CommandsDispatcher::thGuiConnector_, and CommandsDispatcher::thNetConnector_.
Referenced by CommandsDispatcherBT().
const bool CommandsDispatcherBT::restartNetConnector (const string & portNum) virtual
Restart the net connector with the given new port number.
Parameters
portNum The port number string (the new port)
Returns
true The connector has restarted successfully
Implements CommandsDispatcher.
Definition at line 100 of file CommandsDispatcherBT.cpp.
References TAG, and writeToLog().
Field Documentation
const char * CommandsDispatcherBT::TAG = "BT_COMMANDS_DISPATCHER" static private
The tag for writing to the log file.
The tag for writting to log file.
Definition at line 44 of file CommandsDispatcherBT.h.
Referenced by restartNetConnector().
The documentation for this class was generated from the following files:
CommandsDispatcherBT.h
CommandsDispatcherBT.cpp