SounDroid: ClosingClient.c File Reference
ClosingClient.c File Reference
The closing client should send the closing message to the server, to stop its running.
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <netdb.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "Log.h"
Macros
#define NO_ERR 0
No errors.
#define ERR -1
There is an error.
#define TAG "CLOSING_CLIENT"
The tag for writing to log file.
#define MAXDATASIZE 100
The max number of bytes we can get at once.
#define MSG "end\n\r"
Functions
const int fillServInfoStructs (const char *port, struct addrinfo **servinfo)
Fill the given structure of server info.
const int initConnection (struct addrinfo *servinfo)
Initialize connection.
void sendEnd (const int sockfd)
Send the end message to the given socket descriptor.
const int runClosingClient (const char *port)
Run the client for closing.
Detailed Description
The closing client should send the closing message to the server, to stop its running.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file ClosingClient.c.
Macro Definition Documentation
#define ERR -1
There is an error.
Definition at line 43 of file ClosingClient.c.
Referenced by initConnection(), runClosingClient(), and sendEnd().
#define MAXDATASIZE 100
The max number of bytes we can get at once.
Definition at line 47 of file ClosingClient.c.
#define MSG "end\n\r"
Referenced by sendEnd().
#define NO_ERR 0
No errors.
Definition at line 42 of file ClosingClient.c.
Referenced by fillServInfoStructs(), and runClosingClient().
#define TAG "CLOSING_CLIENT"
The tag for writing to log file.
Definition at line 45 of file ClosingClient.c.
Referenced by fillServInfoStructs(), initConnection(), runClosingClient(), and sendEnd().
Function Documentation
const int fillServInfoStructs (const char * port, struct addrinfo ** servinfo)
Fill the given structure of server info.
Parameters
port The port number string for listening
servinfo The poiner to the structure of server info
Returns
The status: ERR or NO_ERR
Definition at line 56 of file ClosingClient.c.
References NO_ERR, TAG, and writeToLog2().
Referenced by runClosingClient().
const int initConnection (struct addrinfo * servinfo)
Initialize connection.
Parameters
servinfo The poiner to the structure of server info
Returns
The status: ERR or NO_ERR
Definition at line 77 of file ClosingClient.c.
References ERR, TAG, and writeToLog2().
Referenced by runClosingClient().
const int runClosingClient (const char * port)
Run the client for closing.
Parameters
port The port number string of client
Returns
The status: ERR or NO_ERR
Definition at line 120 of file ClosingClient.c.
References ERR, fillServInfoStructs(), initConnection(), NO_ERR, sendEnd(), TAG, and writeToLog2().
Referenced by ConnectorWiFi::stop().
void sendEnd (const int sockfd)
Send the end message to the given socket descriptor.
Parameters
sockfd The file descriptor of the socket for sending message
Definition at line 102 of file ClosingClient.c.
References ERR, MSG, TAG, and writeToLog2().
Referenced by runClosingClient().