SounDroid: Daemon.cpp File Reference
Daemon.cpp File Reference
The Linux daemon for controlling sound volume The daemon runs the thread with Commands Dispatcher(dispatching commands from between GUI, network and ALSA)
#include <sys/stat.h>
#include <sys/types.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <cstdio>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cstring>
#include "CommandsDispatcher.h"
#include "CommandsDispatcherWiFi.h"
#include "CommandsDispatcherBT.h"
#include "ConnectionTypes.h"
Macros
#define FILE_NAME "pid.txt"
<
#define ERROR -1
an error code
Functions
void sig_handler (int signo)
The handler function of the given signal.
void savePidToFile ()
Kill the other daemon process if it's running.
void closeStandardStreams ()
Close the standard streams stdin, stdout.
void spawn ()
Spawn a new process.
int runDispatcher (CommandsDispatcher *dispatcher)
Run the given commands dispatcher instance.
void printHelp (std::ostream &out, const char *progName, const string &firstLine=string(""))
Print help message to the given stream.
CommandsDispatcherBT * getCommandsDispatcherBT (char *paramsArr[])
Build a command dispatcher using bluetooth for connection to a client.
CommandsDispatcherWiFi * getCommandsDispatcherWiFi (char *paramsArr[])
Build a command dispatcher using WiFi for connection to a client.
void saveConnectionType (const int connType)
Save the connection type to the file.
CommandsDispatcher * getDispatcher (const int paramsNum, char *paramsArr[])
Get commands dispatcher which type depends on the given parameters from the command line.
int main (int argc, char *argv[])
The main function of the daemon.
Variables
bool stop = false
Is the process stopped.
Detailed Description
The Linux daemon for controlling sound volume The daemon runs the thread with Commands Dispatcher(dispatching commands from between GUI, network and ALSA)
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file Daemon.cpp.
Macro Definition Documentation
#define ERROR -1
an error code
Definition at line 59 of file Daemon.cpp.
Referenced by closeStandardStreams(), deleteMsgsQueue(), deleteQueueMsgsFile(), doesQueueMsgsFileExist(), initMsgsQueue(), initQueueClient(), initQueueServer(), receiveMsgClient(), runQueue(), sendMsgClient(), and sendMsgServer().
#define FILE_NAME "pid.txt"
<
The file with the the process ID
Definition at line 54 of file Daemon.cpp.
Referenced by createQueueMsgsFile(), deleteQueueMsgsFile(), doesQueueMsgsFileExist(), initMsgsQueue(), main(), and savePidToFile().
Function Documentation
void closeStandardStreams ()
Close the standard streams stdin, stdout.
Except stderr
Definition at line 119 of file Daemon.cpp.
References ERROR.
Referenced by main().
CommandsDispatcherBT* getCommandsDispatcherBT (char * paramsArr[])
Build a command dispatcher using bluetooth for connection to a client.
Parameters
paramsArr The array of parameters from the command line
Returns
The instance of command dispatcher or NULL
Definition at line 204 of file Daemon.cpp.
References printHelp(), and GuiException::what().
Referenced by getDispatcher().
CommandsDispatcherWiFi* getCommandsDispatcherWiFi (char * paramsArr[])
Build a command dispatcher using WiFi for connection to a client.
Parameters
paramsArr The array of parameters from the command line
Returns
The instance of command dispatcher or NULL
Definition at line 227 of file Daemon.cpp.
References printHelp(), PortException::what(), and GuiException::what().
Referenced by getDispatcher().
CommandsDispatcher* getDispatcher (const int paramsNum, char * paramsArr[])
Get commands dispatcher which type depends on the given parameters from the command line.
Parameters
paramsNum The number of parameters from the command line
paramsArr The parameters from the command line
Returns
The instance of the commands dispatcher
Definition at line 278 of file Daemon.cpp.
References BLUETOOTH, getCommandsDispatcherBT(), getCommandsDispatcherWiFi(), printHelp(), saveConnectionType(), and WIFI.
Referenced by main().
int main (int argc, char * argv[])
The main function of the daemon.
Parameters
argc There is parameter - port number
argv There is parameter - port number
Definition at line 303 of file Daemon.cpp.
References closeStandardStreams(), FILE_NAME, getDispatcher(), runDispatcher(), and spawn().
void printHelp (std::ostream & out, const char * progName, const string & firstLine = string(""))
Print help message to the given stream.
Parameters
out The output stream for printing
progName The name of this program
firstLine The first line of the help message
Definition at line 191 of file Daemon.cpp.
Referenced by getCommandsDispatcherBT(), getCommandsDispatcherWiFi(), and getDispatcher().
int runDispatcher (CommandsDispatcher * dispatcher)
Run the given commands dispatcher instance.
Parameters
dispatcher The instance of the dispatcher
Definition at line 153 of file Daemon.cpp.
References savePidToFile(), sig_handler(), CommandsDispatcher::start(), stop, CommandsDispatcher::stop(), and PortException::what().
Referenced by main().
void saveConnectionType (const int connType)
Save the connection type to the file.
Parameters
connType The connection type number
Definition at line 255 of file Daemon.cpp.
References FILE_NAME_OF_LAST_USED_CONNECTION_TYPE.
Referenced by getDispatcher().
void savePidToFile ()
Kill the other daemon process if it's running.
void killOtherProcess() { ifstream inFile(FILE_NAME, fstream::in);
string pid_str; inFile >> pid_str;
if(!pid_str.empty()) { istringstream str_stream(pid_str); int pid; str_stream >> pid; cout << "Killing the existing process PID=" << pid << endl; if(kill(pid, SIGUSR1) == ERROR) { cerr << "ERROR: Can't send signal to the process with PID=" << pid_str << ". " << strerror(errno) << endl; } }
inFile.close(); } Save the ID of the process to file name FILE_NAME
Definition at line 98 of file Daemon.cpp.
References FILE_NAME, and FILE_NAME_OF_LAST_USED_CONNECTION_TYPE.
Referenced by runDispatcher().
void sig_handler (int signo)
The handler function of the given signal.
Parameters
signo The signal number
Definition at line 65 of file Daemon.cpp.
References stop.
Referenced by runDispatcher().
void spawn ()
Spawn a new process.
Definition at line 131 of file Daemon.cpp.
Referenced by main().
Variable Documentation
bool stop = false
Is the process stopped.
Definition at line 56 of file Daemon.cpp.
Referenced by runDispatcher(), and sig_handler().