SounDroid: gtk_ui.c File Reference
gtk_ui.c File Reference
The main function of the GUI program for the daemon of system's sound control.
#include "Log.h"
#include "init.h"
#include "ConnectionTypes.h"
#include "file_utils.h"
Macros
#define WIN_TITLE "Soundroid"
The title of the program's window.
#define ERR -1
The code of an error.
Functions
const ConnType getLastConnectionType ()
Get from file the last connection type (WIFI/BLUETOOTH) used by daemon.
int main (int argc, char *argv[])
The main function.
Detailed Description
The main function of the GUI program for the daemon of system's sound control.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file gtk_ui.c.
Macro Definition Documentation
#define ERR -1
The code of an error.
Definition at line 36 of file gtk_ui.c.
Referenced by getLastConnectionType().
#define WIN_TITLE "Soundroid"
The title of the program's window.
Definition at line 35 of file gtk_ui.c.
Referenced by main().
Function Documentation
const ConnType getLastConnectionType ()
Get from file the last connection type (WIFI/BLUETOOTH) used by daemon.
Returns
The last connection type
Definition at line 43 of file gtk_ui.c.
References cpStrFromFileToBuff(), ERR, FILE_NAME_OF_LAST_USED_CONNECTION_TYPE, and WIFI.
Referenced by main().
int main (int argc, char * argv[])
The main function.
Definition at line 63 of file gtk_ui.c.
References closeLogFile(), curConnType, getLastConnectionType(), hideWidgetsByConnectionType(), initButtonsFrame(), initClosingWinButt(), initDaemonStateFrame(), initFrameConnected(), initFrameLocal(), initStatusIcon(), initWindow(), mainWin, openLogFile(), and WIN_TITLE.