SounDroid: init.c File Reference
init.c File Reference
Initialization of GUI: main window, its frames and their elements.
#include "init.h"
#include "port_ops.h"
#include "file_utils.h"
#include "str_utils.h"
#include <string.h>
#include <stdlib.h>
Macros
#define ICON_PATH "Sound.png"
The path to the program's icon.
#define STOP_DAEMON_SCRIPT_NAME "stop.sh"
The name of the script for stopping the daemon.
#define DAEMON_PROG_NAME "vol_daemon"
The of the daemon file.
#define PID_FILE_NAME "pid.txt"
The name of the file for saving the process ID of the running daemon.
#define PID_NUM_MAXLEN 20
The maximal length of the running daemon's PID.
#define RED_BOLD_MARKUP "<span weight=\"bold\" color='red'>%s</span>"
The gtk+ text tag for marking up a text to red color and to bold font.
#define BLUE_BOLD_MARKUP "<span weight=\"bold\" color='blue'>%s</span>"
The gtk+ text tag for marking up a text to blue color and to bold font.
#define PORT_NUM_MAX_LEN 10
The maxima length of the port number.
Typedefs
typedef enum visibility_state VisibilityState
States of visibility for some UI components.
Enumerations
enum visibility_state { HIDE, SHOW }
Functions
void setDaemonStateLbl (GtkLabel *lbl)
Set the label of the daemon's state.
char * getRunningDaemonPID ()
Get the PID of a running daemon.
void showDialog (const gchar *lblTxt, const GtkMessageType msgType, const gchar *title)
Show dialog with the given title, label text and the message type(error, warning, etc.)
static void stopDaemon (GtkWidget *window, gpointer data)
Stop the daemon.
const gint showStopDaemonDialog ()
Show the dialog window of stopping daemon.
const bool stopPrevDaemonIfRuns ()
Stop the previous daemon before the new one start.
const bool isDaemonRunning ()
Is daemon running?
gchar * getIpStrForLbl (char *ipStr, char *noIpStr, char *lblName)
Get the text string of IP for a text label.
GtkWidget * setLocalIpLbl ()
Set the text label for the local IP.
void startBtDaemon ()
Start the blue tooth daemon The dialog with a result of starting will be shown.
void startWifiDaemon ()
Start the wifi daemon The dialog with a result of starting will be shown.
void startDaemon (GtkWidget *window, gpointer data)
Start daemon.
GtkWidget * initButton (GtkWidget *container, char *txt, void(*func)(GtkWidget *window, gpointer data), gpointer data)
Initialize a button with the given text, for the given container and with the given pointer to function.
GtkWidget * initRadioButt (GtkWidget *container, char *txt, GtkWidget *firstRadio, void(*func)(GtkWidget *window, gpointer data), gpointer data)
Initialize a radio button with the given text, for the given container, with the given pointer to function and the given first radio button.
GtkWidget * initEditTxt (GtkWidget *container, char *labelTxt, const gchar *txt, const int disapperingWidgetsArrInd)
Initialize the edit text widget with option to be disappering.
void chgPort (GtkWidget *window, gpointer data)
Change port function.
void setLblTxtAndColor (GtkLabel *lbl, const char *markup_str, const char *txt)
Set the text of the given text label and its color.
GtkWidget * initDaemonStateFrame ()
Initialize the frame of daemon's state.
void chgDisappearedWidgetsState (const VisibilityState state)
Change the visibility state of the widget with visibility property.
void setConnectionTypeWifi (GtkWidget *butt, gpointer data)
Set connection type WiFi.
void setConnectionTypeBlueTooth (GtkWidget *butt, gpointer data)
Set connection type Blue Tooth.
void initRadioButtsByConnType (GtkWidget *container)
Initialize the radio button of connection type the current connection type.
GtkWidget * initFrameLocal ()
Initialize the frame with the info of local parameters: local IP, used connection type.
GtkWidget * setConnectedIpLbl ()
Set the label for connected IP.
GtkWidget * initFrameConnected ()
Initialisation of the frame 'Connected'.
void initStatusIcon ()
Init the status icon of the program.
void close_window (GtkWidget *widget, gpointer window)
Close the window with the given pointer.
void initClosingWinButt (GtkWidget *frame, gchar *lblTxt, gpointer window)
Iinitialise the button for closing the given window.
GtkWidget * initButtonsFrame ()
Iinitialise the frame of buttons.
gint close_application (GtkWidget *widget, GdkEvent *event, gpointer data)
Close this application function.
GtkWidget * initWindow (gchar *title)
Initialise a window with the given title.
void hideWidgetsByConnectionType ()
Hide widgets by the current connection type.
Variables
char prevPortNumStr [PORT_NUM_MAX_LEN] = {'\0'}
The array of the previous port number string.
GtkWidget * portEditTxt = NULL
The edit text widget of the port number.
GtkWidget * mainWin = NULL
The main window of the program.
GtkWidget * daemonStateLbl = NULL
The text label of daemon's state: Running or Stopped.
GtkWidget * localIpLbl = NULL
The text label of the local IP.
GtkWidget * connectedIpLbl = NULL
The text label of the connected client IP.
ConnType curConnType = WIFI
Current connection type: Wifi or Bluetooth.
GtkWidget * disapperingWidgetsArr [] = { NULL, NULL }
The widgets able to be visible/invisible.
Detailed Description
Initialization of GUI: main window, its frames and their elements.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file init.c.
Macro Definition Documentation
#define BLUE_BOLD_MARKUP "<span weight=\"bold\" color='blue'>%s</span>"
The gtk+ text tag for marking up a text to blue color and to bold font.
Definition at line 47 of file init.c.
Referenced by setDaemonStateLbl().
#define DAEMON_PROG_NAME "vol_daemon"
The of the daemon file.
Definition at line 40 of file init.c.
Referenced by startBtDaemon(), and startWifiDaemon().
#define ICON_PATH "Sound.png"
The path to the program's icon.
Definition at line 37 of file init.c.
Referenced by initStatusIcon().
#define PID_FILE_NAME "pid.txt"
The name of the file for saving the process ID of the running daemon.
Definition at line 42 of file init.c.
Referenced by getRunningDaemonPID().
#define PID_NUM_MAXLEN 20
The maximal length of the running daemon's PID.
Definition at line 44 of file init.c.
Referenced by getRunningDaemonPID().
#define PORT_NUM_MAX_LEN 10
The maxima length of the port number.
Definition at line 49 of file init.c.
Referenced by chgPort().
#define RED_BOLD_MARKUP "<span weight=\"bold\" color='red'>%s</span>"
The gtk+ text tag for marking up a text to red color and to bold font.
Definition at line 46 of file init.c.
Referenced by setDaemonStateLbl().
#define STOP_DAEMON_SCRIPT_NAME "stop.sh"
The name of the script for stopping the daemon.
Definition at line 39 of file init.c.
Referenced by stopDaemon(), and stopPrevDaemonIfRuns().
Typedef Documentation
typedef enum visibility_state VisibilityState
States of visibility for some UI components.
Enumeration Type Documentation
enum visibility_state
Enumerator
HIDE
SHOW
Definition at line 66 of file init.c.
Function Documentation
void chgDisappearedWidgetsState (const VisibilityState state)
Change the visibility state of the widget with visibility property.
Parameters
state The state of visibility: HIDE or SHOW
Definition at line 469 of file init.c.
References disapperingWidgetsArr, HIDE, and SHOW.
Referenced by hideWidgetsByConnectionType(), setConnectionTypeBlueTooth(), and setConnectionTypeWifi().
void chgPort (GtkWidget * window, gpointer data)
Change port function.
Parameters
window (not used)
data (not used)
Definition at line 367 of file init.c.
References chgPortOfDaemon(), getRunningDaemonPID(), PORT_NUM_MAX_LEN, portEditTxt, prevPortNumStr, and showDialog().
Referenced by initButtonsFrame().
gint close_application (GtkWidget * widget, GdkEvent * event, gpointer data)
Close this application function.
The function of gtk+
Parameters
widget (not used)
event (not used)
data (not used)
Definition at line 652 of file init.c.
Referenced by initWindow().
void close_window (GtkWidget * widget, gpointer window)
Close the window with the given pointer.
Parameters
widget (not used)
window The being closed window pointer
Definition at line 610 of file init.c.
Referenced by initClosingWinButt().
gchar* getIpStrForLbl (char * ipStr, char * noIpStr, char * lblName)
Get the text string of IP for a text label.
Parameters
ipStr The string of the IP
noIpStr The string for the not found IP
lblName The name of the text label
Returns
The text string of IP
Definition at line 196 of file init.c.
Referenced by setConnectedIpLbl(), and setLocalIpLbl().
char* getRunningDaemonPID ()
Get the PID of a running daemon.
The PID is in the file within /proc
Returns
string of the PID or an empty string if there is no running daemon
Definition at line 77 of file init.c.
References cpStrFromFileToBuff(), delFileByPath(), doesDirHasFile(), PID_FILE_NAME, and PID_NUM_MAXLEN.
Referenced by chgPort(), isDaemonRunning(), setDaemonStateLbl(), stopDaemon(), and stopPrevDaemonIfRuns().
void hideWidgetsByConnectionType ()
Hide widgets by the current connection type.
Hide or show widgets dependengly on the current connection type.
Definition at line 679 of file init.c.
References BLUETOOTH, chgDisappearedWidgetsState(), curConnType, HIDE, SHOW, and WIFI.
Referenced by main().
GtkWidget* initButton (GtkWidget * container, char * txt, void(*)(GtkWidget *window, gpointer data) func, gpointer data)
Initialize a button with the given text, for the given container and with the given pointer to function.
Parameters
container The widget for containing the button
txt The text of the button
func The button's function
data The additional data's pointer
Definition at line 306 of file init.c.
Referenced by initButtonsFrame().
GtkWidget* initButtonsFrame ()
Iinitialise the frame of buttons.
Returns
The initialised frame with buttons
Definition at line 636 of file init.c.
References chgPort(), disapperingWidgetsArr, initButton(), startDaemon(), and stopDaemon().
Referenced by main().
void initClosingWinButt (GtkWidget * frame, gchar * lblTxt, gpointer window)
Iinitialise the button for closing the given window.
Add the button to the given frame
Parameters
frame The frame for adding the button to
lblTxt The text of the button's label
window The window should be closed by the buttons
Definition at line 623 of file init.c.
References close_window().
Referenced by main().
GtkWidget* initDaemonStateFrame ()
Initialize the frame of daemon's state.
Returns
The frame's widget
Definition at line 450 of file init.c.
References daemonStateLbl, and setDaemonStateLbl().
Referenced by main().
GtkWidget* initEditTxt (GtkWidget * container, char * labelTxt, const gchar * txt, const int disapperingWidgetsArrInd)
Initialize the edit text widget with option to be disappering.
Parameters
container The container for containing the edit text widget
labelTxt The text for the label of the edit text widget
txt The text for the edit text widget
disapperingWidgetsArrInd The index in the array of pointers to disapperaing widgets
Returns
The initialized edit text widget
Definition at line 345 of file init.c.
References disapperingWidgetsArr.
Referenced by initFrameConnected().
GtkWidget* initFrameConnected ()
Initialisation of the frame 'Connected'.
Returns
The initialised frame
Definition at line 579 of file init.c.
References connectedIpLbl, getPortOfDaemon(), initEditTxt(), portEditTxt, prevPortNumStr, and setConnectedIpLbl().
Referenced by main().
GtkWidget* initFrameLocal ()
Initialize the frame with the info of local parameters: local IP, used connection type.
Returns
The built frame widget
Definition at line 543 of file init.c.
References initRadioButtsByConnType(), localIpLbl, and setLocalIpLbl().
Referenced by main().
GtkWidget* initRadioButt (GtkWidget * container, char * txt, GtkWidget * firstRadio, void(*)(GtkWidget *window, gpointer data) func, gpointer data)
Initialize a radio button with the given text, for the given container, with the given pointer to function and the given first radio button.
Parameters
firstRadio If itsn't NULL the the new radion button will be connected to the existing radio button's group
container The widget for containing the button
txt The text of the button
func The button's function
data The additional data's pointer
Definition at line 325 of file init.c.
Referenced by initRadioButtsByConnType().
void initRadioButtsByConnType (GtkWidget * container)
Initialize the radio button of connection type the current connection type.
Parameters
container The container with the radio buttons
Definition at line 521 of file init.c.
References BLUETOOTH, curConnType, initRadioButt(), setConnectionTypeBlueTooth(), setConnectionTypeWifi(), and WIFI.
Referenced by initFrameLocal().
void initStatusIcon ()
Init the status icon of the program.
Definition at line 598 of file init.c.
References ICON_PATH.
Referenced by main().
GtkWidget* initWindow (gchar * title)
Initialise a window with the given title.
Parameters
title The title string
Returns
The initialised window widget
Definition at line 663 of file init.c.
References close_application().
Referenced by main().
const bool isDaemonRunning ()
Is daemon running?
Returns
true The daemon is running
Definition at line 178 of file init.c.
References getRunningDaemonPID().
Referenced by startBtDaemon(), and startWifiDaemon().
GtkWidget* setConnectedIpLbl ()
Set the label for connected IP.
Returns
The label of the connected IP
Definition at line 562 of file init.c.
References connectedIpLbl, getConnectedIP(), and getIpStrForLbl().
Referenced by initFrameConnected().
void setConnectionTypeBlueTooth (GtkWidget * butt, gpointer data)
Set connection type Blue Tooth.
Parameters
butt The button of the connection type
data The adding data's pointer
Definition at line 511 of file init.c.
References BLUETOOTH, chgDisappearedWidgetsState(), curConnType, and HIDE.
Referenced by initRadioButtsByConnType().
void setConnectionTypeWifi (GtkWidget * butt, gpointer data)
Set connection type WiFi.
Parameters
butt The button of the connection type
data (not used)
Definition at line 500 of file init.c.
References chgDisappearedWidgetsState(), curConnType, SHOW, and WIFI.
Referenced by initRadioButtsByConnType().
void setDaemonStateLbl (GtkLabel * lbl)
Set the label of the daemon's state.
Parameters
lbl The label widget
Definition at line 428 of file init.c.
References BLUE_BOLD_MARKUP, getRunningDaemonPID(), RED_BOLD_MARKUP, and setLblTxtAndColor().
Referenced by initDaemonStateFrame(), startBtDaemon(), startWifiDaemon(), and stopDaemon().
void setLblTxtAndColor (GtkLabel * lbl, const char * markup_str, const char * txt)
Set the text of the given text label and its color.
Parameters
lbl The text label widget
markup_str The string for marking up the text
txt The text for the label
Definition at line 408 of file init.c.
References isStrEmptyOrNULL().
Referenced by setDaemonStateLbl().
GtkWidget* setLocalIpLbl ()
Set the text label for the local IP.
Returns
The text label widget
Definition at line 213 of file init.c.
References getIpStrForLbl(), getLocalIP(), and localIpLbl.
Referenced by initFrameLocal(), startBtDaemon(), and startWifiDaemon().
void showDialog (const gchar * lblTxt, const GtkMessageType msgType, const gchar * title)
Show dialog with the given title, label text and the message type(error, warning, etc.)
Parameters
lblTxt The text of the label
msgType The type of the message of the dialog
title The title of the dialog window
Definition at line 99 of file init.c.
References mainWin.
Referenced by chgPort(), startBtDaemon(), startDaemon(), startWifiDaemon(), and stopDaemon().
const gint showStopDaemonDialog ()
Show the dialog window of stopping daemon.
Returns
The code of the clicked button at dialog
Definition at line 138 of file init.c.
References mainWin.
Referenced by stopPrevDaemonIfRuns().
void startBtDaemon ()
Start the blue tooth daemon The dialog with a result of starting will be shown.
Definition at line 230 of file init.c.
References DAEMON_PROG_NAME, daemonStateLbl, isDaemonRunning(), localIpLbl, runFileInCurDir(), setDaemonStateLbl(), setLocalIpLbl(), and showDialog().
Referenced by startDaemon().
void startDaemon (GtkWidget * window, gpointer data)
Start daemon.
Parameters
window (not used)
data (not used)
Definition at line 283 of file init.c.
References BLUETOOTH, curConnType, showDialog(), startBtDaemon(), startWifiDaemon(), stopPrevDaemonIfRuns(), and WIFI.
Referenced by initButtonsFrame().
void startWifiDaemon ()
Start the wifi daemon The dialog with a result of starting will be shown.
Definition at line 252 of file init.c.
References DAEMON_PROG_NAME, daemonStateLbl, isDaemonRunning(), localIpLbl, portEditTxt, runFileInCurDir(), setDaemonStateLbl(), setLocalIpLbl(), and showDialog().
Referenced by startDaemon().
static void stopDaemon (GtkWidget * window, gpointer data) static
Stop the daemon.
Parameters
window (not used)
data (not used)
Definition at line 118 of file init.c.
References daemonStateLbl, getRunningDaemonPID(), runFileInCurDir(), setDaemonStateLbl(), showDialog(), and STOP_DAEMON_SCRIPT_NAME.
Referenced by initButtonsFrame(), and stopPrevDaemonIfRuns().
const bool stopPrevDaemonIfRuns ()
Stop the previous daemon before the new one start.
Returns
true The previous daemon has stopped successfully
Definition at line 156 of file init.c.
References doesDirHasFile(), getRunningDaemonPID(), runFileInCurDir(), showStopDaemonDialog(), STOP_DAEMON_SCRIPT_NAME, and stopDaemon().
Referenced by startDaemon().
Variable Documentation
GtkWidget* connectedIpLbl = NULL
The text label of the connected client IP.
Definition at line 59 of file init.c.
Referenced by initFrameConnected(), and setConnectedIpLbl().
ConnType curConnType = WIFI
Current connection type: Wifi or Bluetooth.
The currently used connection type.
Definition at line 61 of file init.c.
Referenced by hideWidgetsByConnectionType(), initRadioButtsByConnType(), main(), setConnectionTypeBlueTooth(), setConnectionTypeWifi(), and startDaemon().
GtkWidget* daemonStateLbl = NULL
The text label of daemon's state: Running or Stopped.
Definition at line 56 of file init.c.
Referenced by initDaemonStateFrame(), startBtDaemon(), startWifiDaemon(), and stopDaemon().
GtkWidget* disapperingWidgetsArr[] = { NULL, NULL }
The widgets able to be visible/invisible.
Definition at line 67 of file init.c.
Referenced by chgDisappearedWidgetsState(), initButtonsFrame(), and initEditTxt().
GtkWidget* localIpLbl = NULL
The text label of the local IP.
Definition at line 58 of file init.c.
Referenced by initFrameLocal(), setLocalIpLbl(), startBtDaemon(), and startWifiDaemon().
GtkWidget* mainWin = NULL
The main window of the program.
It initialized from the main function
Definition at line 54 of file init.c.
Referenced by main(), showDialog(), and showStopDaemonDialog().
GtkWidget* portEditTxt = NULL
The edit text widget of the port number.
Definition at line 52 of file init.c.
Referenced by chgPort(), initFrameConnected(), and startWifiDaemon().
char prevPortNumStr[PORT_NUM_MAX_LEN] = {'\0'}
The array of the previous port number string.
Definition at line 50 of file init.c.
Referenced by chgPort(), and initFrameConnected().