SounDroid: init.h File Reference
init.h File Reference
Initialization of GUI: main window, its frames and their elements.
#include <gtk/gtk.h>
Typedefs
typedef enum connection_type ConnType
Enumerations
enum connection_type { WIFI, BLUETOOTH }
Connection types.
Functions
GtkWidget * initFrameLocal ()
Initialize the frame with the info of local parameters: local IP, used connection type.
GtkWidget * initFrameConnected ()
Initialisation of the frame 'Connected'.
GtkWidget * initButtonsFrame ()
Iinitialise the frame of buttons.
GtkWidget * initDaemonStateFrame ()
Initialize the frame of daemon's state.
void initClosingWinButt (GtkWidget *frame, gchar *lblTxt, gpointer window)
Iinitialise the button for closing the given window.
GtkWidget * initWindow (gchar *title)
Initialise a window with the given title.
void initStatusIcon ()
Init the status icon of the program.
void hideWidgetsByConnectionType ()
Hide or show widgets dependengly on the current connection type.
Variables
GtkWidget * mainWin
The main window of the program.
ConnType curConnType
The currently used connection type.
Detailed Description
Initialization of GUI: main window, its frames and their elements.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file init.h.
Typedef Documentation
typedef enum connection_type ConnType
Enumeration Type Documentation
enum connection_type
Connection types.
Enumerator
WIFI
BLUETOOTH
Definition at line 39 of file init.h.
Function Documentation
void hideWidgetsByConnectionType ()
Hide or show widgets dependengly on the current connection type.
Hide or show widgets dependengly on the current connection type.
Definition at line 679 of file init.c.
References BLUETOOTH, chgDisappearedWidgetsState(), curConnType, HIDE, SHOW, and WIFI.
Referenced by main().
GtkWidget* initButtonsFrame ()
Iinitialise the frame of buttons.
Returns
The initialised frame with buttons
Definition at line 636 of file init.c.
References chgPort(), disapperingWidgetsArr, initButton(), startDaemon(), and stopDaemon().
Referenced by main().
void initClosingWinButt (GtkWidget * frame, gchar * lblTxt, gpointer window)
Iinitialise the button for closing the given window.
Add the button to the given frame
Parameters
frame The frame for adding the button to
lblTxt The text of the button's label
window The window should be closed by the buttons
Definition at line 623 of file init.c.
References close_window().
Referenced by main().
GtkWidget* initDaemonStateFrame ()
Initialize the frame of daemon's state.
Returns
The frame's widget
Definition at line 450 of file init.c.
References daemonStateLbl, and setDaemonStateLbl().
Referenced by main().
GtkWidget* initFrameConnected ()
Initialisation of the frame 'Connected'.
Returns
The initialised frame
Definition at line 579 of file init.c.
References connectedIpLbl, getPortOfDaemon(), initEditTxt(), portEditTxt, prevPortNumStr, and setConnectedIpLbl().
Referenced by main().
GtkWidget* initFrameLocal ()
Initialize the frame with the info of local parameters: local IP, used connection type.
Returns
The built frame widget
Definition at line 543 of file init.c.
References initRadioButtsByConnType(), localIpLbl, and setLocalIpLbl().
Referenced by main().
void initStatusIcon ()
Init the status icon of the program.
Definition at line 598 of file init.c.
References ICON_PATH.
Referenced by main().
GtkWidget* initWindow (gchar * title)
Initialise a window with the given title.
Parameters
title The title string
Returns
The initialised window widget
Definition at line 663 of file init.c.
References close_application().
Referenced by main().
Variable Documentation
ConnType curConnType
The currently used connection type.
The currently used connection type.
Definition at line 61 of file init.c.
Referenced by hideWidgetsByConnectionType(), initRadioButtsByConnType(), main(), setConnectionTypeBlueTooth(), setConnectionTypeWifi(), and startDaemon().
GtkWidget* mainWin
The main window of the program.
It initialized from the main function
Definition at line 54 of file init.c.
Referenced by main(), showDialog(), and showStopDaemonDialog().