SounDroid: IpOps.c File Reference
IpOps.c File Reference
Operations on a local IP or a connected IP.
#include "IpOps.h"
#include "Log.h"
#include "SocketsLib.h"
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <errno.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
Macros
#define ETH "eth"
#define WLAN "wlan"
#define TAG "IP_OPS"
tag for writing to the log file
#define UNKNOWN "UNKNOWN"
Functions
void copyLocalIp2Str (char *str)
Copy the local IP to the given string.
void copyConnectedIp2Str (const int sockDescr, char *str)
Copy the IP of the connected client to the given string.
Detailed Description
Operations on a local IP or a connected IP.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file IpOps.c.
Macro Definition Documentation
#define ETH "eth"
Definition at line 45 of file IpOps.c.
Referenced by copyLocalIp2Str().
#define TAG "IP_OPS"
tag for writing to the log file
Definition at line 48 of file IpOps.c.
Referenced by copyConnectedIp2Str(), and copyLocalIp2Str().
#define UNKNOWN "UNKNOWN"
Definition at line 50 of file IpOps.c.
Referenced by copyConnectedIp2Str(), and copyLocalIp2Str().
#define WLAN "wlan"
Definition at line 46 of file IpOps.c.
Referenced by copyLocalIp2Str().
Function Documentation
void copyConnectedIp2Str (const int sockDescr, char * str)
Copy the IP of the connected client to the given string.
Parameters
sockDescr Socket descriptor
str String for copying IP to
Definition at line 102 of file IpOps.c.
References ERR, TAG, UNKNOWN, and writeToLog2().
Referenced by runConnection().
void copyLocalIp2Str (char * str)
Copy the local IP to the given string.
Parameters
str String for copying IP to
Definition at line 56 of file IpOps.c.
References ERR, ETH, NO_ERR, TAG, UNKNOWN, WLAN, and writeToLog2().
Referenced by initConnectionBeforeListen().