SounDroid: Log.c File Reference
Log.c File Reference
Write to log file.
#include "Log.h"
#include <errno.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <pthread.h>
Macros
#define ERR -1
the code of an error
#define LOG_FILE_NAME_LEN 100
#define ERRSTR "ERROR: "
#define STR "(): "
Functions
void chgLogFileName (const char *name)
Change the name of the currently opened log file.
void openLogFile (const char *name)
Open the log file with the given name.
void closeLogFile ()
Close the log file if it has been opened before.
const char * getCurDate ()
Get current date string pointer.
char * addDateToTxt (const char *txt, const char *tag)
Add the current date and the given tag to the given text.
void writeToLog (const char *txt, const char *tag)
Write the given text and tag to log file.
void writeToLog2 (const char *txt1, const char *txt2, const char *tag)
Write to log file the given two textes and tag.
void clearLogFile ()
Clear the log file.
void writeToLogIfError (const int result, const char *funcName, const char *errorStr, const char *TAG)
Write error string to the log file.
long getLogSizeBytes ()
Get the size of the log file in bytes.
Variables
FILE * logFile = NULL
Pointer to the log file.
char fileName [LOG_FILE_NAME_LEN] = {'\0'}
The log file's name string array.
pthread_mutex_t mutex
The mutex for concurrent writing to the same log file by different threads.
long curSize = 0
The current size of the log.
Detailed Description
Write to log file.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file Log.c.
Macro Definition Documentation
#define ERR -1
the code of an error
Definition at line 38 of file Log.c.
Referenced by writeToLogIfError().
#define ERRSTR "ERROR: "
Referenced by writeToLogIfError().
#define LOG_FILE_NAME_LEN 100
Definition at line 42 of file Log.c.
Referenced by chgLogFileName().
#define STR "(): "
Referenced by writeToLogIfError().
Function Documentation
char* addDateToTxt (const char * txt, const char * tag)
Add the current date and the given tag to the given text.
Parameters
txt The text
tag The tag
Returns
The new text containing the old text and the added tag and the date
Definition at line 134 of file Log.c.
References getCurDate().
Referenced by writeToLog().
void chgLogFileName (const char * name)
Change the name of the currently opened log file.
Parameters
name The new name
Definition at line 53 of file Log.c.
References fileName, and LOG_FILE_NAME_LEN.
Referenced by openLogFile().
void clearLogFile ()
Clear the log file.
Definition at line 238 of file Log.c.
References closeLogFile(), fileName, logFile, and openLogFile().
Referenced by writeToLog().
void closeLogFile ()
Close the log file if it has been opened before.
Close the log file.
Definition at line 100 of file Log.c.
References fileName, logFile, and mutex.
Referenced by clearLogFile(), CommandsDispatcherBT::CommandsDispatcherBT(), main(), writeToLog(), and CommandsDispatcher::~CommandsDispatcher().
const char* getCurDate ()
Get current date string pointer.
Get current date string.
Returns
The pointer to the string of current date
Definition at line 122 of file Log.c.
Referenced by addDateToTxt().
long getLogSizeBytes ()
Get the size of the log file in bytes.
Get log file's size in bytes.
Returns
The size of the log file in bytes
Definition at line 287 of file Log.c.
References curSize.
void openLogFile (const char * name)
Open the log file with the given name.
The give name will be saved in the global value fileName
Parameters
name The name of the log file
Definition at line 68 of file Log.c.
References chgLogFileName(), curSize, fileName, logFile, and mutex.
Referenced by clearLogFile(), CommandsDispatcherBT::CommandsDispatcherBT(), CommandsDispatcherWiFi::CommandsDispatcherWiFi(), main(), and writeToLog().
void writeToLog (const char * txt, const char * tag)
Write the given text and tag to log file.
Write the given text to the log file with the given tag.
Parameters
txt The text for writing
tag The tag
Definition at line 157 of file Log.c.
References addDateToTxt(), clearLogFile(), closeLogFile(), curSize, fileName, LOG_FILE_NAME, logFile, MAX_LOG_FILE_LEN, mutex, and openLogFile().
Referenced by acceptBtConn(), bindBtSocket(), bindSocket(), ConnectorBT::callToFuncFromDynLib(), closeBtSocketConn(), closeSocketConn(), conversation(), conversationBt(), createBtSocket(), createSocket(), SndConnector::doChgVol(), SndConnector::doGetVol(), SndConnector::doIsMuted(), SndConnector::doMute(), SndConnector::doUnmute(), CommandsDispatcher::execCommand(), CommandChgVol::execute(), CommandChangePort::execute(), fillHostInfoStructs(), ConnectorBT::getConnectedAddrStr(), ConnectorWiFi::getConnectedAddrStr(), ConnectorBT::getLocalAddrStr(), ConnectorWiFi::getLocalAddrStr(), ConnectorBT::getUsedPort(), ConnectorBT::isPortAvailable(), isStrNum(), listenBtConns(), listenConns(), ConnectorWiFi::processPortNumErr(), receiveBtData(), receiveData(), CommandsDispatcherBT::restartNetConnector(), CommandsDispatcherWiFi::restartNetConnector(), ConnectorBT::send(), ConnectorWiFi::send(), sendBtData(), sendData(), sendMsgClient(), sendMsgServer(), setPort(), CommandsDispatcher::start(), writeToLog2(), and writeToLogIfError().
void writeToLog2 (const char * txt1, const char * txt2, const char * tag)
Write to log file the given two textes and tag.
The given textes will be concatenated and added to the log file with the given tag.
Parameters
txt1 The first text for writing
txt2 The second text for writing
tag The tag
Definition at line 212 of file Log.c.
References fileName, and writeToLog().
Referenced by acceptBtConn(), bindSocket(), ConnectorBT::callToFuncFromDynLib(), closeSocketConn(), conversation(), conversationBt(), copyConnectedIp2Str(), copyLocalIp2Str(), createBtSocket(), createQueueMsgsFile(), deleteMsgsQueue(), deleteQueueMsgsFile(), doSoundVolAction(), fillHostInfoStructs(), fillServInfoStructs(), finishSoundControl(), getFileSizeBytes(), getLocalAddr(), getProcessParams(), initConnection(), initLocalAdapterName(), initMsgsQueue(), initSoundControl(), isStrNum(), receiveBtData(), receiveData(), receiveMsgClient(), runClosingClient(), runQueue(), sendBtData(), sendData(), sendEnd(), sendMsgClient(), and sendMsgServer().
void writeToLogIfError (const int result, const char * funcName, const char * errorStr, const char * TAG)
Write error string to the log file.
Parameters
result The result index, if result is error then the given error string should be written to the log file
funcName The name of the function where the error has taken place
errorStr The error string should be written to the log file
TAG The tag string for logs
Definition at line 265 of file Log.c.
References ERR, ERRSTR, STR, and writeToLog().
Referenced by acceptBtConn(), acceptConn(), bindBtSocket(), bindSocket(), closeBtSocketConn(), createBtSocket(), createSocket(), listenBtConns(), and listenConns().
Variable Documentation
long curSize = 0
The current size of the log.
Definition at line 47 of file Log.c.
Referenced by getLogSizeBytes(), openLogFile(), and writeToLog().
char fileName[LOG_FILE_NAME_LEN] = {'\0'}
The log file's name string array.
Definition at line 43 of file Log.c.
Referenced by chgLogFileName(), clearLogFile(), closeLogFile(), openLogFile(), writeToLog(), and writeToLog2().
FILE* logFile = NULL
Pointer to the log file.
Definition at line 40 of file Log.c.
Referenced by clearLogFile(), closeLogFile(), openLogFile(), and writeToLog().
pthread_mutex_t mutex
The mutex for concurrent writing to the same log file by different threads.
Definition at line 45 of file Log.c.
Referenced by closeLogFile(), CommandsDispatcherBT::CommandsDispatcherBT(), CommandsDispatcherWiFi::CommandsDispatcherWiFi(), openLogFile(), and writeToLog().