SounDroid: Log.h File Reference
Log.h File Reference
Writing to log fileThe MIT License (MIT)
#include <stdio.h>
Macros
#define MAX_LOG_FILE_LEN 10000
The maximal number of lines within the log file.
#define LOG_FILE_NAME "log.txt"
the name of the file for writing logs info
Functions
void openLogFile (const char *name)
Open the log file with the given name.
void closeLogFile ()
Close the log file.
void writeToLog (const char *txt, const char *tag)
Write the given text to the log file with the given tag.
void writeToLog2 (const char *txt1, const char *txt2, const char *tag)
The given textes will be concatenated and added to the log file with the given tag.
void clearLogFile ()
Clear the log file.
void writeToLogIfError (const int result, const char *funcName, const char *errorStr, const char *TAG)
Write error string to the log file.
long getLogSizeBytes ()
Get log file's size in bytes.
char * addDateToTxt (const char *txt, const char *tag)
Add the current date and the given tag to the given text.
const char * getCurDate ()
Get current date string.
Detailed Description
Writing to log file
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file Log.h.
Macro Definition Documentation
#define LOG_FILE_NAME "log.txt"
the name of the file for writing logs info
Definition at line 39 of file Log.h.
Referenced by CommandsDispatcherBT::CommandsDispatcherBT(), CommandsDispatcherWiFi::CommandsDispatcherWiFi(), and writeToLog().
#define MAX_LOG_FILE_LEN 10000
The maximal number of lines within the log file.
When the file has the maximal length it will be cleared
Definition at line 37 of file Log.h.
Referenced by writeToLog().
Function Documentation
char* addDateToTxt (const char * txt, const char * tag)
Add the current date and the given tag to the given text.
Parameters
txt The text
tag The tag for logs
Returns
The new text containing the old text and the added tag and the date
Parameters
txt The text
tag The tag
Returns
The new text containing the old text and the added tag and the date
Definition at line 134 of file Log.c.
References getCurDate().
Referenced by writeToLog().
void clearLogFile ()
Clear the log file.
Definition at line 238 of file Log.c.
References closeLogFile(), fileName, logFile, and openLogFile().
Referenced by writeToLog().
void closeLogFile ()
Close the log file.
Close the log file.
Definition at line 100 of file Log.c.
References fileName, logFile, and mutex.
Referenced by clearLogFile(), CommandsDispatcherBT::CommandsDispatcherBT(), main(), writeToLog(), and CommandsDispatcher::~CommandsDispatcher().
const char* getCurDate ()
Get current date string.
Returns
The string of the current date
Get current date string.
Returns
The pointer to the string of current date
Definition at line 122 of file Log.c.
Referenced by addDateToTxt().
long getLogSizeBytes ()
Get log file's size in bytes.
Get log file's size in bytes.
Returns
The size of the log file in bytes
Definition at line 287 of file Log.c.
References curSize.
void openLogFile (const char * name)
Open the log file with the given name.
Parameters
name The name of the file
The give name will be saved in the global value fileName
Parameters
name The name of the log file
Definition at line 68 of file Log.c.
References chgLogFileName(), curSize, fileName, logFile, and mutex.
Referenced by clearLogFile(), CommandsDispatcherBT::CommandsDispatcherBT(), CommandsDispatcherWiFi::CommandsDispatcherWiFi(), main(), and writeToLog().
void writeToLog (const char * txt, const char * tag)
Write the given text to the log file with the given tag.
Parameters
txt The text for adding to the log
tag The tag of the text
Write the given text to the log file with the given tag.
Parameters
txt The text for writing
tag The tag
Definition at line 157 of file Log.c.
References addDateToTxt(), clearLogFile(), closeLogFile(), curSize, fileName, LOG_FILE_NAME, logFile, MAX_LOG_FILE_LEN, mutex, and openLogFile().
Referenced by acceptBtConn(), bindBtSocket(), bindSocket(), ConnectorBT::callToFuncFromDynLib(), closeBtSocketConn(), closeSocketConn(), conversation(), conversationBt(), createBtSocket(), createSocket(), SndConnector::doChgVol(), SndConnector::doGetVol(), SndConnector::doIsMuted(), SndConnector::doMute(), SndConnector::doUnmute(), CommandsDispatcher::execCommand(), CommandChgVol::execute(), CommandChangePort::execute(), fillHostInfoStructs(), ConnectorBT::getConnectedAddrStr(), ConnectorWiFi::getConnectedAddrStr(), ConnectorBT::getLocalAddrStr(), ConnectorWiFi::getLocalAddrStr(), ConnectorBT::getUsedPort(), ConnectorBT::isPortAvailable(), isStrNum(), listenBtConns(), listenConns(), ConnectorWiFi::processPortNumErr(), receiveBtData(), receiveData(), CommandsDispatcherBT::restartNetConnector(), CommandsDispatcherWiFi::restartNetConnector(), ConnectorBT::send(), ConnectorWiFi::send(), sendBtData(), sendData(), sendMsgClient(), sendMsgServer(), setPort(), CommandsDispatcher::start(), writeToLog2(), and writeToLogIfError().
void writeToLog2 (const char * txt1, const char * txt2, const char * tag)
The given textes will be concatenated and added to the log file with the given tag.
Parameters
txt1 The 1st text for adding to the log
txt2 The 2nd text for adding to the log
tag The tag of the text
The given textes will be concatenated and added to the log file with the given tag.
Parameters
txt1 The first text for writing
txt2 The second text for writing
tag The tag
Definition at line 212 of file Log.c.
References fileName, and writeToLog().
Referenced by acceptBtConn(), bindSocket(), ConnectorBT::callToFuncFromDynLib(), closeSocketConn(), conversation(), conversationBt(), copyConnectedIp2Str(), copyLocalIp2Str(), createBtSocket(), createQueueMsgsFile(), deleteMsgsQueue(), deleteQueueMsgsFile(), doSoundVolAction(), fillHostInfoStructs(), fillServInfoStructs(), finishSoundControl(), getFileSizeBytes(), getLocalAddr(), getProcessParams(), initConnection(), initLocalAdapterName(), initMsgsQueue(), initSoundControl(), isStrNum(), receiveBtData(), receiveData(), receiveMsgClient(), runClosingClient(), runQueue(), sendBtData(), sendData(), sendEnd(), sendMsgClient(), and sendMsgServer().
void writeToLogIfError (const int result, const char * funcName, const char * errorStr, const char * TAG)
Write error string to the log file.
Parameters
result The result index, if result is error then the given error string should be written to the log file
funcName The name of the function where the error has taken place
errorStr The error string should be written to the log file
TAG The tag for logs
result The result index, if result is error then the given error string should be written to the log file
funcName The name of the function where the error has taken place
errorStr The error string should be written to the log file
TAG The tag string for logs
Definition at line 265 of file Log.c.
References ERR, ERRSTR, STR, and writeToLog().
Referenced by acceptBtConn(), acceptConn(), bindBtSocket(), bindSocket(), closeBtSocketConn(), createBtSocket(), createSocket(), listenBtConns(), and listenConns().