SounDroid: MsgsQueueServer.c File Reference
MsgsQueueServer.c File Reference
Messages queue for IPC in Linux, the server side.
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <strings.h>
#include <string.h>
#include <unistd.h>
#include <Log.h>
#include "MsgsQueue.h"
#include <pthread.h>
Macros
#define TAG "MSGS_QUEUE_SERVER"
the tag for writing to log file
#define HAS_NEW_MSG 4
there is a new message in queue
#define NO_NEW_MSG 5
there are no new messages in queue
#define RECEIVING 1
receiving a message
#define SENDING 2
sending a message
#define STOP 3
stopping the queue
Functions
void setRunningStatus (const int status)
Set the running status.
bool sendMsgServer (const char *msgTxt)
Send message from the server's side.
char * receiveMsgServer ()
Receive a message on the server's side.
bool initQueueServer ()
Initialize the messages queue on the server's side.
const int getRunningStatus ()
Get the running status of the server's side messages queue.
void runQueue ()
Run the messages queue.
void deleteMsgsQueue ()
Stop the messages queue and delete it.
void deleteQueueMsgsFile ()
Delete the file of the messages queue.
void deleteQueue ()
Delete messages queue and its file.
Variables
int receivingMsgStatus = NO_NEW_MSG
the server's receiving status
struct message msg
/struct msg The structure of a message
int runingStatus = RECEIVING
the running status of the messages server
pthread_mutex_t statusMutex
the mutex of the server's status
struct MsgsQueueData serverQueueData
Detailed Description
Messages queue for IPC in Linux, the server side.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file MsgsQueueServer.c.
Macro Definition Documentation
#define HAS_NEW_MSG 4
there is a new message in queue
Definition at line 49 of file MsgsQueueServer.c.
Referenced by receiveMsgServer(), and runQueue().
#define NO_NEW_MSG 5
there are no new messages in queue
Definition at line 50 of file MsgsQueueServer.c.
Referenced by receiveMsgServer().
#define RECEIVING 1
receiving a message
Definition at line 62 of file MsgsQueueServer.c.
Referenced by runQueue(), and sendMsgServer().
#define SENDING 2
sending a message
Definition at line 63 of file MsgsQueueServer.c.
Referenced by runQueue(), and sendMsgServer().
#define STOP 3
stopping the queue
Definition at line 64 of file MsgsQueueServer.c.
Referenced by acceptBtConn(), conversation(), conversationBt(), deleteMsgsQueue(), getRunStatus(), receiveBtData(), ConnectorBT::run(), ConnectorWiFi::run(), runBtConnection(), runConnection(), runQueue(), sendMsgServer(), ConnectorBT::stop(), and ConnectorWiFi::stop().
#define TAG "MSGS_QUEUE_SERVER"
the tag for writing to log file
Definition at line 47 of file MsgsQueueServer.c.
Referenced by deleteMsgsQueue(), deleteQueueMsgsFile(), runQueue(), and sendMsgServer().
Function Documentation
void deleteMsgsQueue ()
Stop the messages queue and delete it.
Definition at line 201 of file MsgsQueueServer.c.
References ERROR, MsgsQueueData::queueID, serverQueueData, setRunningStatus(), STOP, TAG, and writeToLog2().
Referenced by deleteQueue().
void deleteQueue ()
Delete messages queue and its file.
Definition at line 225 of file MsgsQueueServer.c.
References deleteMsgsQueue(), and deleteQueueMsgsFile().
Referenced by GuiConnector::stop().
void deleteQueueMsgsFile ()
Delete the file of the messages queue.
Definition at line 214 of file MsgsQueueServer.c.
References ERROR, FILE_NAME, TAG, and writeToLog2().
Referenced by deleteQueue().
const int getRunningStatus ()
Get the running status of the server's side messages queue.
Returns
The status code: RECEIVING, SENDING or STOP
Definition at line 156 of file MsgsQueueServer.c.
References runingStatus, and statusMutex.
Referenced by runQueue().
bool initQueueServer ()
Initialize the messages queue on the server's side.
Returns
true Initialized successfully
Definition at line 141 of file MsgsQueueServer.c.
References createQueueMsgsFile(), ERROR, initMsgsQueue(), msg, MSG_STR_MAX_LEN, message::mtxt, MsgsQueueData::queueID, MsgsQueueData::receivedMsgTxt, and serverQueueData.
Referenced by GuiConnector::GuiConnector().
char* receiveMsgServer ()
Receive a message on the server's side.
Returns
The text of the received message
Definition at line 124 of file MsgsQueueServer.c.
References HAS_NEW_MSG, NO_NEW_MSG, MsgsQueueData::receivedMsgTxt, receivingMsgStatus, serverQueueData, and statusMutex.
Referenced by GuiConnector::receive().
void runQueue ()
Run the messages queue.
Definition at line 170 of file MsgsQueueServer.c.
References ERROR, getRunningStatus(), HAS_NEW_MSG, msg, MSG_STR_MAX_LEN, message::mtxt, MsgsQueueData::queueID, MsgsQueueData::receivedMsgTxt, RECEIVING, receivingMsgStatus, SENDING, serverQueueData, statusMutex, STOP, TAG, and writeToLog2().
Referenced by GuiConnector::run().
bool sendMsgServer (const char * msgTxt)
Send message from the server's side.
Parameters
msgTxt The text of the message
Returns
true The message has sent successfully
Definition at line 89 of file MsgsQueueServer.c.
References ERROR, MSG_STR_MAX_LEN, message::mtxt, message::mtype, MsgsQueueData::queueID, RECEIVING, SENDING, serverQueueData, setRunningStatus(), STOP, TAG, writeToLog(), and writeToLog2().
Referenced by GuiConnector::send().
void setRunningStatus (const int status)
Set the running status.
Parameters
status The status code: RECEIVING, SENDING or STOP
Definition at line 77 of file MsgsQueueServer.c.
References runingStatus, and statusMutex.
Referenced by deleteMsgsQueue(), and sendMsgServer().
Variable Documentation
struct message msg
/struct msg The structure of a message
Definition at line 60 of file MsgsQueueServer.c.
Referenced by initQueueServer(), and runQueue().
int receivingMsgStatus = NO_NEW_MSG
the server's receiving status
Definition at line 52 of file MsgsQueueServer.c.
Referenced by receiveMsgServer(), and runQueue().
int runingStatus = RECEIVING
the running status of the messages server
Definition at line 66 of file MsgsQueueServer.c.
Referenced by getRunningStatus(), and setRunningStatus().
struct MsgsQueueData serverQueueData
Definition at line 70 of file MsgsQueueServer.c.
Referenced by deleteMsgsQueue(), initQueueServer(), receiveMsgServer(), runQueue(), and sendMsgServer().
pthread_mutex_t statusMutex
the mutex of the server's status
Definition at line 68 of file MsgsQueueServer.c.
Referenced by getRunningStatus(), receiveMsgServer(), runQueue(), and setRunningStatus().