SounDroid: MsgsQueueClient.h File Reference
MsgsQueueClient.h File Reference
The client side of the messages queue.
#include "MsgsQueue.h"
Functions
bool initQueueClient ()
Initialize the messages queue of the client side.
bool sendMsgClient (const char *msgTxt)
Send message with the given text from the clien side to the server one.
char * receiveMsgClient ()
Receive the message on the client side from the server one.
Detailed Description
The client side of the messages queue.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file MsgsQueueClient.h.
Function Documentation
bool initQueueClient ()
Initialize the messages queue of the client side.
Returns
true The queue has initialized successfully
Definition at line 49 of file MsgsQueueClient.c.
References clientQueueData, doesQueueMsgsFileExist(), ERROR, initMsgsQueue(), MSG_STR_MAX_LEN, MsgsQueueData::queueID, and MsgsQueueData::receivedMsgTxt.
Referenced by chgPortOfDaemon(), and sendStrInQueueMsg().
char* receiveMsgClient ()
Receive the message on the client side from the server one.
Returns
The text of the message
Definition at line 96 of file MsgsQueueClient.c.
References clientQueueData, ERROR, MSG_STR_MAX_LEN, message::mtxt, MsgsQueueData::queueID, MsgsQueueData::receivedMsgTxt, TAG, and writeToLog2().
Referenced by chgPortOfDaemon(), and sendStrInQueueMsg().
bool sendMsgClient (const char * msgTxt)
Send message with the given text from the clien side to the server one.
Parameters
msgTxt The text of the message
Returns
true The message has sent successfully
Definition at line 66 of file MsgsQueueClient.c.
References clientQueueData, ERROR, MSG_STR_MAX_LEN, message::mtxt, message::mtype, MsgsQueueData::queueID, TAG, writeToLog(), and writeToLog2().
Referenced by chgPortOfDaemon(), and sendStrInQueueMsg().