SounDroid: MsgsQueueServer.h File Reference
MsgsQueueServer.h File Reference
Messages queue for IPC in Linux, the server side.
#include "MsgsQueue.h"
Functions
bool initQueueServer ()
Initialize the messages queue on the server's side.
void runQueue ()
Run the messages queue.
bool sendMsgServer (const char *msgTxt)
Send message from the server's side.
char * receiveMsgServer ()
Receive a message on the server's side.
void deleteQueue ()
Delete messages queue and its file.
Detailed Description
Messages queue for IPC in Linux, the server side.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file MsgsQueueServer.h.
Function Documentation
void deleteQueue ()
Delete messages queue and its file.
Definition at line 225 of file MsgsQueueServer.c.
References deleteMsgsQueue(), and deleteQueueMsgsFile().
Referenced by GuiConnector::stop().
bool initQueueServer ()
Initialize the messages queue on the server's side.
Returns
true Initialized successfully
Definition at line 141 of file MsgsQueueServer.c.
References createQueueMsgsFile(), ERROR, initMsgsQueue(), msg, MSG_STR_MAX_LEN, message::mtxt, MsgsQueueData::queueID, MsgsQueueData::receivedMsgTxt, and serverQueueData.
Referenced by GuiConnector::GuiConnector().
char* receiveMsgServer ()
Receive a message on the server's side.
Returns
The text of the received message
Definition at line 124 of file MsgsQueueServer.c.
References HAS_NEW_MSG, NO_NEW_MSG, MsgsQueueData::receivedMsgTxt, receivingMsgStatus, serverQueueData, and statusMutex.
Referenced by GuiConnector::receive().
void runQueue ()
Run the messages queue.
Definition at line 170 of file MsgsQueueServer.c.
References ERROR, getRunningStatus(), HAS_NEW_MSG, msg, MSG_STR_MAX_LEN, message::mtxt, MsgsQueueData::queueID, MsgsQueueData::receivedMsgTxt, RECEIVING, receivingMsgStatus, SENDING, serverQueueData, statusMutex, STOP, TAG, and writeToLog2().
Referenced by GuiConnector::run().
bool sendMsgServer (const char * msgTxt)
Send message from the server's side.
Parameters
msgTxt The text of the message
Returns
true The message has sent successfully
Definition at line 89 of file MsgsQueueServer.c.
References ERROR, MSG_STR_MAX_LEN, message::mtxt, message::mtype, MsgsQueueData::queueID, RECEIVING, SENDING, serverQueueData, setRunningStatus(), STOP, TAG, writeToLog(), and writeToLog2().
Referenced by GuiConnector::send().