SounDroid: MsgsQueue.c File Reference
MsgsQueue.c File Reference
Linux Messages Queue for interprocess communication.
#include "MsgsQueue.h"
#include "Log.h"
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <unistd.h>
Macros
#define TAG "MSGS_QUEUE"
The tag for writing to log file.
Functions
bool createQueueMsgsFile ()
Create the file of messages queue.
bool doesQueueMsgsFileExist ()
Does the file of messages queue exist?
const int initMsgsQueue (const int permissionFlag)
Initialize the the queue of messages.
Detailed Description
Linux Messages Queue for interprocess communication.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file MsgsQueue.c.
Macro Definition Documentation
#define TAG "MSGS_QUEUE"
The tag for writing to log file.
Definition at line 40 of file MsgsQueue.c.
Referenced by createQueueMsgsFile(), and initMsgsQueue().
Function Documentation
bool createQueueMsgsFile ()
Create the file of messages queue.
Returns
true The file has created successfully
Definition at line 47 of file MsgsQueue.c.
References FILE_NAME, TAG, and writeToLog2().
Referenced by initQueueServer().
bool doesQueueMsgsFileExist ()
Does the file of messages queue exist?
Returns
true The file does exist
Definition at line 68 of file MsgsQueue.c.
References ERROR, and FILE_NAME.
Referenced by initQueueClient().
const int initMsgsQueue (const int permissionFlag)
Initialize the the queue of messages.
Parameters
permissionFlag The flag of the queue permission
Returns
The messages queue ID
Definition at line 78 of file MsgsQueue.c.
References ERROR, FILE_NAME, TAG, and writeToLog2().
Referenced by initQueueClient(), and initQueueServer().