SounDroid: port_ops.c File Reference
port_ops.c File Reference
Port operations from GUI.
#include "CommandsNames.h"
#include "MsgsQueueClient.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
Functions
char * sendStrInQueueMsg (const char *str)
Send the given string in messages to the server side of the messages queue which is run in the daemon.
char * getPortOfDaemon ()
Get currently used port of daemon.
char * buildCommandStr (const char *commandName, const char *param)
Build the string of a command with parameters for sending through the messages queue.
bool chgPortOfDaemon (const char *newPortNum)
Change the port of the daemon to the given port number.
char * getLocalIP ()
Get local IP by sending message with command to the server side of the messages queue opened by the running volume control daemon and getting a message with IP from one.
char * getConnectedIP ()
Get the IP of a connected client by sending message with command to the server side of the messages queue opened by the running volume control daemon and getting a message with IP from one.
Detailed Description
Port operations from GUI.
All the port operations from GUI realised by by sending messages with commands to the system sound control daemon (sending messages is based on the inter process communication messages queue)
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file port_ops.c.
Function Documentation
char* buildCommandStr (const char * commandName, const char * param)
Build the string of a command with parameters for sending through the messages queue.
Parameters
commandName The name of the command
param The string of parameters
Returns
The built string
Definition at line 81 of file port_ops.c.
Referenced by chgPortOfDaemon().
bool chgPortOfDaemon (const char * newPortNum)
Change the port of the daemon to the given port number.
Parameters
newPortNum The new port number
Returns
true - The change of the port has been successful
Definition at line 95 of file port_ops.c.
References buildCommandStr(), CHG_PORT, initQueueClient(), receiveMsgClient(), and sendMsgClient().
Referenced by chgPort().
char* getConnectedIP ()
Get the IP of a connected client by sending message with command to the server side of the messages queue opened by the running volume control daemon and getting a message with IP from one.
Returns
The connected IP string
Definition at line 136 of file port_ops.c.
References CONNECTED_IP, and sendStrInQueueMsg().
Referenced by setConnectedIpLbl().
char* getLocalIP ()
Get local IP by sending message with command to the server side of the messages queue opened by the running volume control daemon and getting a message with IP from one.
Returns
The local IP string
Definition at line 123 of file port_ops.c.
References LOCAL_IP, and sendStrInQueueMsg().
Referenced by setLocalIpLbl().
char* getPortOfDaemon ()
Get currently used port of daemon.
Returns
The string of the used port number
Definition at line 69 of file port_ops.c.
References ERR, GET_PORT, and sendStrInQueueMsg().
Referenced by initFrameConnected().
char* sendStrInQueueMsg (const char * str)
Send the given string in messages to the server side of the messages queue which is run in the daemon.
Parameters
str The string for sending
Returns
The response string from the server side of messages queue. If there is an error, the "" will be returned
Definition at line 46 of file port_ops.c.
References initQueueClient(), receiveMsgClient(), and sendMsgClient().
Referenced by getConnectedIP(), getLocalIP(), and getPortOfDaemon().