SounDroid: service.c File Reference
service.c File Reference
The SDP service of blue tooth connection.
#include "service.h"
#include <string.h>
#include <errno.h>
Functions
sdp_record_t * setGeneralServiceID ()
Set the ID for general SDP service.
void setServiceRecordBrowsable (sdp_record_t *record)
Set the given SDP record browsalbe.
void setL2CapInfo (sdp_list_t *proto_list)
Set L2cap info.
void setRfcommInfo (sdp_list_t *proto_list)
Set RFCOMM info.
void addProtoInfoToRecord (sdp_record_t *record, sdp_list_t *proto_list)
Add the sdp protocol info to the SDP record.
sdp_session_t * register_service ()
Register SDP service.
Detailed Description
The SDP service of blue tooth connection.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file service.c.
Function Documentation
void addProtoInfoToRecord (sdp_record_t * record, sdp_list_t * proto_list)
Add the sdp protocol info to the SDP record.
Parameters
record The SDP record
proto_list The SDP protocol list
Definition at line 103 of file service.c.
Referenced by register_service().
sdp_session_t* register_service ()
Register SDP service.
Register service.
Returns
SDP session pointer
Definition at line 115 of file service.c.
References addProtoInfoToRecord(), setGeneralServiceID(), setL2CapInfo(), setRfcommInfo(), and setServiceRecordBrowsable().
sdp_record_t* setGeneralServiceID ()
Set the ID for general SDP service.
Returns
The SDP record instance
Definition at line 37 of file service.c.
Referenced by register_service().
void setL2CapInfo (sdp_list_t * proto_list)
Set L2cap info.
Parameters
proto_list The SDP list
Definition at line 69 of file service.c.
Referenced by register_service().
void setRfcommInfo (sdp_list_t * proto_list)
Set RFCOMM info.
Parameters
proto_list The SDP list
Definition at line 83 of file service.c.
References RFCCOMM_CHANEL_NUM.
Referenced by register_service().
void setServiceRecordBrowsable (sdp_record_t * record)
Set the given SDP record browsalbe.
Parameters
record The SDP record
Definition at line 56 of file service.c.
Referenced by register_service().