SounDroid: SocketsLib.h File Reference
SocketsLib.h File Reference
The library for connecting by sockets.
Macros
#define SOCKET_TIME_OUT 60
Sockets connection time out in seconds.
#define ERR -1
an error's code
#define NO_ERR 0
no errors code
Functions
const int initConnectionBeforeListen ()
Initial connection before listening.
void runConnection (const int sockDescr)
Run client-server connection.
const int setPort (const char *port)
Set port number.
const char * getErrStr ()
Get the string of the last error.
Detailed Description
The library for connecting by sockets.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file SocketsLib.h.
Macro Definition Documentation
#define ERR -1
an error's code
Definition at line 34 of file SocketsLib.h.
#define NO_ERR 0
no errors code
Definition at line 35 of file SocketsLib.h.
#define SOCKET_TIME_OUT 60
Sockets connection time out in seconds.
Definition at line 32 of file SocketsLib.h.
Function Documentation
const char* getErrStr ()
Get the string of the last error.
Returns
The string of the last error
Definition at line 95 of file SocketsLib.c.
Referenced by ConnectorWiFi::getLastErrStr().
const int initConnectionBeforeListen ()
Initial connection before listening.
Returns
socket descriptor or ERR
Definition at line 408 of file SocketsLib.c.
References bindSocket(), closeSocketConn(), copyLocalIp2Str(), createSocket(), ERR, fillHostInfoStructs(), IP_ADDR_STR_LEN, localIP, master, and read_fds.
Referenced by ConnectorWiFi::isPortAvailable().
void runConnection (const int sockDescr)
Run client-server connection.
Parameters
sockDescr The socket descriptor
sockDescr An initialized socket descriptor
Definition at line 504 of file SocketsLib.c.
References acceptConn(), closeSocketConn(), connectedIP, conversation(), copyConnectedIp2Str(), DATA_LEN, destroyMutexes(), ERR, fdmax, getRunStatus(), initMutexes(), IP_ADDR_STR_LEN, listenConns(), master, MILLISECONDS_SLEEP_TIME, read_fds, and STOP.
Referenced by ConnectorWiFi::run().
const int setPort (const char * port)
Set port number.
Parameters
port The port number string
Returns
ERR or NO_ERR
Definition at line 123 of file SocketsLib.c.
References ERR, NO_ERR, PORT_NUM_LEN, portNum, TAG, and writeToLog().
Referenced by ConnectorWiFi::setPortNum().