SounDroid: SocketsLib.c File Reference
SocketsLib.c File Reference
The library for connecting by sockets.
#include "SocketsLib.h"
#include "synchronise.h"
#include "Log.h"
#include "addr.h"
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <ctype.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netdb.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <sys/ioctl.h>
#include "IpOps.h"
Macros
#define MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT 5
The maximal number of sockets waiting for accept.
#define STR_END "end"
#define TAG "SOCKETS_LIB"
The tag for writing to the log file.
#define IP_ADDR_STR_LEN 20
The length of the IP string.
#define PORT_NUM_LEN 10
The length of the port number string.
Functions
const char * getErrStr ()
Get the string of the last error.
const char * getLocalAddr ()
Get local IP.
const char * getConnectedAddr ()
Get connected IP.
const int setPort (const char *port)
Set port number.
char * getPort ()
Get the currently used port.
bool isStrNum (const char *str)
Check wether the given string is number.
const int fillHostInfoStructs (struct addrinfo *host_info, struct addrinfo **host_info_list)
Fill the structures of a host info.
const int createSocket (struct addrinfo *host_info_list)
Create socket from the given list of the host info structs.
const int bindSocket (const int sockDescr, struct addrinfo *host_info_list)
Bind the socket with the given descriptor.
const int listenConns (const int sockDescr)
Listen to new connections.
const int acceptConn (const int sockDescr)
Accept a connection.
const char * receiveData (const int newSockDescr, char *incoming_data_buffer, const size_t buff_len)
Receive a data from a client.
const int sendData (const int socketDescr)
Send data by sockets.
const int closeSocketConn (const int sockDescr)
Close the socket connection.
const int initConnectionBeforeListen ()
Initial connection before listening.
const int conversation (char *incoming_data_buffer, const size_t buff_len, const int listenSocketDescr, const int curSocketDescr)
Client-server conversation.
void runConnection (const int sockDescr)
Run client-server connection.
Variables
char connectedIP [IP_ADDR_STR_LEN] = {'\0'}
The buffer for a connected IP addres string.
char localIP [IP_ADDR_STR_LEN] = {'\0'}
The buffer for the local IP addres string.
char portNum [PORT_NUM_LEN] = {'\0'}
The buffer for the port number string.
fd_set master
fd_set read_fds
int fdmax
Detailed Description
The library for connecting by sockets.
Definition in file SocketsLib.c.
Macro Definition Documentation
#define IP_ADDR_STR_LEN 20
The length of the IP string.
Definition at line 64 of file SocketsLib.c.
Referenced by initConnectionBeforeListen(), and runConnection().
#define MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT 5
The maximal number of sockets waiting for accept.
Definition at line 58 of file SocketsLib.c.
Referenced by listenConns().
#define PORT_NUM_LEN 10
The length of the port number string.
Definition at line 68 of file SocketsLib.c.
Referenced by setPort().
#define STR_END "end"
Definition at line 60 of file SocketsLib.c.
Referenced by conversation(), and receiveData().
#define TAG "SOCKETS_LIB"
The tag for writing to the log file.
Definition at line 62 of file SocketsLib.c.
Referenced by acceptConn(), bindSocket(), closeSocketConn(), conversation(), createSocket(), fillHostInfoStructs(), isStrNum(), listenConns(), receiveData(), sendData(), and setPort().
Function Documentation
const int acceptConn (const int sockDescr)
Accept a connection.
Parameters
sockDescr A socket's descriptor
Returns
ERR if there is an error. Any other number if there is no error
Definition at line 298 of file SocketsLib.c.
References TAG, and writeToLogIfError().
Referenced by runConnection().
const int bindSocket (const int sockDescr, struct addrinfo * host_info_list)
Bind the socket with the given descriptor.
Parameters
host_info_list The list of the host info structs
sockDescr The socket descriptor
Returns
The status of binding
Definition at line 243 of file SocketsLib.c.
References ERR, TAG, writeToLog(), writeToLog2(), and writeToLogIfError().
Referenced by initConnectionBeforeListen().
const int closeSocketConn (const int sockDescr)
Close the socket connection.
Parameters
sockDescr The socket descriptor of the connection
Returns
The result integer of closing
Definition at line 388 of file SocketsLib.c.
References ERR, master, TAG, writeToLog(), and writeToLog2().
Referenced by initConnectionBeforeListen(), and runConnection().
const int conversation (char * incoming_data_buffer, const size_t buff_len, const int listenSocketDescr, const int curSocketDescr)
Client-server conversation.
Parameters
incoming_data_buffer The string buffer for the incoming from the client data
buff_len The length of the buffer
listenSocketDescr The descriptor of the listening socket
curSocketDescr Currently used socket descriptor
Returns
The integer status of the conversation: ERR, NO_ERR or STOP if received the connection end message
Definition at line 449 of file SocketsLib.c.
References ERR, fdmax, getSentData(), HAS_NEW_DATA, master, receiveData(), sendData(), setReceivedData(), setReceivedDataStatus(), STOP, STR_END, TAG, writeToLog(), and writeToLog2().
Referenced by runConnection().
const int createSocket (struct addrinfo * host_info_list)
Create socket from the given list of the host info structs.
Parameters
host_info_list The list of the host info structs
Returns
The socket descriptor
Definition at line 226 of file SocketsLib.c.
References TAG, writeToLog(), and writeToLogIfError().
Referenced by initConnectionBeforeListen().
const int fillHostInfoStructs (struct addrinfo * host_info, struct addrinfo ** host_info_list)
Fill the structures of a host info.
Parameters
host_info The host info structure, which should be filled up
host_info_list The list of the host info structs
Returns
The result: ERR or NO_ERR
Definition at line 202 of file SocketsLib.c.
References ERR, isStrNum(), NO_ERR, portNum, TAG, writeToLog(), and writeToLog2().
Referenced by initConnectionBeforeListen().
const char* getConnectedAddr ()
Get connected IP.
Get connected address string.
Returns
The string of the connected IP or ""
Definition at line 113 of file SocketsLib.c.
References connectedIP.
Referenced by ConnectorWiFi::getConnectedAddrStr().
const char* getErrStr ()
Get the string of the last error.
Returns
The string of the last error
Definition at line 95 of file SocketsLib.c.
Referenced by ConnectorWiFi::getLastErrStr().
const char* getLocalAddr ()
Get local IP.
Get local address string.
Returns
The string of the local IP or ""
Definition at line 104 of file SocketsLib.c.
References localIP.
Referenced by ConnectorWiFi::getLocalAddrStr().
char* getPort ()
Get the currently used port.
Returns
the string of the currently used port number
Definition at line 161 of file SocketsLib.c.
References portNum.
const int initConnectionBeforeListen ()
Initial connection before listening.
Returns
socket descriptor or ERR
Definition at line 408 of file SocketsLib.c.
References bindSocket(), closeSocketConn(), copyLocalIp2Str(), createSocket(), ERR, fillHostInfoStructs(), IP_ADDR_STR_LEN, localIP, master, and read_fds.
Referenced by ConnectorWiFi::isPortAvailable().
bool isStrNum (const char * str)
Check wether the given string is number.
Parameters
str The string for checking
Returns
true The string is number
Definition at line 171 of file SocketsLib.c.
References TAG, writeToLog(), and writeToLog2().
Referenced by fillHostInfoStructs().
const int listenConns (const int sockDescr)
Listen to new connections.
Parameters
sockDescr A socket's descriptor
Returns
ERR if there is an error. Any other number if there is no error
Definition at line 277 of file SocketsLib.c.
References fdmax, master, MAX_SOCKETS_NUM_WAITED_FOR_ACCEPT, TAG, writeToLog(), and writeToLogIfError().
Referenced by runConnection().
const char* receiveData (const int newSockDescr, char * incoming_data_buffer, const size_t buff_len)
Receive a data from a client.
Parameters
newSockDescr A socket's descriptor
incoming_data_buffer The buffer for incoming data
buff_len The length of the buffer
Returns
The buffer of the incoming data or NULL if there is an error
Definition at line 317 of file SocketsLib.c.
References ERR, STR_END, TAG, writeToLog(), and writeToLog2().
Referenced by conversation().
void runConnection (const int sockDescr)
Run client-server connection.
Parameters
sockDescr An initialized socket descriptor
Definition at line 504 of file SocketsLib.c.
References acceptConn(), closeSocketConn(), connectedIP, conversation(), copyConnectedIp2Str(), DATA_LEN, destroyMutexes(), ERR, fdmax, getRunStatus(), initMutexes(), IP_ADDR_STR_LEN, listenConns(), master, MILLISECONDS_SLEEP_TIME, read_fds, and STOP.
Referenced by ConnectorWiFi::run().
const int sendData (const int socketDescr)
Send data by sockets.
Parameters
socketDescr The socket descriptor
Returns
ERR or NO_ERR
Definition at line 358 of file SocketsLib.c.
References ERR, getSentData(), NO_ERR, sentData, TAG, writeToLog(), and writeToLog2().
Referenced by conversation().
const int setPort (const char * port)
Set port number.
Parameters
port The port number string
Returns
ERR or NO_ERR
Definition at line 123 of file SocketsLib.c.
References ERR, NO_ERR, PORT_NUM_LEN, portNum, TAG, and writeToLog().
Referenced by ConnectorWiFi::setPortNum().
Variable Documentation
char connectedIP[IP_ADDR_STR_LEN] = {'\0'}
The buffer for a connected IP addres string.
Definition at line 65 of file SocketsLib.c.
Referenced by getConnectedAddr(), and runConnection().
int fdmax
Definition at line 74 of file SocketsLib.c.
Referenced by conversation(), listenConns(), and runConnection().
char localIP[IP_ADDR_STR_LEN] = {'\0'}
The buffer for the local IP addres string.
Definition at line 66 of file SocketsLib.c.
Referenced by getLocalAddr(), and initConnectionBeforeListen().
fd_set master
Definition at line 72 of file SocketsLib.c.
Referenced by closeSocketConn(), conversation(), initConnectionBeforeListen(), listenConns(), and runConnection().
char portNum[PORT_NUM_LEN] = {'\0'}
The buffer for the port number string.
Definition at line 69 of file SocketsLib.c.
Referenced by CommandsDispatcherWiFi::CommandsDispatcherWiFi(), ConnectorWiFi::ConnectorWiFi(), fillHostInfoStructs(), getPort(), CommandsDispatcherWiFi::initConnectors(), setPort(), and ConnectorWiFi::setPortNum().
fd_set read_fds
Definition at line 73 of file SocketsLib.c.
Referenced by initConnectionBeforeListen(), and runConnection().