SounDroid: SoundLib.c File Reference
SoundLib.c File Reference
The library for control of the sound system volume.
#include "SoundLib.h"
#include <alsa/asoundlib.h>
#include <stdlib.h>
#include "Log.h"
Macros
#define TAG "SOUND_LIB"
The tag for log file records.
#define AUDIO_CARD "default"
The name of the default sound card.
#define AUDIO_MIXER "Master"
The name of the used mixer.
#define ERR 1
Error code.
#define NO_ERR 0
No error code.
#define MAX_VOL 100
The maximal volume in percents.
Enumerations
enum AUDIO_ACTIONS { AUDIO_VOLUME_SET_VOLUME, AUDIO_VOLUME_GET_VOLUME, AUDIO_VOLUME_SET_MUTE, AUDIO_VOLUME_GET_MUTE }
The actions for audio.
enum SOUND_STATE { UNMUTED, MUTED }
The states of sound: muted, unmuted.
Functions
const int doSoundVolAction (const int action, long *vol)
Make the given action on the sound volume, e.g.
const int initSoundControl ()
Initialise the sound control.
void finishSoundControl ()
Finish sound control using.
void mute ()
Make the sound state muted.
void unmute ()
Unmute the sound state.
void chgVol (const int value)
Change the current value by the given value if the given value > 0, then increase the current volume by value if the given value < 0, then decrease the current volume by value.
const long getVol ()
Get current volume.
const bool isMuted ()
Is the sound state muted.
Variables
long volume_
long state_
Current volume percent and the state of sound.
long minv
long maxv
Minimal and maximal volume.
snd_mixer_t * handle
snd_mixer_elem_t * elem
Detailed Description
The library for control of the sound system volume.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file SoundLib.c.
Macro Definition Documentation
#define AUDIO_CARD "default"
The name of the default sound card.
Definition at line 38 of file SoundLib.c.
Referenced by initSoundControl().
#define AUDIO_MIXER "Master"
The name of the used mixer.
Definition at line 39 of file SoundLib.c.
Referenced by initSoundControl().
#define ERR 1
Error code.
Definition at line 41 of file SoundLib.c.
Referenced by doSoundVolAction(), and initSoundControl().
#define MAX_VOL 100
The maximal volume in percents.
Definition at line 44 of file SoundLib.c.
Referenced by chgVol(), and doSoundVolAction().
#define NO_ERR 0
No error code.
Definition at line 42 of file SoundLib.c.
Referenced by chgVol(), doSoundVolAction(), finishSoundControl(), initSoundControl(), isMuted(), mute(), and unmute().
#define TAG "SOUND_LIB"
The tag for log file records.
Definition at line 36 of file SoundLib.c.
Referenced by doSoundVolAction(), finishSoundControl(), and initSoundControl().
Enumeration Type Documentation
enum AUDIO_ACTIONS
The actions for audio.
Enumerator
AUDIO_VOLUME_SET_VOLUME
AUDIO_VOLUME_GET_VOLUME
AUDIO_VOLUME_SET_MUTE
AUDIO_VOLUME_GET_MUTE
Definition at line 50 of file SoundLib.c.
enum SOUND_STATE
The states of sound: muted, unmuted.
Enumerator
UNMUTED
MUTED
Definition at line 62 of file SoundLib.c.
Function Documentation
void chgVol (const int value)
Change the current value by the given value if the given value > 0, then increase the current volume by value if the given value < 0, then decrease the current volume by value.
Parameters
value The value of change.
Definition at line 237 of file SoundLib.c.
References AUDIO_VOLUME_SET_VOLUME, doSoundVolAction(), finishSoundControl(), initSoundControl(), MAX_VOL, NO_ERR, and volume_.
Referenced by SndConnector::doChgVol().
const int doSoundVolAction (const int action, long * vol)
Make the given action on the sound volume, e.g.
mute or get the current volume value.
Parameters
action The action type: get mute state or set mute, get or set volume
vol The current sound volume
Returns
ERR or NO_ERR
Definition at line 77 of file SoundLib.c.
References AUDIO_VOLUME_GET_MUTE, AUDIO_VOLUME_GET_VOLUME, AUDIO_VOLUME_SET_MUTE, AUDIO_VOLUME_SET_VOLUME, elem, ERR, MAX_VOL, maxv, minv, mute(), MUTED, NO_ERR, TAG, UNMUTED, and writeToLog2().
Referenced by chgVol(), initSoundControl(), isMuted(), mute(), and unmute().
void finishSoundControl ()
Finish sound control using.
Definition at line 188 of file SoundLib.c.
References handle, NO_ERR, TAG, and writeToLog2().
Referenced by chgVol(), getVol(), isMuted(), mute(), and unmute().
const long getVol ()
Get current volume.
Returns
The current volume percents
Definition at line 257 of file SoundLib.c.
References finishSoundControl(), initSoundControl(), and volume_.
Referenced by SndConnector::doGetVol().
const int initSoundControl ()
Initialise the sound control.
Returns
The sound control handler
Definition at line 132 of file SoundLib.c.
References AUDIO_CARD, AUDIO_MIXER, AUDIO_VOLUME_GET_MUTE, AUDIO_VOLUME_GET_VOLUME, doSoundVolAction(), elem, ERR, handle, maxv, minv, NO_ERR, state_, TAG, volume_, and writeToLog2().
Referenced by chgVol(), getVol(), isMuted(), mute(), and unmute().
const bool isMuted ()
Is the sound state muted.
Returns
True if the sound state is muted
Definition at line 268 of file SoundLib.c.
References AUDIO_VOLUME_GET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, and state_.
Referenced by SndConnector::doIsMuted().
void mute ()
Make the sound state muted.
Definition at line 202 of file SoundLib.c.
References AUDIO_VOLUME_SET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, state_, and UNMUTED.
Referenced by SndConnector::doMute(), and doSoundVolAction().
void unmute ()
Unmute the sound state.
Definition at line 218 of file SoundLib.c.
References AUDIO_VOLUME_SET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, state_, and UNMUTED.
Referenced by SndConnector::doUnmute().
Variable Documentation
snd_mixer_elem_t* elem
Definition at line 68 of file SoundLib.c.
Referenced by doSoundVolAction(), and initSoundControl().
snd_mixer_t* handle
Definition at line 67 of file SoundLib.c.
Referenced by ConnectorBT::callToFuncFromDynLib(), finishSoundControl(), and initSoundControl().
long maxv
Minimal and maximal volume.
Definition at line 65 of file SoundLib.c.
Referenced by doSoundVolAction(), and initSoundControl().
long minv
Definition at line 65 of file SoundLib.c.
Referenced by doSoundVolAction(), and initSoundControl().
long state_
Current volume percent and the state of sound.
Definition at line 64 of file SoundLib.c.
Referenced by initSoundControl(), isMuted(), mute(), and unmute().
long volume_
Definition at line 64 of file SoundLib.c.
Referenced by chgVol(), getVol(), and initSoundControl().