SounDroid: SoundLib.h File Reference
SoundLib.h File Reference
The library for control of the sound system volume.
#include <stdbool.h>
Functions
void mute ()
Make the sound state muted.
void unmute ()
Unmute the sound state.
void chgVol (const int value)
Change the current value by the given value if the given value > 0, then increase the current volume by value if the given value < 0, then decrease the current volume by value.
const long getVol ()
Get current volume.
const bool isMuted ()
Is the sound state muted.
Detailed Description
The library for control of the sound system volume.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file SoundLib.h.
Function Documentation
void chgVol (const int value)
Change the current value by the given value if the given value > 0, then increase the current volume by value if the given value < 0, then decrease the current volume by value.
Parameters
value The value of change.
Definition at line 237 of file SoundLib.c.
References AUDIO_VOLUME_SET_VOLUME, doSoundVolAction(), finishSoundControl(), initSoundControl(), MAX_VOL, NO_ERR, and volume_.
Referenced by SndConnector::doChgVol().
const long getVol ()
Get current volume.
Returns
The current volume percents
Definition at line 257 of file SoundLib.c.
References finishSoundControl(), initSoundControl(), and volume_.
Referenced by SndConnector::doGetVol().
const bool isMuted ()
Is the sound state muted.
Returns
True if the sound state is muted
Definition at line 268 of file SoundLib.c.
References AUDIO_VOLUME_GET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, and state_.
Referenced by SndConnector::doIsMuted().
void mute ()
Make the sound state muted.
Definition at line 202 of file SoundLib.c.
References AUDIO_VOLUME_SET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, state_, and UNMUTED.
Referenced by SndConnector::doMute(), and doSoundVolAction().
void unmute ()
Unmute the sound state.
Definition at line 218 of file SoundLib.c.
References AUDIO_VOLUME_SET_MUTE, doSoundVolAction(), finishSoundControl(), initSoundControl(), MUTED, NO_ERR, state_, and UNMUTED.
Referenced by SndConnector::doUnmute().