SounDroid: synchronise.c File Reference
synchronise.c File Reference
Threads synchronisation of sending and receiving data by used connection type.
#include "synchronise.h"
#include <string.h>
Macros
#define TAG "synchronise"
The tag for logs.
Functions
void destroyMutexes ()
Destroy mutexes.
void initMutexes ()
Initialize mutexes.
char * getSentData ()
Get pointer to the sent data string.
void setSentData (const char *dataStr)
Set data string for sending.
void setReceivedData (const char *dataStr)
Set received data string by the given string.
char * getReceivedData ()
Get the deceived data string.
void setRunStatus (const int status)
Set the status of running.
const int getRunStatus ()
Get the status of running.
void setReceivedDataStatus (const int status)
Set the status of the recieved data.
Variables
int runStatus = RUN
The run status: running or stopped.
int receivedDataStatus = NO_NEW_DATA
The status of receiving data.
char sentData [DATA_LEN] = {'\0'}
The buffer for the sent data.
char receivedData [DATA_LEN] = {'\0'}
The buffer for the received data.
pthread_mutex_t mutexData
The mutex for synchronising data.
pthread_mutex_t mutexStop
The mutex for synchronising running.
Detailed Description
Threads synchronisation of sending and receiving data by used connection type.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file synchronise.c.
Macro Definition Documentation
#define TAG "synchronise"
The tag for logs.
Definition at line 45 of file synchronise.c.
Function Documentation
void destroyMutexes ()
Destroy mutexes.
Definition at line 50 of file synchronise.c.
References mutexData, and mutexStop.
Referenced by runBtConnection(), and runConnection().
char* getReceivedData ()
Get the deceived data string.
Get the received data string.
Returns
The received data string
Definition at line 102 of file synchronise.c.
References HAS_NEW_DATA, mutexData, NO_NEW_DATA, receivedData, and receivedDataStatus.
Referenced by ConnectorBT::receive(), and ConnectorWiFi::receive().
const int getRunStatus ()
Get the status of running.
Returns
The status: RUN or STOP
Definition at line 130 of file synchronise.c.
References mutexStop, runStatus, and STOP.
Referenced by acceptBtConn(), ConnectorBT::isRunning(), ConnectorWiFi::isRunning(), receiveBtData(), runBtConnection(), and runConnection().
char* getSentData ()
Get pointer to the sent data string.
Returns
The string of the sent data
Definition at line 69 of file synchronise.c.
References sentData.
Referenced by conversation(), conversationBt(), sendBtData(), and sendData().
void initMutexes ()
Initialize mutexes.
Definition at line 59 of file synchronise.c.
References mutexData, and mutexStop.
Referenced by runBtConnection(), and runConnection().
void setReceivedData (const char * dataStr)
Set received data string by the given string.
Parameters
dataStr The string for setting received data
Definition at line 91 of file synchronise.c.
References mutexData, and receivedData.
Referenced by conversation(), and conversationBt().
void setReceivedDataStatus (const int status)
Set the status of the recieved data.
Parameters
status HAS_NEW_DATA or NO_NEW_DATA
Definition at line 143 of file synchronise.c.
References mutexData, and receivedDataStatus.
Referenced by conversation(), and conversationBt().
void setRunStatus (const int status)
Set the status of running.
Parameters
status The status: RUN or STOP
Definition at line 119 of file synchronise.c.
References mutexStop, and runStatus.
Referenced by ConnectorBT::run(), ConnectorWiFi::run(), ConnectorBT::stop(), and ConnectorWiFi::stop().
void setSentData (const char * dataStr)
Set data string for sending.
Parameters
dataStr data string
Definition at line 78 of file synchronise.c.
References DATA_LEN, mutexData, and sentData.
Referenced by ConnectorBT::send(), and ConnectorWiFi::send().
Variable Documentation
mutexData
The mutex for synchronising data.
The mutex for sent/received data.
Definition at line 42 of file synchronise.c.
Referenced by destroyMutexes(), getReceivedData(), initMutexes(), setReceivedData(), setReceivedDataStatus(), and setSentData().
mutexStop
The mutex for synchronising running.
The mutex for run status.
Definition at line 43 of file synchronise.c.
Referenced by destroyMutexes(), getRunStatus(), initMutexes(), and setRunStatus().
char receivedData[DATA_LEN] = {'\0'}
The buffer for the received data.
Definition at line 40 of file synchronise.c.
Referenced by getReceivedData(), and setReceivedData().
int receivedDataStatus = NO_NEW_DATA
The status of receiving data.
Definition at line 36 of file synchronise.c.
Referenced by getReceivedData(), and setReceivedDataStatus().
int runStatus = RUN
The run status: running or stopped.
Definition at line 34 of file synchronise.c.
Referenced by getRunStatus(), and setRunStatus().
char sentData[DATA_LEN] = {'\0'}
The buffer for the sent data.
Definition at line 38 of file synchronise.c.
Referenced by getSentData(), sendBtData(), sendData(), and setSentData().