SounDroid: utils.c File Reference
utils.c File Reference
Utils for writing errors to the log file.
#include "utils.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "Log.h"
Macros
#define TAG "UTILS"
tag for writing to log file
#define ERRSTR "\tERROR: "
Functions
void writeToLogIfError (const int result, const char *funcName, const char *errorStr)
Write error string to the log file.
Detailed Description
Utils for writing errors to the log file.
The MIT License (MIT)
Copyright (c) 2014 Daniel Haimov
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file utils.c.
Macro Definition Documentation
#define ERRSTR "\tERROR: "
Referenced by writeToLogIfError().
#define TAG "UTILS"
tag for writing to log file
Definition at line 37 of file utils.c.
Referenced by writeToLogIfError().
Function Documentation
void writeToLogIfError (const int result, const char * funcName, const char * errorStr)
Write error string to the log file.
Parameters
result The result index, if result is error then the given error string should be written to the log file
funcName The name of the function where the error has taken place
errorStr The error string should be written to the log file
Definition at line 45 of file utils.c.
References ERR, ERRSTR, TAG, and writeToLog().
Referenced by acceptConn(), bindSocket(), createSocket(), and listenConns().