SounDroid: com.soundroid.ui.wifi.WiFiConnectingActivity Class Reference
com.soundroid.ui.wifi.WiFiConnectingActivity Class Reference
Activity for making connection to the given desktop.
Inherits Activity.
Public Member Functions
void onBackPressed ()
Click on 'Back'.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Creating the activity.
Private Member Functions
Runnable getConnection (final DesktopData data)
Connect to desktop which data has given.
Static Private Attributes
static final String TAG = "WiFiConnectingActivity"
The tag for writing to log.
Detailed Description
Activity for making connection to the given desktop.
Definition at line 45 of file WiFiConnectingActivity.java.
Member Function Documentation
Runnable com.soundroid.ui.wifi.WiFiConnectingActivity.getConnection (final DesktopData data) inline private
Connect to desktop which data has given.
Parameters
data The data of the desktop for connecting to
Returns
The runnable instance of the function
Definition at line 106 of file WiFiConnectingActivity.java.
References com.soundroid.ui.UI.connector, com.soundroid.net.NetConnector.isAddrReachable(), and com.soundroid.ui.wifi.WiFiConnectingActivity.TAG.
Referenced by com.soundroid.ui.wifi.WiFiConnectingActivity.onCreate().
void com.soundroid.ui.wifi.WiFiConnectingActivity.onBackPressed () inline
Click on 'Back'.
Definition at line 96 of file WiFiConnectingActivity.java.
void com.soundroid.ui.wifi.WiFiConnectingActivity.onCreate (Bundle savedInstanceState) inline protected
Creating the activity.
Parameters
savedInstanceState
Definition at line 54 of file WiFiConnectingActivity.java.
References com.soundroid.ui.UI.connector, com.soundroid.ui.UI.DESKTOPS_DATA, com.soundroid.ui.wifi.WiFiConnectingActivity.getConnection(), and com.soundroid.ui.wifi.WiFiConnectingActivity.TAG.
Field Documentation
final String com.soundroid.ui.wifi.WiFiConnectingActivity.TAG = "WiFiConnectingActivity" static private
The tag for writing to log.
Definition at line 47 of file WiFiConnectingActivity.java.
Referenced by com.soundroid.ui.wifi.WiFiConnectingActivity.getConnection(), and com.soundroid.ui.wifi.WiFiConnectingActivity.onCreate().
The documentation for this class was generated from the following file:
WiFiConnectingActivity.java