SounDroid: com.soundroid.tests.DistanceVolumeActivityTests Class Reference
com.soundroid.tests.DistanceVolumeActivityTests Class Reference
Inherits ActivityInstrumentationTestCase2< DistanceVolumeActivity >.
Data Structures
class SeekBarCondition
Public Member Functions
DistanceVolumeActivityTests ()
void setUp () throws Exception
void testElementsPresenceInActivity ()
void testConnectionTypeRadioButtons ()
void testAddDesktops ()
void testSelectUnreachableDesktop ()
void testMainActivityAfterEditCancel () throws InterruptedException
void testMainActivityAfterAddNewCancel () throws InterruptedException
void testReachableDesktopSoundElementsEnabled ()
void tearDown () throws Exception
Static Public Member Functions
static void wifiTurnON (final InstrumentationTestCase test)
static void wifiTurnOFF (final InstrumentationTestCase test)
Private Attributes
Solo solo
final String reachableDesktopName = EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.REACHABLE.getValue()
final String unreachableDesktopName = EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.UNREACHABLE.getValue()
Detailed Description
Definition at line 23 of file DistanceVolumeActivityTests.java.
Constructor & Destructor Documentation
com.soundroid.tests.DistanceVolumeActivityTests.DistanceVolumeActivityTests () inline
Definition at line 26 of file DistanceVolumeActivityTests.java.
Member Function Documentation
void com.soundroid.tests.DistanceVolumeActivityTests.setUp () throws Exception inline
Definition at line 34 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.solo, and com.soundroid.tests.DistanceVolumeActivityTests.wifiTurnON().
void com.soundroid.tests.DistanceVolumeActivityTests.tearDown () throws Exception inline
Definition at line 237 of file DistanceVolumeActivityTests.java.
void com.soundroid.tests.DistanceVolumeActivityTests.testAddDesktops () inline
Definition at line 68 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.reachableDesktopName, com.soundroid.tests.DistanceVolumeActivityTests.solo, and com.soundroid.tests.DistanceVolumeActivityTests.unreachableDesktopName.
void com.soundroid.tests.DistanceVolumeActivityTests.testConnectionTypeRadioButtons () inline
Definition at line 61 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.solo.
void com.soundroid.tests.DistanceVolumeActivityTests.testElementsPresenceInActivity () inline
Definition at line 51 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.solo.
void com.soundroid.tests.DistanceVolumeActivityTests.testMainActivityAfterAddNewCancel () throws InterruptedException inline
Definition at line 182 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.solo.
void com.soundroid.tests.DistanceVolumeActivityTests.testMainActivityAfterEditCancel () throws InterruptedException inline
Definition at line 142 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.solo.
void com.soundroid.tests.DistanceVolumeActivityTests.testReachableDesktopSoundElementsEnabled () inline
Definition at line 206 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.reachableDesktopName, and com.soundroid.tests.DistanceVolumeActivityTests.solo.
void com.soundroid.tests.DistanceVolumeActivityTests.testSelectUnreachableDesktop () inline
Definition at line 110 of file DistanceVolumeActivityTests.java.
References com.soundroid.tests.DistanceVolumeActivityTests.reachableDesktopName, com.soundroid.tests.DistanceVolumeActivityTests.solo, and com.soundroid.tests.DistanceVolumeActivityTests.unreachableDesktopName.
static void com.soundroid.tests.DistanceVolumeActivityTests.wifiTurnOFF (final InstrumentationTestCase test) inline static
Definition at line 45 of file DistanceVolumeActivityTests.java.
static void com.soundroid.tests.DistanceVolumeActivityTests.wifiTurnON (final InstrumentationTestCase test) inline static
Definition at line 39 of file DistanceVolumeActivityTests.java.
Referenced by com.soundroid.tests.DistanceVolumeActivityTests.setUp().
Field Documentation
final String com.soundroid.tests.DistanceVolumeActivityTests.reachableDesktopName = EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.REACHABLE.getValue() private
Definition at line 30 of file DistanceVolumeActivityTests.java.
Referenced by com.soundroid.tests.DistanceVolumeActivityTests.testAddDesktops(), com.soundroid.tests.DistanceVolumeActivityTests.testReachableDesktopSoundElementsEnabled(), and com.soundroid.tests.DistanceVolumeActivityTests.testSelectUnreachableDesktop().
Solo com.soundroid.tests.DistanceVolumeActivityTests.solo private
Definition at line 24 of file DistanceVolumeActivityTests.java.
Referenced by com.soundroid.tests.DistanceVolumeActivityTests.setUp(), com.soundroid.tests.DistanceVolumeActivityTests.testAddDesktops(), com.soundroid.tests.DistanceVolumeActivityTests.testConnectionTypeRadioButtons(), com.soundroid.tests.DistanceVolumeActivityTests.testElementsPresenceInActivity(), com.soundroid.tests.DistanceVolumeActivityTests.testMainActivityAfterAddNewCancel(), com.soundroid.tests.DistanceVolumeActivityTests.testMainActivityAfterEditCancel(), com.soundroid.tests.DistanceVolumeActivityTests.testReachableDesktopSoundElementsEnabled(), and com.soundroid.tests.DistanceVolumeActivityTests.testSelectUnreachableDesktop().
final String com.soundroid.tests.DistanceVolumeActivityTests.unreachableDesktopName = EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.UNREACHABLE.getValue() private
Definition at line 31 of file DistanceVolumeActivityTests.java.
Referenced by com.soundroid.tests.DistanceVolumeActivityTests.testAddDesktops(), and com.soundroid.tests.DistanceVolumeActivityTests.testSelectUnreachableDesktop().
The documentation for this class was generated from the following file:
DistanceVolumeActivityTests.java