SounDroid: com.soundroid.net.wifi.WifiDesktopData Class Reference
com.soundroid.net.wifi.WifiDesktopData Class Reference
Created by saratoga on 10/10/14.
Inherits com.soundroid.net.DesktopData.
Public Member Functions
WifiDesktopData (final String name, final String address, final String port)
Constructor initializing desktop's data.
WifiDesktopData ()
Default desktop Make all data empty.
WifiDesktopData (final String data)
Constructor initializing a desktop data from the given string.
String toString ()
Get desktop's data in string.
String[] getAddressArr ()
Get the IP as a strings array.
boolean equals (final Object otherData)
Compare the data with an other one.
Public Member Functions inherited from com.soundroid.net.DesktopData
String getName ()
Get desktop's name.
String getAddress ()
Get desktop's IP.
String getPort ()
Get the port number of the daemon running on the desktop.
void setName (String name)
Set desktop's name.
void setAddress (String address)
Set desktop's IP.
void setPort (String port)
Set the desktop's port number.
abstract String[] getAddressArr ()
Get the address array of strings.
boolean isEmpty ()
Is the desktop's data empty?
Private Member Functions
void chkAddress (final String addrStr)
Check the given string is IP address.
Static Private Attributes
static final int IP_ADDR_PARTS_NUM = 4
Additional Inherited Members
Protected Member Functions inherited from com.soundroid.net.DesktopData
String[] getAddressArr (final int len, final String delimiter)
Get the address array of strings.
Protected Attributes inherited from com.soundroid.net.DesktopData
String name
The desktop's name, given by user.
String address
The IP of the desktop.
String port
The port number of the daemon, running on the desktop.
Static Protected Attributes inherited from com.soundroid.net.DesktopData
static final long serialVersionUID = 1L
Detailed Description
Created by saratoga on 10/10/14.
Definition at line 40 of file WifiDesktopData.java.
Constructor & Destructor Documentation
com.soundroid.net.wifi.WifiDesktopData.WifiDesktopData (final String name, final String address, final String port) inline
Constructor initializing desktop's data.
Parameters
name The name of the desktop
address The desktop's IP
port The port number of the daemon on the desktop
Definition at line 49 of file WifiDesktopData.java.
References com.soundroid.net.DesktopData.address, com.soundroid.net.wifi.WifiDesktopData.chkAddress(), com.soundroid.net.DesktopData.name, and com.soundroid.net.DesktopData.port.
com.soundroid.net.wifi.WifiDesktopData.WifiDesktopData () inline
Default desktop Make all data empty.
Definition at line 78 of file WifiDesktopData.java.
References com.soundroid.net.DesktopData.setAddress(), com.soundroid.net.DesktopData.setName(), and com.soundroid.net.DesktopData.setPort().
Referenced by com.soundroid.net.wifi.WifiDesktopData.equals().
com.soundroid.net.wifi.WifiDesktopData.WifiDesktopData (final String data) inline
Constructor initializing a desktop data from the given string.
Parameters
data The string with desktop's data
Definition at line 110 of file WifiDesktopData.java.
References com.soundroid.net.DesktopData.address, com.soundroid.net.DesktopData.name, and com.soundroid.net.DesktopData.port.
Member Function Documentation
void com.soundroid.net.wifi.WifiDesktopData.chkAddress (final String addrStr) inline private
Check the given string is IP address.
Parameters
addrStr The IP string
Definition at line 88 of file WifiDesktopData.java.
Referenced by com.soundroid.net.wifi.WifiDesktopData.WifiDesktopData().
boolean com.soundroid.net.wifi.WifiDesktopData.equals (final Object otherData) inline
Compare the data with an other one.
Parameters
otherData The other blue tooth desktop data
Returns
true The datas are equal
Definition at line 161 of file WifiDesktopData.java.
References com.soundroid.net.DesktopData.address, com.soundroid.net.DesktopData.name, com.soundroid.net.DesktopData.port, and com.soundroid.net.wifi.WifiDesktopData.WifiDesktopData().
String [] com.soundroid.net.wifi.WifiDesktopData.getAddressArr () inline
Get the IP as a strings array.
Returns
The array of strings
Definition at line 151 of file WifiDesktopData.java.
References com.soundroid.net.wifi.WifiDesktopData.IP_ADDR_PARTS_NUM.
String com.soundroid.net.wifi.WifiDesktopData.toString () inline
Get desktop's data in string.
Returns
The string of the desktop's data
Definition at line 142 of file WifiDesktopData.java.
References com.soundroid.net.DesktopData.address, com.soundroid.net.DesktopData.name, and com.soundroid.net.DesktopData.port.
Field Documentation
final int com.soundroid.net.wifi.WifiDesktopData.IP_ADDR_PARTS_NUM = 4 static private
Definition at line 41 of file WifiDesktopData.java.
Referenced by com.soundroid.net.wifi.WifiDesktopData.getAddressArr().
The documentation for this class was generated from the following file:
WifiDesktopData.java