SounDroid: com.soundroid.ui.bluetooth.BluetoothUI Class Reference
com.soundroid.ui.bluetooth.BluetoothUI Class Reference
UI for connecting by blue tooth.
Inherits com.soundroid.ui.UI.
Public Member Functions
BluetoothUI (final Activity activity)
Constructor.
void initDesktopsDatasFromFile ()
Initialize desktops data from file.
void saveDesktopsDatas ()
Save desktops data to file.
void processActivityResult (final int requestCode, final Intent data)
Process the results of the closed activities.
void connectToNetByDialog ()
Turning on bluetooth connection by opening dialog 'Bluetooth permission request' for user.
void setVolumeUI ()
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
Public Member Functions inherited from com.soundroid.ui.UI
void saveUiData ()
Save the current UI data.
NetConnector getConnector ()
Get current network connector.
abstract void saveDesktopsDatas ()
Save the datas of desktops.
abstract void initDesktopsDatasFromFile ()
Initialization of the desktops data from file.
UI buildUiBySelectedRadioButt (final Activity activity)
Build the UI with depends on the selected Radio button of connection type.
synchronized void setConnectionTypeChanged (final boolean state)
Set the flag of connection type changing.
synchronized boolean hasConnectionTypeChanged ()
Get the flag of connection type changing.
void initUI (final boolean connected)
Initialization of an user interface.
void initDesktopNamesSpinner ()
Initialization of the 'Desktops Names' spinner.
abstract void processActivityResult (final int requestCode, final Intent data)
Process the result of the activity.
synchronized void redraw (final boolean flag)
Set the flag for redrawing UI.
synchronized boolean shouldBeRedrawn ()
Should the UI be redrawn.
synchronized void redrawSoundVolUI (final boolean flag)
Set the flag for redrawing of the UI of the sound volume.
synchronized boolean shouldBeRedrawnSoundVolUI ()
Should the UI of the sound volume be redrawn.
void clrDesktopsData ()
Clear the list of desktops data.
abstract void connectToNetByDialog ()
Connect to a network by opening dialog for user selection.
void onItemSelected (AdapterView<?> parent, View view, int pos, long id)
If an item of the desktops names drop box selected the volume percent of the selected desktop should be set.
void onNothingSelected (AdapterView<?> arg0)
Not used.
Protected Member Functions
void saveCurConnectionType ()
Save the type of the current connection(Wifi or bluetooth)
void fillDesktopsListFromFile (final String fileName) throws IOException
Fill the list of desktops names by the data from file.
void initConnectionTypeRadioButt ()
Initialize the radio button for selecting connection type bluetooth.
void initNewButt ()
Initialization of the button 'New'.
void initEditButt ()
Initialisation of the button 'Edit'.
void reInitConnector ()
Re-initialize the bluetooth connector.
Protected Member Functions inherited from com.soundroid.ui.UI
void saveDesktopsDatas (String fileName)
Save the txt_view_item of desktops' datas.
abstract void saveCurConnectionType ()
Save current connection type.
abstract void fillDesktopsListFromFile (final String fileName) throws IOException
Fill the list of desktops datas from file.
void initDesktopsDatasFromFile (final String fileName)
Initialization of the desktops data from file.
abstract void initConnectionTypeRadioButt ()
Initialize the radio button of connection type.
abstract void setVolumeUI ()
Set the UI of sound volume.
void showOkDialog (String txt)
Show a dialog with the given text and the button 'OK'.
void enableVolumeSeekBar ()
Enable the seek bar for changing volume.
void setVolumeUiElements ()
Set values for the elements of the Volume UI(mute/unmute button, volume seekbar, etc)
abstract void initNewButt ()
Initialize the 'New' button.
abstract void initEditButt ()
Initialize the 'Edit' button.
boolean isDesktopDataDefault (final String name)
Check whether the desktop with the given name is default.
DesktopData getDesktopDataByName (final String name)
Get the desktop's data by the given name.
void removeCurrentlyEditedDesktopData ()
Remove the currently edited desktop data.
abstract void reInitConnector ()
Re-initialize connection to a network.
Private Member Functions
BluetoothUI ()
void openConnectingActivity (final String connectedDevName)
Open the activity of connecting.
void saveConnectedDesktopData ()
Save the desktop data of the currently connected remote bluetooth device.
String getCurSelectedDesktopName ()
Get the name of the desktop currently selected in UI.
void enableBlueTooth ()
Enable bluetooth connection.
Private Attributes
String TAG = "BluetoothUI"
The tag for logs.
Static Private Attributes
static final String NAMES_DATA_FILE_NAME = "bt.data"
The file containing the desktops data of found remote devices.
static final int REQUEST_CODE_FIND_REMOTE_DEV = 24
The request code for founding remote devices.
Additional Inherited Members
Static Public Member Functions inherited from com.soundroid.ui.UI
static UI buildUiFromFile (final Activity activity) throws IOException, NumberFormatException
Initialization from file the radio button 'Connection type' checked at previous session.
Static Public Attributes inherited from com.soundroid.ui.UI
static final String FILE_NAME = "file_name"
static final String DESKTOPS_DATA = "DESKTOPS_DATA"
static final int EDIT_DESKTOP_NAME = 1
The selected action in the activity.
static final String SINGLE_DESKTOP_DATA = "DESKTOP_DATA"
static final int REQUEST_CODE_EDIT = 1
The request code for a selected action.
static final String IS_DEFAULT = "IS_DEFAULT"
static NetConnector connector
The network connector instance.
Protected Attributes inherited from com.soundroid.ui.UI
Context context
The application's context.
MuteButton muteButt
The button for muting volume.
Button buttEdit
RadioGroup connectionTypeRadio
The radio buttons group for connection types.
Spinner desktopsNames
The drop box of the desktops names for connecting.
SeekBar volume
The seek bar for changing volume in percents.
List< DesktopData > desktopsDatas
The txt_view_item of desktops data.
final int NO_EDIT = -1
int curEditedDesktopNameInd = NO_EDIT
The selected desktop name on the spinner at the time of clicking on the button 'Edit'.
int curSelectedDesktopNameInd = 0
Currently selected desktop name on the spinner.
boolean host_connection_checked = false
The connection to the currently selected desktop's host has checked.
boolean redraw = false
The activity should be redrawn.
boolean redrawSoundVolUI = false
The part of UI for controlling sound volume should be redrawn.
Activity activity
The current activity instance.
Static Protected Attributes inherited from com.soundroid.ui.UI
static String CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME = "conn_type"
The name of the file containing the ID of the connection type radio button selected at last session.
Detailed Description
UI for connecting by blue tooth.
Definition at line 57 of file BluetoothUI.java.
Constructor & Destructor Documentation
com.soundroid.ui.bluetooth.BluetoothUI.BluetoothUI () inline private
Definition at line 62 of file BluetoothUI.java.
com.soundroid.ui.bluetooth.BluetoothUI.BluetoothUI (final Activity activity) inline
Constructor.
Parameters
activity Main activity instance
Definition at line 68 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.connector, com.soundroid.ui.UI.context, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
Member Function Documentation
void com.soundroid.ui.bluetooth.BluetoothUI.connectToNetByDialog () inline
Turning on bluetooth connection by opening dialog 'Bluetooth permission request' for user.
Definition at line 218 of file BluetoothUI.java.
References com.soundroid.ui.bluetooth.BluetoothUI.enableBlueTooth().
void com.soundroid.ui.bluetooth.BluetoothUI.enableBlueTooth () inline private
Enable bluetooth connection.
Definition at line 253 of file BluetoothUI.java.
References com.soundroid.ui.UI.connector, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.connectToNetByDialog().
void com.soundroid.ui.bluetooth.BluetoothUI.fillDesktopsListFromFile (final String fileName) throws IOException inline protected
Fill the list of desktops names by the data from file.
Parameters
fileName The name of the file
Exceptions
IOException
Definition at line 97 of file BluetoothUI.java.
References com.soundroid.ui.UI.connector, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
String com.soundroid.ui.bluetooth.BluetoothUI.getCurSelectedDesktopName () inline private
Get the name of the desktop currently selected in UI.
Returns
The name of the desktop or empty string
Definition at line 240 of file BluetoothUI.java.
References com.soundroid.ui.UI.curSelectedDesktopNameInd, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.reInitConnector().
void com.soundroid.ui.bluetooth.BluetoothUI.initConnectionTypeRadioButt () inline protected
Initialize the radio button for selecting connection type bluetooth.
Definition at line 137 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity.
void com.soundroid.ui.bluetooth.BluetoothUI.initDesktopsDatasFromFile () inline
Initialize desktops data from file.
Definition at line 111 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.desktopsDatas, com.soundroid.ui.bluetooth.BluetoothUI.NAMES_DATA_FILE_NAME, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
void com.soundroid.ui.bluetooth.BluetoothUI.initEditButt () inline protected
Initialisation of the button 'Edit'.
Definition at line 169 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity, and com.soundroid.ui.UI.buttEdit.
void com.soundroid.ui.bluetooth.BluetoothUI.initNewButt () inline protected
Initialization of the button 'New'.
Definition at line 160 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity.
void com.soundroid.ui.bluetooth.BluetoothUI.openConnectingActivity (final String connectedDevName) inline private
Open the activity of connecting.
Definition at line 146 of file BluetoothUI.java.
References com.soundroid.ui.bluetooth.BlueToothConnectingActivity.CONNECTED_DEV_NAME, com.soundroid.ui.UI.context, com.soundroid.ui.bluetooth.BluetoothUI.REQUEST_CODE_FIND_REMOTE_DEV, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.setVolumeUI().
void com.soundroid.ui.bluetooth.BluetoothUI.processActivityResult (final int requestCode, final Intent data) inline
Process the results of the closed activities.
Parameters
requestCode The request code
data The data from the closed activity
Definition at line 180 of file BluetoothUI.java.
References com.soundroid.ui.bluetooth.BlueToothConnectingActivity.IS_REMOTE_DEV_FOUND, com.soundroid.ui.UI.redraw, com.soundroid.ui.bluetooth.BluetoothUI.REQUEST_CODE_FIND_REMOTE_DEV, com.soundroid.ui.bluetooth.BluetoothUI.saveConnectedDesktopData(), and com.soundroid.ui.UI.showOkDialog().
void com.soundroid.ui.bluetooth.BluetoothUI.reInitConnector () inline protected
Re-initialize the bluetooth connector.
Definition at line 226 of file BluetoothUI.java.
References com.soundroid.ui.UI.connector, com.soundroid.ui.bluetooth.BluetoothUI.getCurSelectedDesktopName(), and com.soundroid.net.NetConnector.isConnectedToDaemon().
void com.soundroid.ui.bluetooth.BluetoothUI.saveConnectedDesktopData () inline private
Save the desktop data of the currently connected remote bluetooth device.
Definition at line 198 of file BluetoothUI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.connector, com.soundroid.ui.bluetooth.BluetoothUI.NAMES_DATA_FILE_NAME, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.processActivityResult().
void com.soundroid.ui.bluetooth.BluetoothUI.saveCurConnectionType () inline protected
Save the type of the current connection(Wifi or bluetooth)
Definition at line 80 of file BluetoothUI.java.
References com.soundroid.ui.UI.CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME, com.soundroid.ui.UI.context, and com.soundroid.ui.bluetooth.BluetoothUI.TAG.
void com.soundroid.ui.bluetooth.BluetoothUI.saveDesktopsDatas () inline
Save desktops data to file.
Definition at line 131 of file BluetoothUI.java.
void com.soundroid.ui.bluetooth.BluetoothUI.setVolumeUI () inline
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
Definition at line 271 of file BluetoothUI.java.
References com.soundroid.ui.UI.connector, com.soundroid.ui.UI.curSelectedDesktopNameInd, com.soundroid.net.bluetooth.BluetoothConnector.getConnectedDeviceName(), com.soundroid.net.DesktopData.getName(), com.soundroid.ui.UI.host_connection_checked, com.soundroid.net.NetConnector.isConnectedToDaemon(), com.soundroid.ui.bluetooth.BluetoothUI.openConnectingActivity(), com.soundroid.ui.UI.setVolumeUiElements(), and com.soundroid.ui.UI.showOkDialog().
Field Documentation
final String com.soundroid.ui.bluetooth.BluetoothUI.NAMES_DATA_FILE_NAME = "bt.data" static private
The file containing the desktops data of found remote devices.
Definition at line 58 of file BluetoothUI.java.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.initDesktopsDatasFromFile(), and com.soundroid.ui.bluetooth.BluetoothUI.saveConnectedDesktopData().
final int com.soundroid.ui.bluetooth.BluetoothUI.REQUEST_CODE_FIND_REMOTE_DEV = 24 static private
The request code for founding remote devices.
Definition at line 59 of file BluetoothUI.java.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.openConnectingActivity(), and com.soundroid.ui.bluetooth.BluetoothUI.processActivityResult().
String com.soundroid.ui.bluetooth.BluetoothUI.TAG = "BluetoothUI" private
The tag for logs.
Definition at line 60 of file BluetoothUI.java.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.BluetoothUI(), com.soundroid.ui.bluetooth.BluetoothUI.enableBlueTooth(), com.soundroid.ui.bluetooth.BluetoothUI.fillDesktopsListFromFile(), com.soundroid.ui.bluetooth.BluetoothUI.getCurSelectedDesktopName(), com.soundroid.ui.bluetooth.BluetoothUI.initDesktopsDatasFromFile(), com.soundroid.ui.bluetooth.BluetoothUI.openConnectingActivity(), com.soundroid.ui.bluetooth.BluetoothUI.saveConnectedDesktopData(), and com.soundroid.ui.bluetooth.BluetoothUI.saveCurConnectionType().
The documentation for this class was generated from the following file:
BluetoothUI.java