SounDroid: com.android.ui.ConnectingActivity Class Reference
com.android.ui.ConnectingActivity Class Reference
Activity for making connection to the given desktop.
Inherits Activity.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
Runnable getConnection (final DesktopData data)
Connect to desktop which data has given.
Private Attributes
NetConnector connector
The network connector.
Static Private Attributes
static final String TAG = "ConnectingActivity"
The tag for writing to log.
Detailed Description
Activity for making connection to the given desktop.
Definition at line 44 of file ConnectingActivity.java.
Member Function Documentation
Runnable com.android.ui.ConnectingActivity.getConnection (final DesktopData data) inline private
Connect to desktop which data has given.
Parameters
data The data of the desktop for connecting to
Returns
The runnable instance of the function
Definition at line 96 of file ConnectingActivity.java.
References com.android.net.NetConnector.connect(), com.android.ui.ConnectingActivity.connector, com.android.net.DesktopData.getIP(), com.android.net.DesktopData.getPort(), com.android.net.NetConnector.handShake(), com.android.net.NetConnector.isReachable(), and com.android.ui.ConnectingActivity.TAG.
Referenced by com.android.ui.ConnectingActivity.onCreate().
void com.android.ui.ConnectingActivity.onCreate (Bundle savedInstanceState) inline protected
Definition at line 56 of file ConnectingActivity.java.
References com.android.ui.ConnectingActivity.connector, com.android.ui.DistanceVolumeActivity.connector, com.android.ui.DistanceVolumeActivity.EXTRA_ACTION_TYPE, com.android.ui.ConnectingActivity.getConnection(), and com.android.ui.ConnectingActivity.TAG.
Field Documentation
NetConnector com.android.ui.ConnectingActivity.connector private
The network connector.
Definition at line 53 of file ConnectingActivity.java.
Referenced by com.android.ui.ConnectingActivity.getConnection(), and com.android.ui.ConnectingActivity.onCreate().
final String com.android.ui.ConnectingActivity.TAG = "ConnectingActivity" static private
The tag for writing to log.
Definition at line 51 of file ConnectingActivity.java.
Referenced by com.android.ui.ConnectingActivity.getConnection(), and com.android.ui.ConnectingActivity.onCreate().
The documentation for this class was generated from the following file:
ConnectingActivity.java