SounDroid: com.android.net.DesktopData Class Reference
com.android.net.DesktopData Class Reference
The data of the desktop and operations with it.
Inherits Serializable.
Public Member Functions
DesktopData (String name, String ip, String port)
Constructor initializing desktop's data.
DesktopData (String data)
Constructor initializing a desktop data from the given string.
String getName ()
Get desktop's name.
String getIP ()
Get desktop's IP.
String getPort ()
Get the port number of the daemon running on the desktop.
String toString ()
Get desktop's data in string.
void setName (String name)
Set desktop's name.
void setIP (String ip)
Set desktop's IP.
void setPort (String port)
Set the desktop's port number.
String[] getIpArr ()
Get the IP as a strings array.
boolean isEmpty ()
Is the desktop's data empty?
Static Public Member Functions
static DesktopData buildEmptyDesktopData ()
Build the desktop data containing empty IP, name and name.
Private Member Functions
void chkIP (String ipStr)
Check the given string is IP address.
Private Attributes
String name
The desktop's name, given by user.
String ip
The IP of the desktop.
String port
The port number of the daemon, running on the desktop.
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
The data of the desktop and operations with it.
Definition at line 42 of file DesktopData.java.
Constructor & Destructor Documentation
com.android.net.DesktopData.DesktopData (String name, String ip, String port) inline
Constructor initializing desktop's data.
Parameters
name The name of the desktop
ip The desktop's IP
port The port number of the daemon on the desktop
Definition at line 55 of file DesktopData.java.
References com.android.net.DesktopData.chkIP(), com.android.net.DesktopData.ip, com.android.net.DesktopData.name, and com.android.net.DesktopData.port.
Referenced by com.android.net.DesktopData.buildEmptyDesktopData().
com.android.net.DesktopData.DesktopData (String data) inline
Constructor initializing a desktop data from the given string.
Parameters
data The string with desktop's data
Definition at line 84 of file DesktopData.java.
References com.android.net.DesktopData.ip, com.android.net.DesktopData.name, and com.android.net.DesktopData.port.
Member Function Documentation
static DesktopData com.android.net.DesktopData.buildEmptyDesktopData () inline static
Build the desktop data containing empty IP, name and name.
Returns
The empty desktop data instance
Definition at line 114 of file DesktopData.java.
References com.android.net.DesktopData.DesktopData(), com.android.net.DesktopData.setIP(), com.android.net.DesktopData.setName(), and com.android.net.DesktopData.setPort().
Referenced by com.android.ui.EditDesktopDataActivity.onCreate(), and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
void com.android.net.DesktopData.chkIP (String ipStr) inline private
Check the given string is IP address.
Parameters
ipStr The IP string
Definition at line 193 of file DesktopData.java.
Referenced by com.android.net.DesktopData.DesktopData().
String com.android.net.DesktopData.getIP () inline
Get desktop's IP.
Returns
The desktop's IP
Definition at line 135 of file DesktopData.java.
References com.android.net.DesktopData.ip.
Referenced by com.android.ui.ConnectingActivity.getConnection().
String [] com.android.net.DesktopData.getIpArr () inline
Get the IP as a strings array.
Returns
The array of strings
Definition at line 215 of file DesktopData.java.
References com.android.net.DesktopData.ip.
Referenced by com.android.ui.EditDesktopDataActivity.initUI().
String com.android.net.DesktopData.getName () inline
Get desktop's name.
Returns
The desktop's name
Definition at line 127 of file DesktopData.java.
References com.android.net.DesktopData.name.
Referenced by com.android.ui.EditDesktopDataActivity.initUI(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
String com.android.net.DesktopData.getPort () inline
Get the port number of the daemon running on the desktop.
Returns
The port number
Definition at line 143 of file DesktopData.java.
References com.android.net.DesktopData.port.
Referenced by com.android.ui.ConnectingActivity.getConnection(), and com.android.ui.EditDesktopDataActivity.initUI().
boolean com.android.net.DesktopData.isEmpty () inline
Is the desktop's data empty?
Returns
true The data is empty
Definition at line 227 of file DesktopData.java.
References com.android.net.DesktopData.ip, com.android.net.DesktopData.name, and com.android.net.DesktopData.port.
Referenced by com.android.ui.EditDesktopDataActivity.initDelButt().
void com.android.net.DesktopData.setIP (String ip) inline
Set desktop's IP.
Parameters
ip The desktop's new IP
Definition at line 171 of file DesktopData.java.
References com.android.net.DesktopData.ip.
Referenced by com.android.net.DesktopData.buildEmptyDesktopData().
void com.android.net.DesktopData.setName (String name) inline
Set desktop's name.
Parameters
name The desktop's new name
Definition at line 160 of file DesktopData.java.
References com.android.net.DesktopData.name.
Referenced by com.android.net.DesktopData.buildEmptyDesktopData().
void com.android.net.DesktopData.setPort (String port) inline
Set the desktop's port number.
Parameters
port The desktop's new port
Definition at line 182 of file DesktopData.java.
References com.android.net.DesktopData.port.
Referenced by com.android.net.DesktopData.buildEmptyDesktopData().
String com.android.net.DesktopData.toString () inline
Get desktop's data in string.
Returns
The string of the desktop's data
Definition at line 152 of file DesktopData.java.
References com.android.net.DesktopData.ip, com.android.net.DesktopData.name, and com.android.net.DesktopData.port.
Referenced by com.android.ui.EditDesktopDataActivity.onCreate().
Field Documentation
String com.android.net.DesktopData.ip private
The IP of the desktop.
Definition at line 46 of file DesktopData.java.
Referenced by com.android.net.DesktopData.DesktopData(), com.android.net.DesktopData.getIP(), com.android.net.DesktopData.getIpArr(), com.android.net.DesktopData.isEmpty(), com.android.net.DesktopData.setIP(), and com.android.net.DesktopData.toString().
String com.android.net.DesktopData.name private
The desktop's name, given by user.
Definition at line 45 of file DesktopData.java.
Referenced by com.android.net.DesktopData.DesktopData(), com.android.net.DesktopData.getName(), com.android.net.DesktopData.isEmpty(), com.android.net.DesktopData.setName(), and com.android.net.DesktopData.toString().
String com.android.net.DesktopData.port private
The port number of the daemon, running on the desktop.
Definition at line 47 of file DesktopData.java.
Referenced by com.android.net.DesktopData.DesktopData(), com.android.net.DesktopData.getPort(), com.android.net.DesktopData.isEmpty(), com.android.net.DesktopData.setPort(), and com.android.net.DesktopData.toString().
final long com.android.net.DesktopData.serialVersionUID = 1L static private
Definition at line 43 of file DesktopData.java.
The documentation for this class was generated from the following file:
DesktopData.java