SounDroid: com.android.ui.DistanceVolumeActivity.MuteButton Class Reference
com.android.ui.DistanceVolumeActivity.MuteButton Class Reference
Class of the button for changing volume states: mute, unmute.
Public Member Functions
MuteButton ()
Constructor for initializing the button and its state.
void setEnabled (boolean enabled)
Set the button enabled or disabled.
void setShownMuted (boolean muted)
Set the button's background image depending on the given state.
Private Member Functions
void init ()
Initialize the button.
Private Attributes
Button butt
The button instance.
boolean shownMuted = false
The button shown as muted.
Detailed Description
Class of the button for changing volume states: mute, unmute.
Definition at line 680 of file DistanceVolumeActivity.java.
Constructor & Destructor Documentation
com.android.ui.DistanceVolumeActivity.MuteButton.MuteButton () inline
Constructor for initializing the button and its state.
Definition at line 688 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.MuteButton.butt, and com.android.ui.DistanceVolumeActivity.MuteButton.init().
Member Function Documentation
void com.android.ui.DistanceVolumeActivity.MuteButton.init () inline private
Initialize the button.
Definition at line 716 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.MuteButton.butt, com.android.ui.DistanceVolumeActivity.connector, com.android.net.NetConnector.sendMuteState(), com.android.ui.DistanceVolumeActivity.MuteButton.setShownMuted(), com.android.ui.DistanceVolumeActivity.MuteButton.shownMuted, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.MuteButton.MuteButton().
void com.android.ui.DistanceVolumeActivity.MuteButton.setEnabled (boolean enabled) inline
Set the button enabled or disabled.
Parameters
enabled To enable the button
Definition at line 697 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.MuteButton.butt.
Referenced by com.android.ui.DistanceVolumeActivity.setVolumeUI().
void com.android.ui.DistanceVolumeActivity.MuteButton.setShownMuted (boolean muted) inline
Set the button's background image depending on the given state.
Parameters
muted The state of the button
Definition at line 705 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.MuteButton.butt, and com.android.ui.DistanceVolumeActivity.MuteButton.shownMuted.
Referenced by com.android.ui.DistanceVolumeActivity.MuteButton.init(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
Field Documentation
Button com.android.ui.DistanceVolumeActivity.MuteButton.butt private
The button instance.
Definition at line 682 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.MuteButton.init(), com.android.ui.DistanceVolumeActivity.MuteButton.MuteButton(), com.android.ui.DistanceVolumeActivity.MuteButton.setEnabled(), and com.android.ui.DistanceVolumeActivity.MuteButton.setShownMuted().
boolean com.android.ui.DistanceVolumeActivity.MuteButton.shownMuted = false private
The button shown as muted.
Definition at line 683 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.MuteButton.init(), and com.android.ui.DistanceVolumeActivity.MuteButton.setShownMuted().
The documentation for this class was generated from the following file:
DistanceVolumeActivity.java