SounDroid: com.soundroid.ui.wifi.WifiUI Class Reference
com.soundroid.ui.wifi.WifiUI Class Reference
UI for connecting by wifi.
Inherits com.soundroid.ui.UI.
Public Member Functions
WifiUI (final Activity activity)
Constructor.
void initDesktopsDatasFromFile ()
Initialize desktops data from file.
void saveDesktopsDatas ()
Save desktops data to file.
void processActivityResult (final int requestCode, final Intent data)
void connectToNetByDialog ()
Turning on wifi connection by opening dialog 'Wifi permission request' for user.
void setVolumeUI ()
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
Public Member Functions inherited from com.soundroid.ui.UI
void saveUiData ()
Save the current UI data.
NetConnector getConnector ()
Get current network connector.
abstract void saveDesktopsDatas ()
Save the datas of desktops.
abstract void initDesktopsDatasFromFile ()
Initialization of the desktops data from file.
UI buildUiBySelectedRadioButt (final Activity activity)
Build the UI with depends on the selected Radio button of connection type.
synchronized void setConnectionTypeChanged (final boolean state)
Set the flag of connection type changing.
synchronized boolean hasConnectionTypeChanged ()
Get the flag of connection type changing.
void initUI (final boolean connected)
Initialization of an user interface.
void initDesktopNamesSpinner ()
Initialization of the 'Desktops Names' spinner.
abstract void processActivityResult (final int requestCode, final Intent data)
Process the result of the activity.
synchronized void redraw (final boolean flag)
Set the flag for redrawing UI.
synchronized boolean shouldBeRedrawn ()
Should the UI be redrawn.
synchronized void redrawSoundVolUI (final boolean flag)
Set the flag for redrawing of the UI of the sound volume.
synchronized boolean shouldBeRedrawnSoundVolUI ()
Should the UI of the sound volume be redrawn.
void clrDesktopsData ()
Clear the list of desktops data.
abstract void connectToNetByDialog ()
Connect to a network by opening dialog for user selection.
void onItemSelected (AdapterView<?> parent, View view, int pos, long id)
If an item of the desktops names drop box selected the volume percent of the selected desktop should be set.
void onNothingSelected (AdapterView<?> arg0)
Not used.
Static Public Attributes
static String NAMES_DATA_FILE_NAME = "wifi.data"
The name of the file for saving desktops datas.
Static Public Attributes inherited from com.soundroid.ui.UI
static final String FILE_NAME = "file_name"
static final String DESKTOPS_DATA = "DESKTOPS_DATA"
static final int EDIT_DESKTOP_NAME = 1
The selected action in the activity.
static final String SINGLE_DESKTOP_DATA = "DESKTOP_DATA"
static final int REQUEST_CODE_EDIT = 1
The request code for a selected action.
static final String IS_DEFAULT = "IS_DEFAULT"
static NetConnector connector
The network connector instance.
Protected Member Functions
void saveCurConnectionType ()
Save the ID of the checked radio button 'Connection type'.
void fillDesktopsListFromFile (final String fileName) throws IOException
Fill the list of desktops names by the data from file.
void initConnectionTypeRadioButt ()
Initialize the radio button for selecting connection type wifi.
void initNewButt ()
Initialization of the button 'New'.
void reInitConnector ()
Re-initialize the wifi connector.
void initEditButt ()
Initialisation of the button 'Edit'.
Protected Member Functions inherited from com.soundroid.ui.UI
void saveDesktopsDatas (String fileName)
Save the txt_view_item of desktops' datas.
abstract void saveCurConnectionType ()
Save current connection type.
abstract void fillDesktopsListFromFile (final String fileName) throws IOException
Fill the list of desktops datas from file.
void initDesktopsDatasFromFile (final String fileName)
Initialization of the desktops data from file.
abstract void initConnectionTypeRadioButt ()
Initialize the radio button of connection type.
abstract void setVolumeUI ()
Set the UI of sound volume.
void showOkDialog (String txt)
Show a dialog with the given text and the button 'OK'.
void enableVolumeSeekBar ()
Enable the seek bar for changing volume.
void setVolumeUiElements ()
Set values for the elements of the Volume UI(mute/unmute button, volume seekbar, etc)
abstract void initNewButt ()
Initialize the 'New' button.
abstract void initEditButt ()
Initialize the 'Edit' button.
boolean isDesktopDataDefault (final String name)
Check whether the desktop with the given name is default.
DesktopData getDesktopDataByName (final String name)
Get the desktop's data by the given name.
void removeCurrentlyEditedDesktopData ()
Remove the currently edited desktop data.
abstract void reInitConnector ()
Re-initialize connection to a network.
Private Member Functions
WifiUI ()
void openConnectingActivity (final DesktopData desktopData)
Open the activity of connecting to the remote desktop.
void openEditDesktopNameActivity (final int actionType)
Open the activity for editing the selected desktop name.
void chgCurrentlyEditedDesktopData (final String dataStr, final boolean setDefault)
Change the currently edited desktop data.
Private Attributes
String TAG = "WifiUI"
The tag for logs.
Additional Inherited Members
Static Public Member Functions inherited from com.soundroid.ui.UI
static UI buildUiFromFile (final Activity activity) throws IOException, NumberFormatException
Initialization from file the radio button 'Connection type' checked at previous session.
Protected Attributes inherited from com.soundroid.ui.UI
Context context
The application's context.
MuteButton muteButt
The button for muting volume.
Button buttEdit
RadioGroup connectionTypeRadio
The radio buttons group for connection types.
Spinner desktopsNames
The drop box of the desktops names for connecting.
SeekBar volume
The seek bar for changing volume in percents.
List< DesktopData > desktopsDatas
The txt_view_item of desktops data.
final int NO_EDIT = -1
int curEditedDesktopNameInd = NO_EDIT
The selected desktop name on the spinner at the time of clicking on the button 'Edit'.
int curSelectedDesktopNameInd = 0
Currently selected desktop name on the spinner.
boolean host_connection_checked = false
The connection to the currently selected desktop's host has checked.
boolean redraw = false
The activity should be redrawn.
boolean redrawSoundVolUI = false
The part of UI for controlling sound volume should be redrawn.
Activity activity
The current activity instance.
Static Protected Attributes inherited from com.soundroid.ui.UI
static String CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME = "conn_type"
The name of the file containing the ID of the connection type radio button selected at last session.
Detailed Description
UI for connecting by wifi.
Definition at line 55 of file WifiUI.java.
Constructor & Destructor Documentation
com.soundroid.ui.wifi.WifiUI.WifiUI () inline private
Definition at line 61 of file WifiUI.java.
com.soundroid.ui.wifi.WifiUI.WifiUI (final Activity activity) inline
Constructor.
Parameters
activity The main activity
Definition at line 67 of file WifiUI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.connector, com.soundroid.ui.UI.context, com.soundroid.ui.UI.host_connection_checked, and com.soundroid.ui.wifi.WifiUI.TAG.
Member Function Documentation
void com.soundroid.ui.wifi.WifiUI.chgCurrentlyEditedDesktopData (final String dataStr, final boolean setDefault) inline private
Change the currently edited desktop data.
Parameters
dataStr The string of a new desktop data
setDefault true The being changed desktop should be signed as default
Definition at line 193 of file WifiUI.java.
References com.soundroid.ui.UI.curEditedDesktopNameInd, com.soundroid.ui.UI.curSelectedDesktopNameInd, com.soundroid.ui.UI.NO_EDIT, com.soundroid.ui.wifi.WifiUI.saveDesktopsDatas(), and com.soundroid.ui.wifi.WifiUI.TAG.
Referenced by com.soundroid.ui.wifi.WifiUI.processActivityResult().
void com.soundroid.ui.wifi.WifiUI.connectToNetByDialog () inline
Turning on wifi connection by opening dialog 'Wifi permission request' for user.
Definition at line 257 of file WifiUI.java.
void com.soundroid.ui.wifi.WifiUI.fillDesktopsListFromFile (final String fileName) throws IOException inline protected
Fill the list of desktops names by the data from file.
Parameters
fileName The name of the file
Exceptions
IOException
Definition at line 97 of file WifiUI.java.
References com.soundroid.ui.UI.context.
void com.soundroid.ui.wifi.WifiUI.initConnectionTypeRadioButt () inline protected
Initialize the radio button for selecting connection type wifi.
Definition at line 108 of file WifiUI.java.
References com.soundroid.ui.UI.activity.
void com.soundroid.ui.wifi.WifiUI.initDesktopsDatasFromFile () inline
Initialize desktops data from file.
Definition at line 176 of file WifiUI.java.
References com.soundroid.ui.wifi.WifiUI.NAMES_DATA_FILE_NAME.
void com.soundroid.ui.wifi.WifiUI.initEditButt () inline protected
Initialisation of the button 'Edit'.
Definition at line 305 of file WifiUI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.buttEdit, com.soundroid.ui.UI.desktopsDatas, com.soundroid.ui.UI.EDIT_DESKTOP_NAME, and com.soundroid.ui.wifi.WifiUI.openEditDesktopNameActivity().
void com.soundroid.ui.wifi.WifiUI.initNewButt () inline protected
Initialization of the button 'New'.
Definition at line 161 of file WifiUI.java.
References com.soundroid.ui.UI.activity, and com.soundroid.ui.wifi.WifiUI.openEditDesktopNameActivity().
void com.soundroid.ui.wifi.WifiUI.openConnectingActivity (final DesktopData desktopData) inline private
Open the activity of connecting to the remote desktop.
Parameters
desktopData The data of the desktop which connecting to
Definition at line 118 of file WifiUI.java.
References com.soundroid.ui.UI.context, and com.soundroid.ui.UI.DESKTOPS_DATA.
Referenced by com.soundroid.ui.wifi.WifiUI.setVolumeUI().
void com.soundroid.ui.wifi.WifiUI.openEditDesktopNameActivity (final int actionType) inline private
Open the activity for editing the selected desktop name.
Parameters
actionType The type of editing(editing, adding new or deleting)
Definition at line 129 of file WifiUI.java.
References com.soundroid.ui.UI.context, com.soundroid.ui.UI.curEditedDesktopNameInd, com.soundroid.ui.UI.DESKTOPS_DATA, com.soundroid.ui.UI.FILE_NAME, com.soundroid.ui.UI.getDesktopDataByName(), com.soundroid.ui.UI.IS_DEFAULT, com.soundroid.ui.UI.isDesktopDataDefault(), com.soundroid.ui.wifi.WifiUI.NAMES_DATA_FILE_NAME, com.soundroid.ui.UI.NO_EDIT, com.soundroid.ui.UI.REQUEST_CODE_EDIT, and com.soundroid.ui.wifi.WifiUI.TAG.
Referenced by com.soundroid.ui.wifi.WifiUI.initEditButt(), and com.soundroid.ui.wifi.WifiUI.initNewButt().
void com.soundroid.ui.wifi.WifiUI.processActivityResult (final int requestCode, final Intent data) inline
Definition at line 219 of file WifiUI.java.
References com.soundroid.ui.wifi.WifiUI.chgCurrentlyEditedDesktopData(), com.soundroid.ui.UI.curEditedDesktopNameInd, com.soundroid.ui.UI.host_connection_checked, com.soundroid.ui.UI.IS_DEFAULT, com.soundroid.ui.UI.NO_EDIT, com.soundroid.ui.UI.redraw, com.soundroid.ui.UI.redrawSoundVolUI, com.soundroid.ui.UI.removeCurrentlyEditedDesktopData(), com.soundroid.ui.UI.REQUEST_CODE_EDIT, com.soundroid.ui.wifi.WifiUI.saveDesktopsDatas(), com.soundroid.ui.UI.SINGLE_DESKTOP_DATA, and com.soundroid.ui.wifi.WifiUI.TAG.
void com.soundroid.ui.wifi.WifiUI.reInitConnector () inline protected
Re-initialize the wifi connector.
Definition at line 265 of file WifiUI.java.
References com.soundroid.ui.UI.connector.
void com.soundroid.ui.wifi.WifiUI.saveCurConnectionType () inline protected
Save the ID of the checked radio button 'Connection type'.
Definition at line 80 of file WifiUI.java.
References com.soundroid.ui.UI.CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME, com.soundroid.ui.UI.context, and com.soundroid.ui.wifi.WifiUI.TAG.
void com.soundroid.ui.wifi.WifiUI.saveDesktopsDatas () inline
Save desktops data to file.
Definition at line 184 of file WifiUI.java.
References com.soundroid.ui.wifi.WifiUI.NAMES_DATA_FILE_NAME.
Referenced by com.soundroid.ui.wifi.WifiUI.chgCurrentlyEditedDesktopData(), and com.soundroid.ui.wifi.WifiUI.processActivityResult().
void com.soundroid.ui.wifi.WifiUI.setVolumeUI () inline
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
Definition at line 280 of file WifiUI.java.
References com.soundroid.ui.UI.connector, com.soundroid.ui.UI.curSelectedDesktopNameInd, com.soundroid.net.DesktopData.getName(), com.soundroid.ui.UI.host_connection_checked, com.soundroid.net.NetConnector.isConnectedToDaemon(), com.soundroid.ui.wifi.WifiUI.openConnectingActivity(), com.soundroid.ui.UI.setVolumeUiElements(), and com.soundroid.ui.UI.showOkDialog().
Field Documentation
String com.soundroid.ui.wifi.WifiUI.NAMES_DATA_FILE_NAME = "wifi.data" static
The name of the file for saving desktops datas.
Definition at line 59 of file WifiUI.java.
Referenced by com.soundroid.ui.wifi.WifiUI.initDesktopsDatasFromFile(), com.soundroid.ui.wifi.WifiUI.openEditDesktopNameActivity(), and com.soundroid.ui.wifi.WifiUI.saveDesktopsDatas().
String com.soundroid.ui.wifi.WifiUI.TAG = "WifiUI" private
The tag for logs.
Definition at line 57 of file WifiUI.java.
Referenced by com.soundroid.ui.wifi.WifiUI.chgCurrentlyEditedDesktopData(), com.soundroid.ui.wifi.WifiUI.openEditDesktopNameActivity(), com.soundroid.ui.wifi.WifiUI.processActivityResult(), com.soundroid.ui.wifi.WifiUI.saveCurConnectionType(), and com.soundroid.ui.wifi.WifiUI.WifiUI().
The documentation for this class was generated from the following file:
WifiUI.java