SounDroid: com.soundroid.ui.UI.MuteButton Class Reference
com.soundroid.ui.UI.MuteButton Class Reference
Class of the button for changing volume states: mute, unmute.
Public Member Functions
MuteButton ()
Constructor for initializing the button and its state.
void setEnabled (final boolean enabled)
Set the button enabled or disabled.
void setShownMuted (final boolean muted)
Set the button's background image depending on the given state.
Private Member Functions
void init ()
Initialize the button.
View.OnClickListener getMuteButtOnClickListener ()
Private Attributes
Button butt
The button instance.
boolean shownMuted = false
The button shown as muted.
Detailed Description
Class of the button for changing volume states: mute, unmute.
Definition at line 520 of file UI.java.
Constructor & Destructor Documentation
com.soundroid.ui.UI.MuteButton.MuteButton () inline
Constructor for initializing the button and its state.
Definition at line 528 of file UI.java.
References com.soundroid.ui.UI.activity, com.soundroid.ui.UI.MuteButton.butt, and com.soundroid.ui.UI.MuteButton.init().
Member Function Documentation
View.OnClickListener com.soundroid.ui.UI.MuteButton.getMuteButtOnClickListener () inline private
Definition at line 568 of file UI.java.
References com.soundroid.ui.UI.connector, com.soundroid.net.NetConnector.sendMuteState(), com.soundroid.ui.UI.MuteButton.setShownMuted(), com.soundroid.ui.UI.MuteButton.shownMuted, and com.soundroid.ui.UI.TAG.
Referenced by com.soundroid.ui.UI.MuteButton.init().
void com.soundroid.ui.UI.MuteButton.init () inline private
Initialize the button.
Definition at line 563 of file UI.java.
References com.soundroid.ui.UI.MuteButton.getMuteButtOnClickListener().
Referenced by com.soundroid.ui.UI.MuteButton.MuteButton().
void com.soundroid.ui.UI.MuteButton.setEnabled (final boolean enabled) inline
Set the button enabled or disabled.
Parameters
enabled To enable the button
Definition at line 537 of file UI.java.
void com.soundroid.ui.UI.MuteButton.setShownMuted (final boolean muted) inline
Set the button's background image depending on the given state.
Parameters
muted The state of the button
Definition at line 545 of file UI.java.
References com.soundroid.ui.UI.MuteButton.butt, com.soundroid.ui.UI.enableVolumeSeekBar(), and com.soundroid.ui.UI.MuteButton.shownMuted.
Referenced by com.soundroid.ui.UI.MuteButton.getMuteButtOnClickListener().
Field Documentation
Button com.soundroid.ui.UI.MuteButton.butt private
The button instance.
Definition at line 522 of file UI.java.
Referenced by com.soundroid.ui.UI.MuteButton.MuteButton(), and com.soundroid.ui.UI.MuteButton.setShownMuted().
boolean com.soundroid.ui.UI.MuteButton.shownMuted = false private
The button shown as muted.
Definition at line 523 of file UI.java.
Referenced by com.soundroid.ui.UI.MuteButton.getMuteButtOnClickListener(), and com.soundroid.ui.UI.MuteButton.setShownMuted().
The documentation for this class was generated from the following file:
UI.java