SounDroid: com.soundroid.ui.bluetooth.BlueToothConnectingActivity Class Reference
com.soundroid.ui.bluetooth.BlueToothConnectingActivity Class Reference
The activity of connecting to a remote soundroid daemon by blue tooth.
Inherits Activity.
Public Member Functions
void onBackPressed ()
Static Public Attributes
static final String CONNECTED_DEV_NAME = "Device_Name_For_Connecting"
static final String IS_REMOTE_DEV_FOUND = "Is_remote_dev_found"
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
Runnable getConnection (final String connectedDevName)
Connect to desktop with the given name.
Intent getIntentWithReachabilityOfDev (final String devName)
Get the intent containing the result of connection to a remote desktop.
Static Private Attributes
static final String TAG = "BTConnectingActivity"
The tag for writing to log.
Detailed Description
The activity of connecting to a remote soundroid daemon by blue tooth.
Definition at line 49 of file BlueToothConnectingActivity.java.
Member Function Documentation
Runnable com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getConnection (final String connectedDevName) inline private
Connect to desktop with the given name.
Parameters
connectedDevName The name of the desktop
Returns
The runnable instance of the function
Definition at line 89 of file BlueToothConnectingActivity.java.
References com.soundroid.ui.UI.connector, com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getIntentWithReachabilityOfDev(), and com.soundroid.ui.bluetooth.BlueToothConnectingActivity.TAG.
Referenced by com.soundroid.ui.bluetooth.BlueToothConnectingActivity.onCreate().
Intent com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getIntentWithReachabilityOfDev (final String devName) inline private
Get the intent containing the result of connection to a remote desktop.
Parameters
devName The name of the desktop(device)
Returns
The intent instance
Definition at line 111 of file BlueToothConnectingActivity.java.
References com.soundroid.ui.bluetooth.BlueToothConnectingActivity.IS_REMOTE_DEV_FOUND, and com.soundroid.ui.bluetooth.BlueToothConnectingActivity.TAG.
Referenced by com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getConnection().
void com.soundroid.ui.bluetooth.BlueToothConnectingActivity.onBackPressed () inline
Definition at line 79 of file BlueToothConnectingActivity.java.
void com.soundroid.ui.bluetooth.BlueToothConnectingActivity.onCreate (Bundle savedInstanceState) inline protected
Definition at line 57 of file BlueToothConnectingActivity.java.
References com.soundroid.ui.bluetooth.BlueToothConnectingActivity.CONNECTED_DEV_NAME, com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getConnection(), and com.soundroid.ui.bluetooth.BlueToothConnectingActivity.TAG.
Field Documentation
final String com.soundroid.ui.bluetooth.BlueToothConnectingActivity.CONNECTED_DEV_NAME = "Device_Name_For_Connecting" static
Definition at line 52 of file BlueToothConnectingActivity.java.
Referenced by com.soundroid.ui.bluetooth.BlueToothConnectingActivity.onCreate(), and com.soundroid.ui.bluetooth.BluetoothUI.openConnectingActivity().
final String com.soundroid.ui.bluetooth.BlueToothConnectingActivity.IS_REMOTE_DEV_FOUND = "Is_remote_dev_found" static
Definition at line 53 of file BlueToothConnectingActivity.java.
Referenced by com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getIntentWithReachabilityOfDev(), and com.soundroid.ui.bluetooth.BluetoothUI.processActivityResult().
final String com.soundroid.ui.bluetooth.BlueToothConnectingActivity.TAG = "BTConnectingActivity" static private
The tag for writing to log.
Definition at line 50 of file BlueToothConnectingActivity.java.
Referenced by com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getConnection(), com.soundroid.ui.bluetooth.BlueToothConnectingActivity.getIntentWithReachabilityOfDev(), and com.soundroid.ui.bluetooth.BlueToothConnectingActivity.onCreate().
The documentation for this class was generated from the following file:
BlueToothConnectingActivity.java