SounDroid: com.android.net.NetConnector Class Reference
com.android.net.NetConnector Class Reference
Network connector initializes connection to the given IP address and port sends and receives given strings by the established connection.
Inherits Serializable.
Public Member Functions
NetConnector ()
Constructor.
void connect (String ip, String port) throws IOException
Connects to the given IP and port.
boolean isReachable (String ip)
Checks is the given IP reachable by network.
String getCurVol ()
Get the current sound's volume on the connected desktop.
boolean sendMuteState (final boolean mute)
Send the command for mute or unmute the sound's system on the connected desktop.
void sendEnd ()
Send the command for end connection.
void closeConnection ()
Close the connection to the connected desktoop.
boolean sendChgVol (final int vol)
Send the command for changing sound's volume at the connected desktop to the given percent.
boolean isConnected ()
Is the connection to the remote desktop established?
boolean handShake ()
Send hello to the connected desktop and get hello from it.
boolean isMuted ()
Is the sound volume of the connected desktop muted?
Private Member Functions
void sendStr (String str) throws IOException
Send the given string to the connected desktop.
String receiveStr () throws IOException
Receive a string from the connected desktop.
Private Attributes
String TAG = "DistanceVolume.NetConnector"
The tag for writing to log.
Socket socket = null
The socket's instance.
OutputStream outStream = null
The output stream instance.
DataOutputStream dataOutStream = null
The data output stream instance.
InputStream inStream = null
The input stream instance.
DataInputStream dataInStream = null
The data input stream instance.
InetSocketAddress addr
The network address for connecting.
String macAddrStr = ""
The string of a MAC address.
boolean connected = false
Is the connection estableshed?
Static Private Attributes
static final long serialVersionUID = 2L
static final int TIME_OUT = 10000
Connection's time out in milliseconds.
Detailed Description
Network connector initializes connection to the given IP address and port sends and receives given strings by the established connection.
Definition at line 47 of file NetConnector.java.
Constructor & Destructor Documentation
com.android.net.NetConnector.NetConnector () inline
Constructor.
Definition at line 71 of file NetConnector.java.
References com.android.net.NetConnector.socket.
Member Function Documentation
void com.android.net.NetConnector.closeConnection () inline
Close the connection to the connected desktoop.
Definition at line 188 of file NetConnector.java.
References com.android.net.NetConnector.dataInStream, com.android.net.NetConnector.dataOutStream, com.android.net.NetConnector.inStream, com.android.net.NetConnector.outStream, com.android.net.NetConnector.socket, and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onDestroy(), and com.android.ui.DistanceVolumeActivity.onStop().
void com.android.net.NetConnector.connect (String ip, String port) throws IOException inline
Connects to the given IP and port.
Parameters
ip The IP for connecting
port The port number
Exceptions
IOException
Definition at line 81 of file NetConnector.java.
References com.android.net.NetConnector.addr, com.android.net.NetConnector.connected, com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.socket, com.android.net.NetConnector.TAG, and com.android.net.NetConnector.TIME_OUT.
Referenced by com.android.ui.ConnectingActivity.getConnection().
String com.android.net.NetConnector.getCurVol () inline
Get the current sound's volume on the connected desktop.
Returns
The string of the sound's volume in percents
Definition at line 119 of file NetConnector.java.
References com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar().
boolean com.android.net.NetConnector.handShake () inline
Send hello to the connected desktop and get hello from it.
Returns
true The handshake has made successfully
Definition at line 281 of file NetConnector.java.
References com.android.net.NetConnector.connected, com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.ConnectingActivity.getConnection().
boolean com.android.net.NetConnector.isConnected () inline
Is the connection to the remote desktop established?
Returns
true The connection established
Definition at line 273 of file NetConnector.java.
References com.android.net.NetConnector.connected.
Referenced by com.android.ui.DistanceVolumeActivity.onBackPressed(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
boolean com.android.net.NetConnector.isMuted () inline
Is the sound volume of the connected desktop muted?
Returns
true The desktop muted
Definition at line 301 of file NetConnector.java.
References com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.setVolumeUI().
boolean com.android.net.NetConnector.isReachable (String ip) inline
Checks is the given IP reachable by network.
Parameters
ip The IP for checking
Returns
true The IP is reachable
Definition at line 99 of file NetConnector.java.
References com.android.net.NetConnector.TAG, and com.android.net.NetConnector.TIME_OUT.
Referenced by com.android.ui.ConnectingActivity.getConnection().
String com.android.net.NetConnector.receiveStr () throws IOException inline private
Receive a string from the connected desktop.
Returns
The received string
Exceptions
IOException
Definition at line 243 of file NetConnector.java.
References com.android.net.NetConnector.dataInStream, com.android.net.NetConnector.inStream, com.android.net.NetConnector.socket, and com.android.net.NetConnector.TAG.
Referenced by com.android.net.NetConnector.getCurVol(), com.android.net.NetConnector.handShake(), com.android.net.NetConnector.isMuted(), com.android.net.NetConnector.sendChgVol(), and com.android.net.NetConnector.sendMuteState().
boolean com.android.net.NetConnector.sendChgVol (final int vol) inline
Send the command for changing sound's volume at the connected desktop to the given percent.
Parameters
vol The volume in percents
Returns
true The volume has been changed successfully
Definition at line 259 of file NetConnector.java.
References com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.initVolumeSeekBar().
void com.android.net.NetConnector.sendEnd () inline
Send the command for end connection.
Definition at line 164 of file NetConnector.java.
References com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onBackPressed(), and com.android.ui.DistanceVolumeActivity.onDestroy().
boolean com.android.net.NetConnector.sendMuteState (final boolean mute) inline
Send the command for mute or unmute the sound's system on the connected desktop.
Parameters
mute The mute or unmute state should be sent
Returns
true The command was sent and executed successfully
Definition at line 144 of file NetConnector.java.
References com.android.net.NetConnector.macAddrStr, com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendStr(), and com.android.net.NetConnector.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.MuteButton.init().
void com.android.net.NetConnector.sendStr (String str) throws IOException inline private
Send the given string to the connected desktop.
Parameters
str The string for sending
Exceptions
IOException
Definition at line 177 of file NetConnector.java.
References com.android.net.NetConnector.dataOutStream, com.android.net.NetConnector.outStream, com.android.net.NetConnector.socket, and com.android.net.NetConnector.TAG.
Referenced by com.android.net.NetConnector.getCurVol(), com.android.net.NetConnector.handShake(), com.android.net.NetConnector.isMuted(), com.android.net.NetConnector.sendChgVol(), com.android.net.NetConnector.sendEnd(), and com.android.net.NetConnector.sendMuteState().
Field Documentation
InetSocketAddress com.android.net.NetConnector.addr private
The network address for connecting.
Definition at line 63 of file NetConnector.java.
Referenced by com.android.net.NetConnector.connect().
boolean com.android.net.NetConnector.connected = false private
Is the connection estableshed?
Definition at line 66 of file NetConnector.java.
Referenced by com.android.net.NetConnector.connect(), com.android.net.NetConnector.handShake(), and com.android.net.NetConnector.isConnected().
DataInputStream com.android.net.NetConnector.dataInStream = null private
The data input stream instance.
Definition at line 61 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), and com.android.net.NetConnector.receiveStr().
DataOutputStream com.android.net.NetConnector.dataOutStream = null private
The data output stream instance.
Definition at line 58 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), and com.android.net.NetConnector.sendStr().
InputStream com.android.net.NetConnector.inStream = null private
The input stream instance.
Definition at line 60 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), and com.android.net.NetConnector.receiveStr().
String com.android.net.NetConnector.macAddrStr = "" private
The string of a MAC address.
Definition at line 64 of file NetConnector.java.
Referenced by com.android.net.NetConnector.connect(), com.android.net.NetConnector.getCurVol(), com.android.net.NetConnector.handShake(), com.android.net.NetConnector.isMuted(), com.android.net.NetConnector.sendChgVol(), com.android.net.NetConnector.sendEnd(), and com.android.net.NetConnector.sendMuteState().
OutputStream com.android.net.NetConnector.outStream = null private
The output stream instance.
Definition at line 57 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), and com.android.net.NetConnector.sendStr().
final long com.android.net.NetConnector.serialVersionUID = 2L static private
Definition at line 49 of file NetConnector.java.
Socket com.android.net.NetConnector.socket = null private
The socket's instance.
Definition at line 55 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), com.android.net.NetConnector.connect(), com.android.net.NetConnector.NetConnector(), com.android.net.NetConnector.receiveStr(), and com.android.net.NetConnector.sendStr().
String com.android.net.NetConnector.TAG = "DistanceVolume.NetConnector" private
The tag for writing to log.
Definition at line 53 of file NetConnector.java.
Referenced by com.android.net.NetConnector.closeConnection(), com.android.net.NetConnector.connect(), com.android.net.NetConnector.getCurVol(), com.android.net.NetConnector.handShake(), com.android.net.NetConnector.isMuted(), com.android.net.NetConnector.isReachable(), com.android.net.NetConnector.receiveStr(), com.android.net.NetConnector.sendChgVol(), com.android.net.NetConnector.sendEnd(), com.android.net.NetConnector.sendMuteState(), and com.android.net.NetConnector.sendStr().
final int com.android.net.NetConnector.TIME_OUT = 10000 static private
Connection's time out in milliseconds.
Definition at line 51 of file NetConnector.java.
Referenced by com.android.net.NetConnector.connect(), and com.android.net.NetConnector.isReachable().
The documentation for this class was generated from the following file:
NetConnector.java