SounDroid: com.android.ui.EditDesktopDataActivity Class Reference
com.android.ui.EditDesktopDataActivity Class Reference
Activity for editing a desktop's data.
Inherits Activity.
Public Member Functions
void onCreate (Bundle savedInstanceState)
Getting the desktop data should be edited from the main activity Initializing UI.
Static Public Attributes
static String ACTION_TYPE = "ACTION_TYPE"
static final int ACTION_DEL = 1
Private Member Functions
void initUI (final DesktopData desktopData, final boolean isDefault)
Initialization of UI elements by the given desktop data.
void initIpEditTxtFields (String ip[], final EditText lastFocusedEditBox)
Initialization of the IP field.
void initButtons ()
Initialize buttons.
void initOkButt ()
Initialize the button OK.
void initCancelButt ()
Initialize the button Cancel.
void initDelButt ()
Initialize the button Delete.
String getDataFromUI ()
Get data from UI in a string form.
boolean isNameUsed (String name)
Check is the given name is already used by some desktop?
boolean isIpUsed (String ip)
Is the given IP is already used by some desktop?
Static Private Member Functions
static TextWatcher getTxtWatcherForEditTxt (final EditText editTxtShouldBeFocused, final int lastPosBeforeRefocus)
Text watcher for edit text.
Private Attributes
EditText ipEditTxtArr []
The array of edit text fields for editing IP.
EditText portEditTxt
The field for editing port number.
EditText nameEditTxt
The field for editing desktop's name.
CheckBox defaultChkBox
The check box for checking the currently edited desktop as the first within the drop box of desktop names at the main activity.
Button buttOK
ArrayList< String > existingDesktopsDatasStrs
The string, containing the data about the known desktops.
DesktopData editedDesktopData = null
The desktop data should be edited, and given from the main activity.
final int NO_INDEX = -1
No index selected in the drop box.
int editedDesktopDataIndex = NO_INDEX
The index of the currenty selected desktop data from the drop box /* of the main activity.
Static Private Attributes
static final String TAG = "EditDesktopNameActivity"
The tag for writing to log.
Detailed Description
Activity for editing a desktop's data.
Definition at line 55 of file EditDesktopDataActivity.java.
Member Function Documentation
String com.android.ui.EditDesktopDataActivity.getDataFromUI () inline private
Get data from UI in a string form.
Returns
The string which is the data from UI
Definition at line 268 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.ipEditTxtArr, com.android.ui.EditDesktopDataActivity.isIpUsed(), com.android.ui.EditDesktopDataActivity.isNameUsed(), com.android.ui.EditDesktopDataActivity.nameEditTxt, com.android.ui.EditDesktopDataActivity.portEditTxt, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.initOkButt().
static TextWatcher com.android.ui.EditDesktopDataActivity.getTxtWatcherForEditTxt (final EditText editTxtShouldBeFocused, final int lastPosBeforeRefocus) inline static private
Text watcher for edit text.
When the editing within the current edit text has finished and the cursor within the current edit box is at the last position, the focus will be moved to the next given edit box
Parameters
editTxtShouldBeFocused The edit text should be focused after the current edit box
lastPosBeforeRefocus The last position within the currently edited box
Returns
The text watcher instance
Definition at line 167 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initIpEditTxtFields().
void com.android.ui.EditDesktopDataActivity.initButtons () inline private
Initialize buttons.
Definition at line 185 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.initCancelButt(), com.android.ui.EditDesktopDataActivity.initDelButt(), and com.android.ui.EditDesktopDataActivity.initOkButt().
Referenced by com.android.ui.EditDesktopDataActivity.initUI().
void com.android.ui.EditDesktopDataActivity.initCancelButt () inline private
Initialize the button Cancel.
Definition at line 223 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.ACTION_TYPE, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.initButtons().
void com.android.ui.EditDesktopDataActivity.initDelButt () inline private
Initialize the button Delete.
Definition at line 244 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.ACTION_DEL, com.android.ui.EditDesktopDataActivity.ACTION_TYPE, com.android.ui.EditDesktopDataActivity.editedDesktopData, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, com.android.net.DesktopData.isEmpty(), com.android.ui.EditDesktopDataActivity.nameEditTxt, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.initButtons().
void com.android.ui.EditDesktopDataActivity.initIpEditTxtFields (String ip[], final EditText lastFocusedEditBox) inline private
Initialization of the IP field.
Parameters
ip The array of IP address
lastFocusedEditBox The edit box will be focused automatically after the editing this field
Definition at line 131 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.getTxtWatcherForEditTxt(), com.android.ui.EditDesktopDataActivity.ipEditTxtArr, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.initUI().
void com.android.ui.EditDesktopDataActivity.initOkButt () inline private
Initialize the button OK.
Definition at line 194 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.ACTION_TYPE, com.android.ui.EditDesktopDataActivity.buttOK, com.android.ui.EditDesktopDataActivity.defaultChkBox, com.android.ui.DistanceVolumeActivity.DESKTOP_DATA, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, com.android.ui.EditDesktopDataActivity.getDataFromUI(), com.android.ui.DistanceVolumeActivity.IS_DEFAULT, com.android.ui.EditDesktopDataActivity.nameEditTxt, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.initButtons().
void com.android.ui.EditDesktopDataActivity.initUI (final DesktopData desktopData, final boolean isDefault) inline private
Initialization of UI elements by the given desktop data.
Parameters
desktopData The desktop data should be edited
isDefault Is the given desktop should be default in the drop box of the main activity?
Definition at line 111 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.defaultChkBox, com.android.net.DesktopData.getIpArr(), com.android.net.DesktopData.getName(), com.android.net.DesktopData.getPort(), com.android.ui.EditDesktopDataActivity.initButtons(), com.android.ui.EditDesktopDataActivity.initIpEditTxtFields(), com.android.ui.EditDesktopDataActivity.nameEditTxt, and com.android.ui.EditDesktopDataActivity.portEditTxt.
Referenced by com.android.ui.EditDesktopDataActivity.onCreate().
boolean com.android.ui.EditDesktopDataActivity.isIpUsed (String ip) inline private
Is the given IP is already used by some desktop?
Parameters
ip The checked IP
Returns
true The IP is used
Definition at line 333 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.editedDesktopDataIndex, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI().
boolean com.android.ui.EditDesktopDataActivity.isNameUsed (String name) inline private
Check is the given name is already used by some desktop?
Parameters
name The checked name
Returns
true The name is used
Definition at line 311 of file EditDesktopDataActivity.java.
References com.android.ui.EditDesktopDataActivity.editedDesktopDataIndex, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, and com.android.ui.EditDesktopDataActivity.TAG.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI().
void com.android.ui.EditDesktopDataActivity.onCreate (Bundle savedInstanceState) inline
Getting the desktop data should be edited from the main activity Initializing UI.
Definition at line 81 of file EditDesktopDataActivity.java.
References com.android.net.DesktopData.buildEmptyDesktopData(), com.android.ui.EditDesktopDataActivity.editedDesktopData, com.android.ui.EditDesktopDataActivity.editedDesktopDataIndex, com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs, com.android.ui.DistanceVolumeActivity.EXTRA_ACTION_TYPE, com.android.others.FileUtils.getLinesFromFile(), com.android.ui.EditDesktopDataActivity.initUI(), com.android.ui.DistanceVolumeActivity.IS_DEFAULT, com.android.ui.DistanceVolumeActivity.NAMES_DATA_FILE_NAME, com.android.ui.EditDesktopDataActivity.TAG, and com.android.net.DesktopData.toString().
Field Documentation
final int com.android.ui.EditDesktopDataActivity.ACTION_DEL = 1 static
Definition at line 59 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initDelButt(), and com.android.ui.DistanceVolumeActivity.onActivityResult().
String com.android.ui.EditDesktopDataActivity.ACTION_TYPE = "ACTION_TYPE" static
Definition at line 58 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initCancelButt(), com.android.ui.EditDesktopDataActivity.initDelButt(), com.android.ui.EditDesktopDataActivity.initOkButt(), and com.android.ui.DistanceVolumeActivity.onActivityResult().
Button com.android.ui.EditDesktopDataActivity.buttOK private
Definition at line 67 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initOkButt().
CheckBox com.android.ui.EditDesktopDataActivity.defaultChkBox private
The check box for checking the currently edited desktop as the first within the drop box of desktop names at the main activity.
Definition at line 65 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initOkButt(), and com.android.ui.EditDesktopDataActivity.initUI().
DesktopData com.android.ui.EditDesktopDataActivity.editedDesktopData = null private
The desktop data should be edited, and given from the main activity.
Definition at line 71 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initDelButt(), and com.android.ui.EditDesktopDataActivity.onCreate().
int com.android.ui.EditDesktopDataActivity.editedDesktopDataIndex = NO_INDEX private
The index of the currenty selected desktop data from the drop box /* of the main activity.
Definition at line 73 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.isIpUsed(), com.android.ui.EditDesktopDataActivity.isNameUsed(), and com.android.ui.EditDesktopDataActivity.onCreate().
ArrayList<String> com.android.ui.EditDesktopDataActivity.existingDesktopsDatasStrs private
The string, containing the data about the known desktops.
Definition at line 69 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initCancelButt(), com.android.ui.EditDesktopDataActivity.initDelButt(), com.android.ui.EditDesktopDataActivity.initOkButt(), com.android.ui.EditDesktopDataActivity.isIpUsed(), com.android.ui.EditDesktopDataActivity.isNameUsed(), and com.android.ui.EditDesktopDataActivity.onCreate().
EditText com.android.ui.EditDesktopDataActivity.ipEditTxtArr[] private
The array of edit text fields for editing IP.
Definition at line 61 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI(), and com.android.ui.EditDesktopDataActivity.initIpEditTxtFields().
EditText com.android.ui.EditDesktopDataActivity.nameEditTxt private
The field for editing desktop's name.
Definition at line 63 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI(), com.android.ui.EditDesktopDataActivity.initDelButt(), com.android.ui.EditDesktopDataActivity.initOkButt(), and com.android.ui.EditDesktopDataActivity.initUI().
final int com.android.ui.EditDesktopDataActivity.NO_INDEX = -1 private
No index selected in the drop box.
Definition at line 72 of file EditDesktopDataActivity.java.
EditText com.android.ui.EditDesktopDataActivity.portEditTxt private
The field for editing port number.
Definition at line 62 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI(), and com.android.ui.EditDesktopDataActivity.initUI().
final String com.android.ui.EditDesktopDataActivity.TAG = "EditDesktopNameActivity" static private
The tag for writing to log.
Definition at line 56 of file EditDesktopDataActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.getDataFromUI(), com.android.ui.EditDesktopDataActivity.initCancelButt(), com.android.ui.EditDesktopDataActivity.initDelButt(), com.android.ui.EditDesktopDataActivity.initIpEditTxtFields(), com.android.ui.EditDesktopDataActivity.initOkButt(), com.android.ui.EditDesktopDataActivity.isIpUsed(), com.android.ui.EditDesktopDataActivity.isNameUsed(), and com.android.ui.EditDesktopDataActivity.onCreate().
The documentation for this class was generated from the following file:
EditDesktopDataActivity.java