SounDroid: com.android.others.FileUtils Class Reference
com.android.others.FileUtils Class Reference
Utils for work with files.
Static Public Member Functions
static String getOneLineFromFile (final Context context, String fileName) throws IOException
Get one string from the file with the given name.
static ArrayList< String > getLinesFromFile (final Context context, String fileName) throws IOException
Get lines from the file with the given name.
static void saveDataStr (final Context context, String fileName, String data, final int mode) throws IOException
Save the given data string to the file with the given name.
static void saveDataList (final Context context, String fileName, List< DesktopData > data) throws IOException
Save data list to the file with the given name.
Static Private Member Functions
static void closeBufferReaderAndInputStream (final FileInputStream inputStream, final BufferedReader bufferedReader) throws IOException
Close the buffer of reader and input stream.
static void closeOutputStream (OutputStream outputStream) throws IOException
Close the output stream.
Detailed Description
Utils for work with files.
Definition at line 48 of file FileUtils.java.
Member Function Documentation
static void com.android.others.FileUtils.closeBufferReaderAndInputStream (final FileInputStream inputStream, final BufferedReader bufferedReader) throws IOException inline static private
Close the buffer of reader and input stream.
Parameters
inputStream The input stream instance
bufferedReader The buffer reader instance
Exceptions
IOException
Definition at line 86 of file FileUtils.java.
Referenced by com.android.others.FileUtils.getLinesFromFile(), and com.android.others.FileUtils.getOneLineFromFile().
static void com.android.others.FileUtils.closeOutputStream (OutputStream outputStream) throws IOException inline static private
Close the output stream.
Parameters
outputStream The output stream instance
Exceptions
IOException
Definition at line 206 of file FileUtils.java.
Referenced by com.android.others.FileUtils.saveDataList(), and com.android.others.FileUtils.saveDataStr().
static ArrayList<String> com.android.others.FileUtils.getLinesFromFile (final Context context, String fileName) throws IOException inline static
Get lines from the file with the given name.
Parameters
context The app's context
fileName The name of the file
Returns
The array list of the string from the file
Exceptions
IOException
Definition at line 110 of file FileUtils.java.
References com.android.others.FileUtils.closeBufferReaderAndInputStream().
Referenced by com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile(), and com.android.ui.EditDesktopDataActivity.onCreate().
static String com.android.others.FileUtils.getOneLineFromFile (final Context context, String fileName) throws IOException inline static
Get one string from the file with the given name.
Parameters
context The app's context instance
fileName The file name for reading
Returns
The read string from the file
Exceptions
IOException
Definition at line 57 of file FileUtils.java.
References com.android.others.FileUtils.closeBufferReaderAndInputStream().
Referenced by com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile().
static void com.android.others.FileUtils.saveDataList (final Context context, String fileName, List< DesktopData > data) throws IOException inline static
Save data list to the file with the given name.
Parameters
context The app's context
fileName The file name
data The list of the data for saving
Exceptions
IOException
Definition at line 172 of file FileUtils.java.
References com.android.others.FileUtils.closeOutputStream().
Referenced by com.android.ui.DistanceVolumeActivity.saveDesktopsDatas().
static void com.android.others.FileUtils.saveDataStr (final Context context, String fileName, String data, final int mode) throws IOException inline static
Save the given data string to the file with the given name.
Parameters
context The app's context
fileName The file name
data The data string
mode The mode of saving(adding or rewriting)
Exceptions
IOException
Definition at line 144 of file FileUtils.java.
References com.android.others.FileUtils.closeOutputStream().
Referenced by com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt().
The documentation for this class was generated from the following file:
FileUtils.java