SounDroid: com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread Class Reference
com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread Class Reference
The thread of the conversation between the local bluetooth adapter and a remote device.
Inherits Thread.
Public Member Functions
ConversationThread (final BluetoothSocket socket) throws IOException
Constructor.
void write (final String str) throws IOException
Write the given string to the stream of conversation.
void run ()
Run the thread.
synchronized String getReadStr ()
Get the string read from the conversation stream.
void cancel ()
Cancel the conversation.
Private Member Functions
synchronized boolean isStopped ()
Is the conversation stopped.
synchronized void setStopped ()
Set the conversation stopped.
synchronized void setReadStr (final String str)
Set the string read from the conversation stream.
void read ()
Read from the conversation stream.
Private Attributes
OutputStream sendStream
The stream of sending data.
InputStream receiveStream
The stream of receiving data.
byte[] buff
The buffer for data.
boolean stopped = true
Conversation stopped.
String readStr = ""
The read string.
Detailed Description
The thread of the conversation between the local bluetooth adapter and a remote device.
Definition at line 342 of file BluetoothConnector.java.
Constructor & Destructor Documentation
com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.ConversationThread (final BluetoothSocket socket) throws IOException inline
Constructor.
Parameters
socket The bluetooth socket instance
Exceptions
IOException
Definition at line 356 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.buff, com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.receiveStream, and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.sendStream.
Member Function Documentation
void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.cancel () inline
Cancel the conversation.
Definition at line 439 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.isStopped(), com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setStopped(), and com.soundroid.net.bluetooth.BluetoothConnector.TAG.
synchronized String com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.getReadStr () inline
Get the string read from the conversation stream.
Returns
The string
Definition at line 401 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.readStr.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.waitForResponse().
synchronized boolean com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.isStopped () inline private
Is the conversation stopped.
Returns
true if stopped
Definition at line 386 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.stopped.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.cancel(), and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.read().
void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.read () inline private
Read from the conversation stream.
Definition at line 416 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.buff, com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.isStopped(), com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setReadStr(), and com.soundroid.net.bluetooth.BluetoothConnector.TAG.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.run().
void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.run () inline
Run the thread.
Definition at line 377 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.read(), and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.stopped.
synchronized void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setReadStr (final String str) inline private
Set the string read from the conversation stream.
Parameters
str The string
Definition at line 409 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.readStr.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.read().
synchronized void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setStopped () inline private
Set the conversation stopped.
Definition at line 393 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.stopped.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.cancel().
void com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.write (final String str) throws IOException inline
Write the given string to the stream of conversation.
Parameters
str The string
Exceptions
IOException
Definition at line 368 of file BluetoothConnector.java.
References com.soundroid.net.bluetooth.BluetoothConnector.TAG.
Field Documentation
byte [] com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.buff private
The buffer for data.
Definition at line 346 of file BluetoothConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.ConversationThread(), and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.read().
String com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.readStr = "" private
The read string.
Definition at line 349 of file BluetoothConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.getReadStr(), and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setReadStr().
InputStream com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.receiveStream private
The stream of receiving data.
Definition at line 344 of file BluetoothConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.ConversationThread().
OutputStream com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.sendStream private
The stream of sending data.
Definition at line 343 of file BluetoothConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.ConversationThread().
boolean com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.stopped = true private
Conversation stopped.
Definition at line 348 of file BluetoothConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.isStopped(), com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.run(), and com.soundroid.net.bluetooth.BluetoothConnector.ConversationThread.setStopped().
The documentation for this class was generated from the following file:
BluetoothConnector.java