SounDroid: com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests Class Reference
com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests Class Reference
Tests of blue tooth connection.
Inherits ActivityInstrumentationTestCase2< DistanceVolumeActivity >.
Data Structures
class SeekBarEnabledCondition
class SeekBarLessThanValueCondition
class SeekBarMoreThanValueCondition
Public Member Functions
DistanceVolumeActivityBlueToothTests ()
void setUp () throws Exception
void firstOpenTest ()
void testUnreachableDev ()
void reachableUnreachableDevsTest ()
void allUnreachableDevsTest ()
void pressBackTest ()
void muteButtonTest ()
void volumeSeekbarTest ()
void allReachableDevs ()
void tearDown () throws Exception
Private Member Functions
void turnOnBt ()
void verifyVolumeUiDisabled ()
void selectUnreachableDev ()
void verifyDialog ()
void selectInSpinner (Spinner spinner, String unreachableBtDev)
Private Attributes
Solo solo
final int TIMEOUT = 5000
final int FAIL_CONNECTION_TIMEOUT = 30000
Static Private Attributes
static final String REACHABLE_BT_DEV = "agamemenon-0"
static final String UNREACHABLE_BT_DEV = "ubuntu-gnome-0"
static final String DIALOG_TXT = "The remote device hasn't discovered"
Detailed Description
Tests of blue tooth connection.
Definition at line 23 of file DistanceVolumeActivityBlueToothTests.java.
Constructor & Destructor Documentation
com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.DistanceVolumeActivityBlueToothTests () inline
Definition at line 32 of file DistanceVolumeActivityBlueToothTests.java.
Member Function Documentation
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs () inline
Definition at line 325 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.TIMEOUT, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV.
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest () inline
Definition at line 157 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.firstOpenTest () inline
Definition at line 53 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.TIMEOUT.
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest () inline
Definition at line 190 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV.
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.pressBackTest () inline
Definition at line 180 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.reachableUnreachableDevsTest () inline
Definition at line 135 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo.
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner (Spinner spinner, String unreachableBtDev) inline private
Definition at line 128 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.firstOpenTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.reachableUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev () inline private
Definition at line 102 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled().
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.reachableUnreachableDevsTest(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.testUnreachableDev().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.setUp () throws Exception inline
Definition at line 37 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.turnOnBt().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.tearDown () throws Exception inline
Definition at line 396 of file DistanceVolumeActivityBlueToothTests.java.
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.testUnreachableDev () inline
Definition at line 82 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.turnOnBt () inline private
Definition at line 42 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.setUp().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog () inline private
Definition at line 122 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.DIALOG_TXT, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.FAIL_CONNECTION_TIMEOUT, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.TIMEOUT.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled () inline private
Definition at line 95 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.pressBackTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.testUnreachableDev().
void com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest () inline
Definition at line 265 of file DistanceVolumeActivityBlueToothTests.java.
References com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo, com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.TIMEOUT, and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV.
Field Documentation
final String com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.DIALOG_TXT = "The remote device hasn't discovered" static private
Definition at line 26 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog().
final int com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.FAIL_CONNECTION_TIMEOUT = 30000 private
Definition at line 30 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog().
final String com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.REACHABLE_BT_DEV = "agamemenon-0" static private
Definition at line 24 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.firstOpenTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.reachableUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest().
Solo com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.solo private
Definition at line 28 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.firstOpenTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.reachableUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectInSpinner(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.setUp(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyVolumeUiDisabled(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest().
final int com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.TIMEOUT = 5000 private
Definition at line 29 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.firstOpenTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.verifyDialog(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest().
final String com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.UNREACHABLE_BT_DEV = "ubuntu-gnome-0" static private
Definition at line 25 of file DistanceVolumeActivityBlueToothTests.java.
Referenced by com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allReachableDevs(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.allUnreachableDevsTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.muteButtonTest(), com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.selectUnreachableDev(), and com.soundroid.tests.bt.DistanceVolumeActivityBlueToothTests.volumeSeekbarTest().
The documentation for this class was generated from the following file:
DistanceVolumeActivityBlueToothTests.java