SounDroid: com.soundroid.net.wifi.WifiConnector Class Reference
com.soundroid.net.wifi.WifiConnector Class Reference
Wifi Network connector initializes connection to the given IP address and port sends and receives given strings by the established connection.
Inherits com.soundroid.net.NetConnector.
Public Member Functions
WifiConnector ()
Constructor.
boolean isConnectedToNet (final Context context)
Return connection to a network.
void connect (final String ip, final String port) throws IOException
Connects to the given IP and port.
boolean isAddrReachable (final String ip)
Checks is the given IP reachable by network.
String getCurVol ()
Get the current sound's volume on the connected desktop.
boolean sendMuteState (final boolean mute)
Send the command for mute or unmute the sound's system on the connected desktop.
void closeConnection ()
Close the connection to the connected desktop.
boolean sendChgVol (final int vol)
Send the command for changing sound's volume at the connected desktop to the given percent.
boolean isConnectedToDaemon ()
Is the connection to the remote desktop established?
boolean handShake ()
Send hello to the connected desktop and get hello from it.
boolean isMuted ()
Is the sound volume of the connected desktop muted?
Private Member Functions
void sendStr (final String str) throws IOException
Send the command for end connection.
String receiveStr () throws IOException
Receive a string from the connected desktop.
Private Attributes
String TAG = "DistanceVolume.WifiConnector"
The tag for writing to log.
Socket socket = null
The socket's instance.
OutputStream outStream = null
The output stream instance.
DataOutputStream dataOutStream = null
The data output stream instance.
InputStream inStream = null
The input stream instance.
DataInputStream dataInStream = null
The data input stream instance.
InetSocketAddress addr
The network address for connecting.
String macAddrStr = ""
The string of a MAC address.
boolean connectedToDaemon = false
Is the connection to daemon established?
Static Private Attributes
static final int TIME_OUT = 10000
Connection's time out in milliseconds.
Additional Inherited Members
Data Fields inherited from com.soundroid.net.NetConnector
String HELLO = "hello"
String constant 'hello'.
Detailed Description
Wifi Network connector initializes connection to the given IP address and port sends and receives given strings by the established connection.
Definition at line 50 of file WifiConnector.java.
Constructor & Destructor Documentation
com.soundroid.net.wifi.WifiConnector.WifiConnector () inline
Constructor.
Definition at line 71 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.socket.
Member Function Documentation
void com.soundroid.net.wifi.WifiConnector.closeConnection () inline
Close the connection to the connected desktop.
Implements com.soundroid.net.NetConnector.
Definition at line 208 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.connectedToDaemon, com.soundroid.net.wifi.WifiConnector.dataInStream, com.soundroid.net.wifi.WifiConnector.dataOutStream, com.soundroid.net.wifi.WifiConnector.inStream, com.soundroid.net.wifi.WifiConnector.outStream, com.soundroid.net.wifi.WifiConnector.socket, and com.soundroid.net.wifi.WifiConnector.TAG.
void com.soundroid.net.wifi.WifiConnector.connect (final String ip, final String port) throws IOException inline
Connects to the given IP and port.
Parameters
ip The IP for connecting
port The port number
Exceptions
IOException
Implements com.soundroid.net.NetConnector.
Definition at line 93 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.addr, com.soundroid.net.wifi.WifiConnector.connectedToDaemon, com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.socket, com.soundroid.net.wifi.WifiConnector.TAG, and com.soundroid.net.wifi.WifiConnector.TIME_OUT.
String com.soundroid.net.wifi.WifiConnector.getCurVol () inline
Get the current sound's volume on the connected desktop.
Returns
The string of the sound's volume in percents
Implements com.soundroid.net.NetConnector.
Definition at line 136 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendStr(), and com.soundroid.net.wifi.WifiConnector.TAG.
boolean com.soundroid.net.wifi.WifiConnector.handShake () inline
Send hello to the connected desktop and get hello from it.
Returns
true The handshake has made successfully
Implements com.soundroid.net.NetConnector.
Definition at line 306 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.connectedToDaemon, com.soundroid.net.NetConnector.HELLO, com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendStr(), and com.soundroid.net.wifi.WifiConnector.TAG.
boolean com.soundroid.net.wifi.WifiConnector.isAddrReachable (final String ip) inline
Checks is the given IP reachable by network.
Parameters
ip The IP for checking
Returns
true The IP is reachable
Implements com.soundroid.net.NetConnector.
Definition at line 115 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.TAG, and com.soundroid.net.wifi.WifiConnector.TIME_OUT.
boolean com.soundroid.net.wifi.WifiConnector.isConnectedToDaemon () inline
Is the connection to the remote desktop established?
Returns
true The connection established
Implements com.soundroid.net.NetConnector.
Definition at line 297 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.connectedToDaemon.
boolean com.soundroid.net.wifi.WifiConnector.isConnectedToNet (final Context context) inline
Return connection to a network.
Parameters
context The application's context
Returns
true Connected to a network
Implements com.soundroid.net.NetConnector.
Definition at line 81 of file WifiConnector.java.
boolean com.soundroid.net.wifi.WifiConnector.isMuted () inline
Is the sound volume of the connected desktop muted?
Returns
true The desktop muted
Implements com.soundroid.net.NetConnector.
Definition at line 327 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendStr(), and com.soundroid.net.wifi.WifiConnector.TAG.
String com.soundroid.net.wifi.WifiConnector.receiveStr () throws IOException inline private
Receive a string from the connected desktop.
Returns
The received string
Exceptions
IOException
Definition at line 265 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.dataInStream, com.soundroid.net.wifi.WifiConnector.inStream, and com.soundroid.net.wifi.WifiConnector.TAG.
Referenced by com.soundroid.net.wifi.WifiConnector.getCurVol(), com.soundroid.net.wifi.WifiConnector.handShake(), com.soundroid.net.wifi.WifiConnector.isMuted(), com.soundroid.net.wifi.WifiConnector.sendChgVol(), and com.soundroid.net.wifi.WifiConnector.sendMuteState().
boolean com.soundroid.net.wifi.WifiConnector.sendChgVol (final int vol) inline
Send the command for changing sound's volume at the connected desktop to the given percent.
Parameters
vol The volume in percents
Returns
true The volume has been changed successfully
Implements com.soundroid.net.NetConnector.
Definition at line 282 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendStr(), and com.soundroid.net.wifi.WifiConnector.TAG.
boolean com.soundroid.net.wifi.WifiConnector.sendMuteState (final boolean mute) inline
Send the command for mute or unmute the sound's system on the connected desktop.
Parameters
mute The mute or unmute state should be sent
Returns
true The command was sent and executed successfully
Implements com.soundroid.net.NetConnector.
Definition at line 162 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.macAddrStr, com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendStr(), and com.soundroid.net.wifi.WifiConnector.TAG.
void com.soundroid.net.wifi.WifiConnector.sendStr (final String str) throws IOException inline private
Send the command for end connection.
Send the given string to the connected desktop
Parameters
str The string for sending
Exceptions
IOException
Definition at line 196 of file WifiConnector.java.
References com.soundroid.net.wifi.WifiConnector.dataOutStream, com.soundroid.net.wifi.WifiConnector.outStream, and com.soundroid.net.wifi.WifiConnector.TAG.
Referenced by com.soundroid.net.wifi.WifiConnector.getCurVol(), com.soundroid.net.wifi.WifiConnector.handShake(), com.soundroid.net.wifi.WifiConnector.isMuted(), com.soundroid.net.wifi.WifiConnector.sendChgVol(), and com.soundroid.net.wifi.WifiConnector.sendMuteState().
Field Documentation
InetSocketAddress com.soundroid.net.wifi.WifiConnector.addr private
The network address for connecting.
Definition at line 63 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.connect().
boolean com.soundroid.net.wifi.WifiConnector.connectedToDaemon = false private
Is the connection to daemon established?
Definition at line 66 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), com.soundroid.net.wifi.WifiConnector.connect(), com.soundroid.net.wifi.WifiConnector.handShake(), and com.soundroid.net.wifi.WifiConnector.isConnectedToDaemon().
DataInputStream com.soundroid.net.wifi.WifiConnector.dataInStream = null private
The data input stream instance.
Definition at line 61 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), and com.soundroid.net.wifi.WifiConnector.receiveStr().
DataOutputStream com.soundroid.net.wifi.WifiConnector.dataOutStream = null private
The data output stream instance.
Definition at line 58 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), and com.soundroid.net.wifi.WifiConnector.sendStr().
InputStream com.soundroid.net.wifi.WifiConnector.inStream = null private
The input stream instance.
Definition at line 60 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), and com.soundroid.net.wifi.WifiConnector.receiveStr().
String com.soundroid.net.wifi.WifiConnector.macAddrStr = "" private
The string of a MAC address.
Definition at line 64 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.connect(), com.soundroid.net.wifi.WifiConnector.getCurVol(), com.soundroid.net.wifi.WifiConnector.handShake(), com.soundroid.net.wifi.WifiConnector.isMuted(), com.soundroid.net.wifi.WifiConnector.sendChgVol(), and com.soundroid.net.wifi.WifiConnector.sendMuteState().
OutputStream com.soundroid.net.wifi.WifiConnector.outStream = null private
The output stream instance.
Definition at line 57 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), and com.soundroid.net.wifi.WifiConnector.sendStr().
Socket com.soundroid.net.wifi.WifiConnector.socket = null private
The socket's instance.
Definition at line 55 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), com.soundroid.net.wifi.WifiConnector.connect(), and com.soundroid.net.wifi.WifiConnector.WifiConnector().
String com.soundroid.net.wifi.WifiConnector.TAG = "DistanceVolume.WifiConnector" private
The tag for writing to log.
Definition at line 53 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.closeConnection(), com.soundroid.net.wifi.WifiConnector.connect(), com.soundroid.net.wifi.WifiConnector.getCurVol(), com.soundroid.net.wifi.WifiConnector.handShake(), com.soundroid.net.wifi.WifiConnector.isAddrReachable(), com.soundroid.net.wifi.WifiConnector.isMuted(), com.soundroid.net.wifi.WifiConnector.receiveStr(), com.soundroid.net.wifi.WifiConnector.sendChgVol(), com.soundroid.net.wifi.WifiConnector.sendMuteState(), and com.soundroid.net.wifi.WifiConnector.sendStr().
final int com.soundroid.net.wifi.WifiConnector.TIME_OUT = 10000 static private
Connection's time out in milliseconds.
Definition at line 51 of file WifiConnector.java.
Referenced by com.soundroid.net.wifi.WifiConnector.connect(), and com.soundroid.net.wifi.WifiConnector.isAddrReachable().
The documentation for this class was generated from the following file:
WifiConnector.java