SounDroid: com.android.ui.DistanceVolumeActivity Class Reference
com.android.ui.DistanceVolumeActivity Class Reference
The activity for selecting desktop and changing volume for the selected one.
Inherits Activity, and OnItemSelectedListener.
Data Structures
class EqualiserView
Equalizer for the volume's seek bar.
class MuteButton
Class of the button for changing volume states: mute, unmute.
Public Member Functions
void onPause ()
Save the currently selected desktop name.
void onStop ()
Close connection to a desktop.
void onStart ()
If should be redrawn, check WiFi connection.
void onCreate (Bundle savedInstanceState)
Initialize the desktops datas from file, previously selected connection type.
void onBackPressed ()
If there is connection to a desktop, close the connection and finish the activity.
void onDestroy ()
Save desktops data and close connection.
void onItemSelected (AdapterView<?> parent, View view, int pos, long id)
If an item of the desktops names drop box selected the volume percent of the selected desktop should be set.
void onNothingSelected (AdapterView<?> arg0)
Not used.
Static Public Attributes
static final String EXTRA_ACTION_TYPE = "com.android.desktopVol.SEND_DESKTOP_DATA"
static final int EDIT_DESKTOP_NAME = 1
The selected action in the activity.
static final String DESKTOP_NAME = "DESKTOP_NAME"
static final String DESKTOP_DATA = "DESKTOP_DATA"
static final String IS_DEFAULT = "IS_DEFAULT"
static String NAMES_DATA_FILE_NAME = "names.data"
The name of the file for saving desktops datas.
static NetConnector connector
The network connector instance.
Protected Member Functions
void onResume ()
If should be redrawn, initialize the desktops names drop box and save the the desktops datas.
void onActivityResult (int requestCode, int resultCode, Intent data)
Processing the results from the over activities.
Private Member Functions
void saveUiData ()
void saveDesktopsDatas ()
Save the list of desktops' datas.
void saveCheckedRadioButt ()
Save the ID of the checked radio button 'Connection type'.
void initDesktopsDatasFromFile ()
Initialization of the desktops data from file.
void initUI (final boolean connected)
Initialization of an user interface.
void setVolumeUI ()
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
void showDialog (String txt)
Show a dialog with the given text.
void enableVolumeSeekBar ()
Enable the seek bar for changing volume.
void initVolumeUI ()
Initialize the the UI for controlling volume percent.
void initVolumeSeekBar ()
Initialize the seek bar for controlling volume percent.
void initConnectionTypeRadioButt ()
Initialization of the 'connection type' radio buttons.
void initPrevConnTypeRadioButtIdFromFile ()
Initialization from file the radio button 'Connection type' checked at previous session.
void initButtons ()
Initialization of the UI buttons.
void initDesktopNamesSpinner ()
Initialization of the 'Desktops Names' spinner.
void openEditDesktopNameActivity (final int actionType)
Open the activity for editing the selected desktop name.
void openConnectingActivity (final DesktopData desktopData)
Open the activity of connecting to the remote desktop.
boolean isDesktopDataDefault (String name)
Check whether the desktop with the given name is default.
DesktopData getDesktopDataByName (String name)
Get the desktop's data by the given name.
void chgCurrentlyEditedDesktopData (String dataStr, final boolean setDefault)
Change the currently edited desktop data.
void removeCurrentlyEditedDesktopData ()
Remove the currently edited desktop data.
void setSeekBar (final int percent)
Set the seek bar's progress by the given percent.
boolean isWiFiConnected ()
Check WiFi's connection.
Private Attributes
String TAG = "DistanceVolumeActivity"
The tag for writing to log file.
Button buttEdit
MuteButton muteButt
The button for muting volume.
RadioGroup connectionTypeRadio
The radio buttons group for connection types.
Spinner desktopsNames
The drop box of the desktops names for connecting.
SeekBar volume
The seek bar for changing volume in percents.
List< DesktopData > desktopsDatas
The list of desktops datas.
String CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME = "conn_type"
final int NO_EDIT = -1
int curEditedDesktopNameInd = NO_EDIT
The selected desktop name on the spinner at the time of clicking on the button 'Edit'.
int curSelectedDesktopName = 0
Currently selected desktop name on the spinner.
int checkedConnectionTypeRadioID = R.id.wifiRadio
The checked radio button within the group.
boolean host_connection_checked = false
The connection to the currently selected desktop's host has checked.
boolean redraw = false
The activity should be redrawn.
Static Private Attributes
static final int REQUEST_CODE_EDIT = 1
The request code for a selected action.
Detailed Description
The activity for selecting desktop and changing volume for the selected one.
Definition at line 71 of file DistanceVolumeActivity.java.
Member Function Documentation
void com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData (String dataStr, final boolean setDefault) inline private
Change the currently edited desktop data.
Parameters
dataStr The string of a new desktop data
setDefault true The being changed desktop should be signed as default
Definition at line 617 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.NO_EDIT, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onActivityResult().
void com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar () inline private
Enable the seek bar for changing volume.
Definition at line 309 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.connector, com.android.net.NetConnector.getCurVol(), com.android.ui.DistanceVolumeActivity.setSeekBar(), and com.android.ui.DistanceVolumeActivity.volume.
Referenced by com.android.ui.DistanceVolumeActivity.setVolumeUI().
DesktopData com.android.ui.DistanceVolumeActivity.getDesktopDataByName (String name) inline private
Get the desktop's data by the given name.
Parameters
name The name of the desktop
Returns
The desktop's data
Definition at line 563 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.desktopsDatas.
Referenced by com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
void com.android.ui.DistanceVolumeActivity.initButtons () inline private
Initialization of the UI buttons.
Definition at line 424 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.buttEdit, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.EDIT_DESKTOP_NAME, com.android.ui.DistanceVolumeActivity.muteButt, and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
Referenced by com.android.ui.DistanceVolumeActivity.initUI().
void com.android.ui.DistanceVolumeActivity.initConnectionTypeRadioButt () inline private
Initialization of the 'connection type' radio buttons.
Definition at line 367 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.checkedConnectionTypeRadioID, com.android.ui.DistanceVolumeActivity.connectionTypeRadio, and com.android.ui.DistanceVolumeActivity.showDialog().
Referenced by com.android.ui.DistanceVolumeActivity.initUI().
void com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner () inline private
Initialization of the 'Desktops Names' spinner.
Definition at line 451 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd, com.android.ui.DistanceVolumeActivity.curSelectedDesktopName, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.desktopsNames, com.android.ui.DistanceVolumeActivity.NO_EDIT, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.initUI(), and com.android.ui.DistanceVolumeActivity.onResume().
void com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile () inline private
Initialization of the desktops data from file.
Definition at line 217 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.others.FileUtils.getLinesFromFile(), com.android.ui.DistanceVolumeActivity.NAMES_DATA_FILE_NAME, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onCreate().
void com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile () inline private
Initialization from file the radio button 'Connection type' checked at previous session.
Definition at line 387 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.checkedConnectionTypeRadioID, com.android.ui.DistanceVolumeActivity.CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME, com.android.others.FileUtils.getOneLineFromFile(), and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onCreate().
void com.android.ui.DistanceVolumeActivity.initUI (final boolean connected) inline private
Initialization of an user interface.
Parameters
connected There is connection to network
Definition at line 242 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.initButtons(), com.android.ui.DistanceVolumeActivity.initConnectionTypeRadioButt(), com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.initVolumeUI(), com.android.ui.DistanceVolumeActivity.setVolumeUI(), and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onStart().
void com.android.ui.DistanceVolumeActivity.initVolumeSeekBar () inline private
Initialize the seek bar for controlling volume percent.
Definition at line 328 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.connector, com.android.net.NetConnector.sendChgVol(), and com.android.ui.DistanceVolumeActivity.volume.
Referenced by com.android.ui.DistanceVolumeActivity.initVolumeUI().
void com.android.ui.DistanceVolumeActivity.initVolumeUI () inline private
Initialize the the UI for controlling volume percent.
Definition at line 320 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.initVolumeSeekBar().
Referenced by com.android.ui.DistanceVolumeActivity.initUI().
boolean com.android.ui.DistanceVolumeActivity.isDesktopDataDefault (String name) inline private
Check whether the desktop with the given name is default.
Default means the data of the desktop with the given name is at the head of the list of desktops datas
Parameters
name The name of a desktop
Returns
true The desktop is default
Definition at line 513 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.desktopsDatas, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
boolean com.android.ui.DistanceVolumeActivity.isWiFiConnected () inline private
Check WiFi's connection.
Returns
true There is WiFi connection
Definition at line 672 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.onStart().
void com.android.ui.DistanceVolumeActivity.onActivityResult (int requestCode, int resultCode, Intent data) inline protected
Processing the results from the over activities.
Definition at line 580 of file DistanceVolumeActivity.java.
References com.android.ui.EditDesktopDataActivity.ACTION_DEL, com.android.ui.EditDesktopDataActivity.ACTION_TYPE, com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd, com.android.ui.DistanceVolumeActivity.DESKTOP_DATA, com.android.ui.DistanceVolumeActivity.host_connection_checked, com.android.ui.DistanceVolumeActivity.IS_DEFAULT, com.android.ui.DistanceVolumeActivity.NO_EDIT, com.android.ui.DistanceVolumeActivity.redraw, com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.REQUEST_CODE_EDIT, and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.onBackPressed () inline
If there is connection to a desktop, close the connection and finish the activity.
Definition at line 357 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.connector, com.android.net.NetConnector.isConnected(), and com.android.net.NetConnector.sendEnd().
void com.android.ui.DistanceVolumeActivity.onCreate (Bundle savedInstanceState) inline
Initialize the desktops datas from file, previously selected connection type.
Initialize connection
Definition at line 204 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.connector, com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile(), com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile(), com.android.ui.DistanceVolumeActivity.redraw, and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.onDestroy () inline
Save desktops data and close connection.
Definition at line 404 of file DistanceVolumeActivity.java.
References com.android.net.NetConnector.closeConnection(), com.android.ui.DistanceVolumeActivity.connector, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.saveUiData(), com.android.net.NetConnector.sendEnd(), and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.onItemSelected (AdapterView<?> parent, View view, int pos, long id) inline
If an item of the desktops names drop box selected the volume percent of the selected desktop should be set.
Definition at line 544 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.curSelectedDesktopName, com.android.ui.DistanceVolumeActivity.host_connection_checked, and com.android.ui.DistanceVolumeActivity.setVolumeUI().
void com.android.ui.DistanceVolumeActivity.onNothingSelected (AdapterView<?> arg0) inline
Not used.
Definition at line 556 of file DistanceVolumeActivity.java.
void com.android.ui.DistanceVolumeActivity.onPause () inline
Save the currently selected desktop name.
Definition at line 123 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.curSelectedDesktopName, com.android.ui.DistanceVolumeActivity.desktopsNames, com.android.ui.DistanceVolumeActivity.redraw, and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.onResume () inline protected
If should be redrawn, initialize the desktops names drop box and save the the desktops datas.
Definition at line 528 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.onStart(), com.android.ui.DistanceVolumeActivity.redraw, com.android.ui.DistanceVolumeActivity.saveDesktopsDatas(), and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.onStart () inline
If should be redrawn, check WiFi connection.
If there is WiFi, initialize UI
Definition at line 151 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.initUI(), com.android.ui.DistanceVolumeActivity.isWiFiConnected(), com.android.ui.DistanceVolumeActivity.redraw, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onResume().
void com.android.ui.DistanceVolumeActivity.onStop () inline
Close connection to a desktop.
Definition at line 138 of file DistanceVolumeActivity.java.
References com.android.net.NetConnector.closeConnection(), com.android.ui.DistanceVolumeActivity.connector, and com.android.ui.DistanceVolumeActivity.TAG.
void com.android.ui.DistanceVolumeActivity.openConnectingActivity (final DesktopData desktopData) inline private
Open the activity of connecting to the remote desktop.
Parameters
desktopData The data of the desktop which connecting to
Definition at line 498 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.EXTRA_ACTION_TYPE.
Referenced by com.android.ui.DistanceVolumeActivity.setVolumeUI().
void com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity (final int actionType) inline private
Open the activity for editing the selected desktop name.
Parameters
actionType The type of editing(editing, adding new or deleting)
Definition at line 474 of file DistanceVolumeActivity.java.
References com.android.net.DesktopData.buildEmptyDesktopData(), com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd, com.android.ui.DistanceVolumeActivity.desktopsNames, com.android.ui.DistanceVolumeActivity.EXTRA_ACTION_TYPE, com.android.ui.DistanceVolumeActivity.getDesktopDataByName(), com.android.ui.DistanceVolumeActivity.IS_DEFAULT, com.android.ui.DistanceVolumeActivity.isDesktopDataDefault(), com.android.ui.DistanceVolumeActivity.NO_EDIT, com.android.ui.DistanceVolumeActivity.REQUEST_CODE_EDIT, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.initButtons().
void com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData () inline private
Remove the currently edited desktop data.
Definition at line 644 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd, com.android.ui.DistanceVolumeActivity.curSelectedDesktopName, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.NO_EDIT, and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onActivityResult().
void com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt () inline private
Save the ID of the checked radio button 'Connection type'.
Definition at line 189 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.checkedConnectionTypeRadioID, com.android.ui.DistanceVolumeActivity.CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME, com.android.others.FileUtils.saveDataStr(), and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.saveUiData().
void com.android.ui.DistanceVolumeActivity.saveDesktopsDatas () inline private
Save the list of desktops' datas.
Definition at line 177 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.NAMES_DATA_FILE_NAME, com.android.others.FileUtils.saveDataList(), and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onResume(), and com.android.ui.DistanceVolumeActivity.saveUiData().
void com.android.ui.DistanceVolumeActivity.saveUiData () inline private
Definition at line 167 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt(), com.android.ui.DistanceVolumeActivity.saveDesktopsDatas(), and com.android.ui.DistanceVolumeActivity.TAG.
Referenced by com.android.ui.DistanceVolumeActivity.onDestroy().
void com.android.ui.DistanceVolumeActivity.setSeekBar (final int percent) inline private
Set the seek bar's progress by the given percent.
Parameters
percent The percent of progress
Definition at line 663 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.volume.
Referenced by com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar().
void com.android.ui.DistanceVolumeActivity.setVolumeUI () inline private
Set volume percent of the currently selected desktop if there is network connection and there is connection to the desktop.
Definition at line 261 of file DistanceVolumeActivity.java.
References com.android.ui.DistanceVolumeActivity.connector, com.android.ui.DistanceVolumeActivity.curSelectedDesktopName, com.android.ui.DistanceVolumeActivity.desktopsDatas, com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar(), com.android.net.DesktopData.getName(), com.android.ui.DistanceVolumeActivity.host_connection_checked, com.android.net.NetConnector.isConnected(), com.android.net.NetConnector.isMuted(), com.android.ui.DistanceVolumeActivity.muteButt, com.android.ui.DistanceVolumeActivity.openConnectingActivity(), com.android.ui.DistanceVolumeActivity.MuteButton.setEnabled(), com.android.ui.DistanceVolumeActivity.MuteButton.setShownMuted(), com.android.ui.DistanceVolumeActivity.showDialog(), and com.android.ui.DistanceVolumeActivity.volume.
Referenced by com.android.ui.DistanceVolumeActivity.initUI(), and com.android.ui.DistanceVolumeActivity.onItemSelected().
void com.android.ui.DistanceVolumeActivity.showDialog (String txt) inline private
Show a dialog with the given text.
Parameters
txt The text for the dialog
Definition at line 296 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initConnectionTypeRadioButt(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
Field Documentation
Button com.android.ui.DistanceVolumeActivity.buttEdit private
Definition at line 76 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initButtons().
int com.android.ui.DistanceVolumeActivity.checkedConnectionTypeRadioID = R.id.wifiRadio private
The checked radio button within the group.
Definition at line 109 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initConnectionTypeRadioButt(), com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile(), and com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt().
String com.android.ui.DistanceVolumeActivity.CONN_TYPE_CHECKED_RADIO_BUTT_ID_FILE_NAME = "conn_type" private
Definition at line 103 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile(), and com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt().
RadioGroup com.android.ui.DistanceVolumeActivity.connectionTypeRadio private
The radio buttons group for connection types.
Definition at line 78 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initConnectionTypeRadioButt().
NetConnector com.android.ui.DistanceVolumeActivity.connector static
The network connector instance.
Definition at line 115 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar(), com.android.ui.DistanceVolumeActivity.MuteButton.init(), com.android.ui.DistanceVolumeActivity.initVolumeSeekBar(), com.android.ui.DistanceVolumeActivity.onBackPressed(), com.android.ui.ConnectingActivity.onCreate(), com.android.ui.DistanceVolumeActivity.onCreate(), com.android.ui.DistanceVolumeActivity.onDestroy(), com.android.ui.DistanceVolumeActivity.onStop(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
int com.android.ui.DistanceVolumeActivity.curEditedDesktopNameInd = NO_EDIT private
The selected desktop name on the spinner at the time of clicking on the button 'Edit'.
Definition at line 106 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity(), and com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData().
int com.android.ui.DistanceVolumeActivity.curSelectedDesktopName = 0 private
Currently selected desktop name on the spinner.
Definition at line 107 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.onItemSelected(), com.android.ui.DistanceVolumeActivity.onPause(), com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
final String com.android.ui.DistanceVolumeActivity.DESKTOP_DATA = "DESKTOP_DATA" static
Definition at line 95 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initOkButt(), and com.android.ui.DistanceVolumeActivity.onActivityResult().
final String com.android.ui.DistanceVolumeActivity.DESKTOP_NAME = "DESKTOP_NAME" static
Definition at line 94 of file DistanceVolumeActivity.java.
List<DesktopData> com.android.ui.DistanceVolumeActivity.desktopsDatas private
The list of desktops datas.
Definition at line 84 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.getDesktopDataByName(), com.android.ui.DistanceVolumeActivity.initButtons(), com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile(), com.android.ui.DistanceVolumeActivity.initUI(), com.android.ui.DistanceVolumeActivity.isDesktopDataDefault(), com.android.ui.DistanceVolumeActivity.onDestroy(), com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.saveDesktopsDatas(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
Spinner com.android.ui.DistanceVolumeActivity.desktopsNames private
The drop box of the desktops names for connecting.
Definition at line 80 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.onPause(), and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
final int com.android.ui.DistanceVolumeActivity.EDIT_DESKTOP_NAME = 1 static
The selected action in the activity.
Definition at line 91 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initButtons().
final String com.android.ui.DistanceVolumeActivity.EXTRA_ACTION_TYPE = "com.android.desktopVol.SEND_DESKTOP_DATA" static
Definition at line 90 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.ConnectingActivity.onCreate(), com.android.ui.EditDesktopDataActivity.onCreate(), com.android.ui.DistanceVolumeActivity.openConnectingActivity(), and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
boolean com.android.ui.DistanceVolumeActivity.host_connection_checked = false private
The connection to the currently selected desktop's host has checked.
Definition at line 111 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.DistanceVolumeActivity.onItemSelected(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
final String com.android.ui.DistanceVolumeActivity.IS_DEFAULT = "IS_DEFAULT" static
Definition at line 100 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.EditDesktopDataActivity.initOkButt(), com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.EditDesktopDataActivity.onCreate(), and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
MuteButton com.android.ui.DistanceVolumeActivity.muteButt private
The button for muting volume.
Definition at line 77 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initButtons(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
String com.android.ui.DistanceVolumeActivity.NAMES_DATA_FILE_NAME = "names.data" static
The name of the file for saving desktops datas.
Definition at line 102 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile(), com.android.ui.EditDesktopDataActivity.onCreate(), and com.android.ui.DistanceVolumeActivity.saveDesktopsDatas().
final int com.android.ui.DistanceVolumeActivity.NO_EDIT = -1 private
Definition at line 105 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity(), and com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData().
boolean com.android.ui.DistanceVolumeActivity.redraw = false private
The activity should be redrawn.
Definition at line 113 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.DistanceVolumeActivity.onCreate(), com.android.ui.DistanceVolumeActivity.onPause(), com.android.ui.DistanceVolumeActivity.onResume(), and com.android.ui.DistanceVolumeActivity.onStart().
final int com.android.ui.DistanceVolumeActivity.REQUEST_CODE_EDIT = 1 static private
The request code for a selected action.
Definition at line 97 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.onActivityResult(), and com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity().
String com.android.ui.DistanceVolumeActivity.TAG = "DistanceVolumeActivity" private
The tag for writing to log file.
Definition at line 72 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.chgCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.MuteButton.init(), com.android.ui.DistanceVolumeActivity.initDesktopNamesSpinner(), com.android.ui.DistanceVolumeActivity.initDesktopsDatasFromFile(), com.android.ui.DistanceVolumeActivity.initPrevConnTypeRadioButtIdFromFile(), com.android.ui.DistanceVolumeActivity.initUI(), com.android.ui.DistanceVolumeActivity.isDesktopDataDefault(), com.android.ui.DistanceVolumeActivity.onActivityResult(), com.android.ui.DistanceVolumeActivity.onCreate(), com.android.ui.DistanceVolumeActivity.onDestroy(), com.android.ui.DistanceVolumeActivity.onPause(), com.android.ui.DistanceVolumeActivity.onResume(), com.android.ui.DistanceVolumeActivity.onStart(), com.android.ui.DistanceVolumeActivity.onStop(), com.android.ui.DistanceVolumeActivity.openEditDesktopNameActivity(), com.android.ui.DistanceVolumeActivity.removeCurrentlyEditedDesktopData(), com.android.ui.DistanceVolumeActivity.saveCheckedRadioButt(), com.android.ui.DistanceVolumeActivity.saveDesktopsDatas(), and com.android.ui.DistanceVolumeActivity.saveUiData().
SeekBar com.android.ui.DistanceVolumeActivity.volume private
The seek bar for changing volume in percents.
Definition at line 82 of file DistanceVolumeActivity.java.
Referenced by com.android.ui.DistanceVolumeActivity.enableVolumeSeekBar(), com.android.ui.DistanceVolumeActivity.initVolumeSeekBar(), com.android.ui.DistanceVolumeActivity.setSeekBar(), and com.android.ui.DistanceVolumeActivity.setVolumeUI().
The documentation for this class was generated from the following file:
DistanceVolumeActivity.java