SounDroid: com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver Class Reference
com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver Class Reference
The observing of connection to a network changes.
Inherits Runnable.
Public Member Functions
synchronized void stopObserving ()
Stop observing.
synchronized boolean isStopped ()
Is observing stopped.
void run ()
Private Member Functions
void sleepBeforeChangingConnectorType (final int time)
Sleep the given type before changing connection type.
Private Attributes
boolean stop = true
Stop observing flag.
Detailed Description
The observing of connection to a network changes.
Definition at line 273 of file DistanceVolumeActivity.java.
Member Function Documentation
synchronized boolean com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.isStopped () inline
Is observing stopped.
Returns
true Stopped
Definition at line 287 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stop.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
void com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run () inline
Definition at line 292 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.CONNECTION_TYPE_CHANGED, com.soundroid.ui.UI.hasConnectionTypeChanged(), com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.isStopped(), com.soundroid.ui.DistanceVolumeActivity.REDRAW_SOUNDVOL_UI, com.soundroid.ui.DistanceVolumeActivity.REDRAW_UI, com.soundroid.ui.UI.shouldBeRedrawn(), com.soundroid.ui.UI.shouldBeRedrawnSoundVolUI(), com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.sleepBeforeChangingConnectorType(), com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stop, and com.soundroid.ui.DistanceVolumeActivity.ui.
void com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.sleepBeforeChangingConnectorType (final int time) inline private
Sleep the given type before changing connection type.
Parameters
time Time in milli seconds
Definition at line 315 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.TAG.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
synchronized void com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stopObserving () inline
Stop observing.
Definition at line 279 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stop.
Field Documentation
boolean com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stop = true private
Stop observing flag.
Definition at line 274 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.isStopped(), com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run(), and com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.stopObserving().
The documentation for this class was generated from the following file:
DistanceVolumeActivity.java