SounDroid: com.soundroid.ui.DistanceVolumeActivity Class Reference
com.soundroid.ui.DistanceVolumeActivity Class Reference
The activity for selecting desktop and changing volume for the selected one.
Inherits Activity.
Data Structures
class ConnectionTypeObserver
The observing of connection to a network changes.
Public Member Functions
void onPause ()
Save the currently selected desktop name.
void onStop ()
Close connection to a desktop.
void onStart ()
If should be redrawn, check WiFi connection.
void onCreate (Bundle savedInstanceState)
Initialize the desktops datas from file, previously selected connection type.
void onBackPressed ()
If there is connection to a desktop, close the connection and finish the activity.
void onDestroy ()
Save desktops data and close connection.
Protected Member Functions
void onResume ()
If should be redrawn, initialize the desktops names drop box and save the the desktops datas.
void onActivityResult (int requestCode, int resultCode, Intent data)
Processing the results from the over activities.
Private Member Functions
void reDrawUI ()
Redraw the UI.
boolean isConnectedToNetAfterDialog ()
Is there a connection to a network after opening the dialog for user.
void initUiFromFile ()
Initialize UI from file.
void initUiByRadioButt ()
Initialize UI with dependence on the connection type radio button selected.
void closeConnector ()
Close the connector to a network.
Private Attributes
String TAG = "DistanceVolumeActivity"
The tag for writing to log file.
NetConnector connector
The connector to a network.
UI ui
The UI instance.
ConnectionTypeObserver connectionTypeObserver
The observer of connection type changing.
Thread observerThread = null
The thread of UI observing.
Handler handler
The handler of UI events messages.
Static Private Attributes
static final int CONNECTION_TYPE_CHANGED = 1
static final int REDRAW_UI = 2
static final int REDRAW_SOUNDVOL_UI = 3
Detailed Description
The activity for selecting desktop and changing volume for the selected one.
Definition at line 46 of file DistanceVolumeActivity.java.
Member Function Documentation
void com.soundroid.ui.DistanceVolumeActivity.closeConnector () inline private
Close the connector to a network.
Definition at line 212 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connector.
Referenced by com.soundroid.ui.DistanceVolumeActivity.onBackPressed(), and com.soundroid.ui.DistanceVolumeActivity.onDestroy().
void com.soundroid.ui.DistanceVolumeActivity.initUiByRadioButt () inline private
Initialize UI with dependence on the connection type radio button selected.
Definition at line 177 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connector, com.soundroid.ui.DistanceVolumeActivity.reDrawUI(), and com.soundroid.ui.DistanceVolumeActivity.ui.
void com.soundroid.ui.DistanceVolumeActivity.initUiFromFile () inline private
Initialize UI from file.
Definition at line 162 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connector, com.soundroid.ui.DistanceVolumeActivity.TAG, and com.soundroid.ui.DistanceVolumeActivity.ui.
Referenced by com.soundroid.ui.DistanceVolumeActivity.onCreate().
boolean com.soundroid.ui.DistanceVolumeActivity.isConnectedToNetAfterDialog () inline private
Is there a connection to a network after opening the dialog for user.
Returns
true Connected to a network
Definition at line 127 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connector, com.soundroid.net.NetConnector.isConnectedToNet(), and com.soundroid.ui.DistanceVolumeActivity.TAG.
Referenced by com.soundroid.ui.DistanceVolumeActivity.reDrawUI().
void com.soundroid.ui.DistanceVolumeActivity.onActivityResult (int requestCode, int resultCode, Intent data) inline protected
Processing the results from the over activities.
Definition at line 241 of file DistanceVolumeActivity.java.
void com.soundroid.ui.DistanceVolumeActivity.onBackPressed () inline
If there is connection to a desktop, close the connection and finish the activity.
Definition at line 189 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.closeConnector().
void com.soundroid.ui.DistanceVolumeActivity.onCreate (Bundle savedInstanceState) inline
Initialize the desktops datas from file, previously selected connection type.
Initialize connection
Definition at line 151 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.initUiFromFile(), and com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.onDestroy () inline
Save desktops data and close connection.
Definition at line 198 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.closeConnector(), and com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.onPause () inline
Save the currently selected desktop name.
Definition at line 67 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.onResume () inline protected
If should be redrawn, initialize the desktops names drop box and save the the desktops datas.
Definition at line 226 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.onStart () inline
If should be redrawn, check WiFi connection.
If there is WiFi, initialize UI
Definition at line 95 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connectionTypeObserver, com.soundroid.ui.DistanceVolumeActivity.observerThread, com.soundroid.ui.DistanceVolumeActivity.reDrawUI(), and com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.onStop () inline
Close connection to a desktop.
Definition at line 79 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.connector, com.soundroid.ui.DistanceVolumeActivity.observerThread, and com.soundroid.ui.DistanceVolumeActivity.TAG.
void com.soundroid.ui.DistanceVolumeActivity.reDrawUI () inline private
Redraw the UI.
Definition at line 109 of file DistanceVolumeActivity.java.
References com.soundroid.ui.DistanceVolumeActivity.isConnectedToNetAfterDialog().
Referenced by com.soundroid.ui.DistanceVolumeActivity.initUiByRadioButt(), and com.soundroid.ui.DistanceVolumeActivity.onStart().
Field Documentation
final int com.soundroid.ui.DistanceVolumeActivity.CONNECTION_TYPE_CHANGED = 1 static private
Definition at line 56 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
ConnectionTypeObserver com.soundroid.ui.DistanceVolumeActivity.connectionTypeObserver private
The observer of connection type changing.
Definition at line 54 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.onStart().
NetConnector com.soundroid.ui.DistanceVolumeActivity.connector private
The connector to a network.
Definition at line 50 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.closeConnector(), com.soundroid.ui.DistanceVolumeActivity.initUiByRadioButt(), com.soundroid.ui.DistanceVolumeActivity.initUiFromFile(), com.soundroid.ui.DistanceVolumeActivity.isConnectedToNetAfterDialog(), and com.soundroid.ui.DistanceVolumeActivity.onStop().
Handler com.soundroid.ui.DistanceVolumeActivity.handler private
Initial value:
= new Handler() {
        @Override
        public void handleMessage(Message msg) {
            switch (msg.what) {
                case CONNECTION_TYPE_CHANGED:
                    closeConnector();
                    initUiByRadioButt();
                    break;
                case REDRAW_UI:
                    reDrawUI();
                    break;
                case REDRAW_SOUNDVOL_UI:
                    ui.setVolumeUI();
                    break;
                default:
                    Log.e(TAG, "Unknown message: " + msg.what);
            }
        }
    }
The handler of UI events messages.
Definition at line 250 of file DistanceVolumeActivity.java.
Thread com.soundroid.ui.DistanceVolumeActivity.observerThread = null private
The thread of UI observing.
Definition at line 60 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.onStart(), and com.soundroid.ui.DistanceVolumeActivity.onStop().
final int com.soundroid.ui.DistanceVolumeActivity.REDRAW_SOUNDVOL_UI = 3 static private
Definition at line 58 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
final int com.soundroid.ui.DistanceVolumeActivity.REDRAW_UI = 2 static private
Definition at line 57 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
String com.soundroid.ui.DistanceVolumeActivity.TAG = "DistanceVolumeActivity" private
The tag for writing to log file.
Definition at line 48 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.initUiFromFile(), com.soundroid.ui.DistanceVolumeActivity.isConnectedToNetAfterDialog(), com.soundroid.ui.DistanceVolumeActivity.onCreate(), com.soundroid.ui.DistanceVolumeActivity.onDestroy(), com.soundroid.ui.DistanceVolumeActivity.onPause(), com.soundroid.ui.DistanceVolumeActivity.onResume(), com.soundroid.ui.DistanceVolumeActivity.onStart(), com.soundroid.ui.DistanceVolumeActivity.onStop(), and com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.sleepBeforeChangingConnectorType().
UI com.soundroid.ui.DistanceVolumeActivity.ui private
The UI instance.
Definition at line 52 of file DistanceVolumeActivity.java.
Referenced by com.soundroid.ui.DistanceVolumeActivity.initUiByRadioButt(), com.soundroid.ui.DistanceVolumeActivity.initUiFromFile(), and com.soundroid.ui.DistanceVolumeActivity.ConnectionTypeObserver.run().
The documentation for this class was generated from the following file:
DistanceVolumeActivity.java