SounDroid: com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests Class Reference
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests Class Reference
Tests of the Activity 'Desktop Name Edit' for adding new desktops.
Inherits ActivityInstrumentationTestCase2< DistanceVolumeActivity >.
Data Structures
enum DESKTOPS_NAMES
Public Member Functions
EditDesktopDataActivityForAddingNewAndDelTests ()
void setUp () throws Exception
void testMainActivityWhenNoDesktopsSaved ()
void testAddFirstDesktop ()
void testSecondDesktop ()
void testCreateDelSameDesktop ()
Test:
void testThirdDesktop ()
void testChangeDesktopData ()
void testDelSecondDesktop ()
void testDelThirdDesktop ()
void testDelFirstDesktop ()
void tearDown () throws Exception
Static Public Member Functions
static void createNew (Solo solo_, String ip, String port, DESKTOPS_NAMES name, boolean setDefault, boolean clickCancel)
Private Member Functions
void closeDialogUnreachableHost ()
void chkEditActivityContext (String ip, String port, DESKTOPS_NAMES name, boolean setDefault)
void selectDesktop (final String name, final int expectedDesktopsNum)
void delDesktop (final DESKTOPS_NAMES desktopName)
Private Attributes
boolean wifiWasEnabled = false
Solo solo
Detailed Description
Tests of the Activity 'Desktop Name Edit' for adding new desktops.
Definition at line 24 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Constructor & Destructor Documentation
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.EditDesktopDataActivityForAddingNewAndDelTests () inline
Definition at line 43 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Member Function Documentation
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.chkEditActivityContext (String ip, String port, DESKTOPS_NAMES name, boolean setDefault) inline private
Definition at line 207 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.getValue(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testAddFirstDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData().
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost () inline private
Definition at line 137 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelThirdDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
static void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew (Solo solo_, String ip, String port, DESKTOPS_NAMES name, boolean setDefault, boolean clickCancel) inline static
Definition at line 230 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testAddFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.delDesktop (final DESKTOPS_NAMES desktopName) inline private
Definition at line 399 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.getValue(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop().
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.selectDesktop (final String name, final int expectedDesktopsNum) inline private
Definition at line 300 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData().
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.setUp () throws Exception inline
Definition at line 48 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.wifiWasEnabled.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.tearDown () throws Exception inline
Definition at line 411 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.wifiWasEnabled.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testAddFirstDesktop () inline
Definition at line 80 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.chkEditActivityContext(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData () inline
Definition at line 261 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.chkEditActivityContext(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.selectDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.TEMP, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.THIRD.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop () inline
Test:
Add a new desktop
Delete the desktop
Add the new desktop with the same name
Definition at line 150 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.delDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelFirstDesktop () inline
Definition at line 375 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop () inline
Definition at line 309 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.THIRD.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelThirdDesktop () inline
Definition at line 345 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.THIRD.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testMainActivityWhenNoDesktopsSaved () inline
Definition at line 59 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop () inline
Definition at line 112 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo.
void com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop () inline
Definition at line 181 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
References com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.createNew(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND, com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo, and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.THIRD.
Field Documentation
Solo com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.solo private
Definition at line 41 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.chkEditActivityContext(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.closeDialogUnreachableHost(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.delDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.selectDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.setUp(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testAddFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelThirdDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testMainActivityWhenNoDesktopsSaved(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
boolean com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.wifiWasEnabled = false private
Definition at line 25 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.setUp(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.tearDown().
The documentation for this class was generated from the following file:
EditDesktopDataActivityForAddingNewAndDelTests.java