SounDroid: com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES Enum Reference
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES Enum Reference
Public Member Functions
DESKTOPS_NAMES (String val)
String getValue ()
Data Fields
FIRST =("one")
SECOND =("two")
THIRD =("three")
TEMP =("blabla")
TEST =("test")
REACHABLE =("home")
UNREACHABLE =("unreachable")
REACHABLE2 =("laptop")
Private Attributes
String value
Detailed Description
Definition at line 27 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Constructor & Destructor Documentation
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.DESKTOPS_NAMES (String val) inline
Definition at line 32 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Member Function Documentation
String com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.getValue () inline
Definition at line 36 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.chkEditActivityContext(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.delDesktop().
Field Documentation
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.FIRST =("one")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testAddFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelFirstDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelThirdDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.REACHABLE =("home")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.REACHABLE2 =("laptop")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.SECOND =("two")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testCreateDelSameDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testSecondDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.TEMP =("blabla")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData().
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.TEST =("test")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.THIRD =("three")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
Referenced by com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testChangeDesktopData(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelSecondDesktop(), com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testDelThirdDesktop(), and com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.testThirdDesktop().
com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.UNREACHABLE =("unreachable")
Definition at line 28 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
String com.soundroid.tests.edit.EditDesktopDataActivityForAddingNewAndDelTests.DESKTOPS_NAMES.value private
Definition at line 30 of file EditDesktopDataActivityForAddingNewAndDelTests.java.
The documentation for this enum was generated from the following file:
EditDesktopDataActivityForAddingNewAndDelTests.java