SounDroid: com.soundroid.net.NetConnector Interface Reference
com.soundroid.net.NetConnector Interface Reference
Network connector.
Inherited by com.soundroid.net.bluetooth.BluetoothConnector, and com.soundroid.net.wifi.WifiConnector.
Data Structures
enum ConnectionTypes
Connection types, e.g.
Public Member Functions
boolean isConnectedToNet (final Context context)
Return connection to a network.
void connect (final String addr, final String port) throws IOException
Connect to the given address and port.
boolean isAddrReachable (final String addr)
Check availability of the given address.
String getCurVol ()
Get current volume of the remote soundroid daemon.
boolean sendMuteState (final boolean mute)
Send the state of mute to the remote soundroid daemon.
void closeConnection ()
Close the connection to a network.
boolean sendChgVol (final int vol)
Send changing volume to the soundroid daemon.
boolean isConnectedToDaemon ()
Check the connection to the soundroid daemon.
boolean handShake ()
Make hand shake with the soundroid daemon.
boolean isMuted ()
Is the remote soundroid daemon muted.
Data Fields
String HELLO = "hello"
String constant 'hello'.
Detailed Description
Network connector.
Definition at line 41 of file NetConnector.java.
Member Function Documentation
void com.soundroid.net.NetConnector.closeConnection ()
Close the connection to a network.
Implemented in com.soundroid.net.bluetooth.BluetoothConnector, and com.soundroid.net.wifi.WifiConnector.
void com.soundroid.net.NetConnector.connect (final String addr, final String port) throws IOException
Connect to the given address and port.
Parameters
addr The address for connection
port The port for connection
Exceptions
IOException
Implemented in com.soundroid.net.wifi.WifiConnector.
String com.soundroid.net.NetConnector.getCurVol ()
Get current volume of the remote soundroid daemon.
Returns
The string of the volume value
Implemented in com.soundroid.net.bluetooth.BluetoothConnector, and com.soundroid.net.wifi.WifiConnector.
boolean com.soundroid.net.NetConnector.handShake ()
Make hand shake with the soundroid daemon.
Returns
true The handshake has done successfully
Implemented in com.soundroid.net.wifi.WifiConnector, and com.soundroid.net.bluetooth.BluetoothConnector.
boolean com.soundroid.net.NetConnector.isAddrReachable (final String addr)
Check availability of the given address.
Parameters
addr The address string
Returns
true The address is reachable
Implemented in com.soundroid.net.wifi.WifiConnector.
Referenced by com.soundroid.ui.wifi.WiFiConnectingActivity.getConnection().
boolean com.soundroid.net.NetConnector.isConnectedToDaemon ()
Check the connection to the soundroid daemon.
Returns
true Connected to the daemon
Implemented in com.soundroid.net.wifi.WifiConnector, and com.soundroid.net.bluetooth.BluetoothConnector.
Referenced by com.soundroid.ui.bluetooth.BluetoothUI.reInitConnector(), com.soundroid.ui.bluetooth.BluetoothUI.setVolumeUI(), and com.soundroid.ui.wifi.WifiUI.setVolumeUI().
boolean com.soundroid.net.NetConnector.isConnectedToNet (final Context context)
Return connection to a network.
Parameters
context The application's context
Returns
true Connected to a network
Implemented in com.soundroid.net.bluetooth.BluetoothConnector, and com.soundroid.net.wifi.WifiConnector.
Referenced by com.soundroid.ui.DistanceVolumeActivity.isConnectedToNetAfterDialog().
boolean com.soundroid.net.NetConnector.isMuted ()
Is the remote soundroid daemon muted.
Returns
true The daemon is muted
Implemented in com.soundroid.net.wifi.WifiConnector, and com.soundroid.net.bluetooth.BluetoothConnector.
Referenced by com.soundroid.ui.UI.setVolumeUiElements().
boolean com.soundroid.net.NetConnector.sendChgVol (final int vol)
Send changing volume to the soundroid daemon.
Parameters
vol The new volume value
Returns
true The sending has done successfully
Implemented in com.soundroid.net.wifi.WifiConnector.
Referenced by com.soundroid.ui.UI.getOnSeekBarChangeListener().
boolean com.soundroid.net.NetConnector.sendMuteState (final boolean mute)
Send the state of mute to the remote soundroid daemon.
Parameters
mute The state of mute: true - to mute, false - to unmute
Returns
true The sending has done successfully
Implemented in com.soundroid.net.bluetooth.BluetoothConnector, and com.soundroid.net.wifi.WifiConnector.
Referenced by com.soundroid.ui.UI.MuteButton.getMuteButtOnClickListener().
Field Documentation
String com.soundroid.net.NetConnector.HELLO = "hello"
String constant 'hello'.
Definition at line 42 of file NetConnector.java.
Referenced by com.soundroid.net.bluetooth.BluetoothConnector.handShake(), and com.soundroid.net.wifi.WifiConnector.handShake().
The documentation for this interface was generated from the following file:
NetConnector.java